### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by DreaMinder** [nuxt-community/nuxt-i18n#104]
### Version

[v4.1.0](https://github.com/nuxt-i18n/releases/tag/v4.1.0)

### Reproduction link

[https://odesd2.ua/](https://odesd2.ua/)

### Steps to reproduce

1. Open browser in incognito mode
2. Open https://odesd2.ua/ which should run redirect to detected browser language - In server nuxt logs "headers already sent" shows up.
3. Refresh the page with cookie set or enter URL with locale prefix - no error.

### What is expected ?

Logs without errors

### What is actually happening?

Headers already sent error

### Additional comments?

Well, it doesn't affect frontend but makes junk in server logs.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c101">#c101</a>)</em></sub></div>

**Comment by manniL** [comment]
Unfortunately, we can't access the server logs. Could you build up a reproduction repo? :relaxed:

**Comment by DreaMinder** [comment]
https://github.com/DreaMinder/nuxt-i18n-repo/
1. clone, install deps
2. npm run build
3. npm start
4. open localhost:3000 in incognito mode
5. watch your terminal for errors

**Comment by paulgv** [comment]
Hi @DreaMinder 
Thanks for providing a repro! This should be fixed in v5.0.3.
