### ISSUE TITLE
detectBrowserLanguage and cookies

### ISSUE THREAD

**Issue by MisterEffix** [nuxt-community/nuxt-i18n#106]
### What problem does this feature solve?

Root path redirection

### What does the proposed changes look like?

The common way to handle the redirection from root path to the language path is :

1) check if the user already visits the website and redirect him to his latest used language by using a cookie commonly called "lang".
2) if no "lang" cookie is available, use the browser language.
3) if the browser language is unknown or unavailable, use a default language.

I have updated your "middelware.js" following this way.
Maybe it's not 100% clean, but it works.
Could you integrate this behaviour in your nuxt-i18n ?

FX

"middelware.js" modifactions :

  if (detectBrowserLanguage) {
    // Get browser language either from navigator if running in mode SPA, or from the headers
    let browserLocale = null
    if (isSpa && typeof navigator !== 'undefined' && navigator.language) {
      browserLocale = navigator.language.toLocaleLowerCase().substring(0, 2)
    } else if (req && typeof req.headers['accept-language'] !== 'undefined') {
      browserLocale = req.headers['accept-language'].split(',')[0].toLocaleLowerCase().substring(0, 2)
    }

    const localeFromRoute=getLocaleFromRoute(route, routesNameSeparator, locales);

    if (browserLocale) {
      const { useCookie, cookieKey } = detectBrowserLanguage

      const redirectToBrowserLocale = () => {
        const routeName = route && route.name ? app.getRouteBaseName(route) : 'index'
        if (browserLocale && browserLocale !== app.i18n.locale && locales.indexOf(browserLocale) !== -1) {
          redirect(app.localePath(Object.assign({}, route , {
            name: routeName
          }), browserLocale))
        }
      }

      const redirectToCookieLocale = () => {
        const routeName = route && route.name ? app.getRouteBaseName(route) : 'index'
        if (getCookie()) {
          redirect(app.localePath(Object.assign({}, route , {
            name: routeName
          }), getCookie()))
        }
      }

      const getCookie = () => {
        if (isSpa) {
          return Cookies.get(cookieKey);
        } else if (req && typeof req.headers.cookie !== 'undefined') {
          const cookies = req.headers && req.headers.cookie ? cookie.parse(req.headers.cookie) : {}
          return cookies[cookieKey]
        }
        return null
      }

      const setCookie = () => {
        const date = new Date()
        if (isSpa) {
          Cookies.set(cookieKey, localeFromRoute||browserLocale, {
            expires: new Date(date.setDate(date.getDate() + 365))
          })
        } else if (res) {
          const redirectCookie = cookie.serialize(cookieKey, localeFromRoute||browserLocale, {
            expires: new Date(date.setDate(date.getDate() + 365))
          })
          res.setHeader('Set-Cookie', redirectCookie)
        }
      }

      // Handle cookie option to prevent multiple redirections
      if (useCookie) {
        if (!getCookie()) {
          setCookie()
          // Set cookie
          redirectToBrowserLocale()
        }else if (!localeFromRoute){
          setCookie()
          redirectToCookieLocale()
        } else {
          setCookie()
        }
      } else {
        redirectToBrowserLocale()
      }
    }
  }

  // Abort if different domains option enabled
  if (app.i18n.differentDomains) {
    return
  }

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c103">#c103</a>)</em></sub></div>

**Comment by rchl** [comment]
It seems like with your suggested changes, if one goes to `/jp/foo`, there would be no redirection, even if stored cookie has `fr` locale. I kinda like that idea but there would have be special handling for `PREFIX_AND_DEFAULT` mode so that going to `/foo` would still redirect even though `localeFromRoute` would be defined to something.
