### ISSUE TITLE
element-ui  after calling the popup, I found that the attributes of the html tag (such as lang="en-US") were deleted?

### ISSUE THREAD

**Issue by liuhuanhui** [nuxt-community/nuxt-i18n#115]
https://github.com/ElemeFE/element/issues/12378#issuecomment-413163214

Element UI version
2.4.6

OS/Browsers version
GOOGLE

Vue version
2.5.17

Reproduction Link
https://github.com/liuhuanhui/bug01/

Steps to reproduce
https://github.com/liuhuanhui/bug01/
F12, run, check the HTML tag, and then click the button on the page.

**Comment by trylovetom** [comment]
Same Problem Here, 
I try this setting of nuxt-i18n below, solve the problem
`seo: false`

**Comment by paulgv** [comment]
Hi all, there seem to be an issue with the [mixin](https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/seo.js#L13) that handles SEO in nuxt-i18n, it causes some issues with meta tags and other things in the `<head>`, I'm not sure what's the best way to fix this yet, I'll work on it asap. All suggestions/PR are very welcome!

**Comment by liuhuanhui** [comment]
Thank you, I will also see how to solve this problem.
@paulgv

**Comment by liuhuanhui** [comment]
@trylovetom https://github.com/liuhuanhui/nuxt-i18n/commit/8cb7764d60b7ff192904f43b5db2ebc2c4cb9ade 


I used a very good way of repair.

**Comment by manniL** [comment]
@liuhuanhui probably solved with #154
