### ISSUE TITLE
Non-Latin characters encoding issue

### ISSUE THREAD

**Issue by MomenYasser** [nuxt-community/nuxt-i18n#117]
### Version

[v5.1.1](https://github.com/nuxt-i18n/releases/tag/v5.1.1)

### Reproduction link

[https://github.com/MomenYasser/nuxt-i18n-non-encoding-issue](https://github.com/MomenYasser/nuxt-i18n-non-encoding-issue)

### Steps to reproduce

1- git clone https://github.com/MomenYasser/nuxt-i18n-non-encoding-issue
2- npm install
3- npm run dev
4- go to http://localhost:3000/about
5- Check your terminal

### What is expected ?

Expected to encode Non-Latin  characters in URL like Arabic  

### What is actually happening?

I got this error

{ statusCode: 404,
  path: '/ar/%D8%B9%D9%86%D8%A7',
  message: 'This page could not be found' }

[nuxt-i18n] Locale ISO code is required to generate alternate link

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c122">#c122</a>)</em></sub></div>

**Comment by hinex** [comment]
It's fixed on https://github.com/nuxt-community/nuxt-i18n/pull/145
Try to latest version 5.4.4

**Comment by adi-zz** [comment]
Still/again not working, using nuxt 2.5.1 + nuxt-i18n 5.8.5, as can be reproduced using a [codesandbox](https://codesandbox.io/s/6x2153kv43) I created:
- if you open the [homepage](https://6x2153kv43.sse.codesandbox.io/) and click 'about us fr', you get to `https://6x2153kv43.sse.codesandbox.io/fr/a-proposç` - ok
- but, if you try to open https://6x2153kv43.sse.codesandbox.io/fr/a-proposç directly (a SSR request for that page), `This page could not be found` - nok

**Comment by rchl** [comment]
@adi-zz you can set `encodePaths: false` to disable path encoding.

It's probably still a bug but there is a workaround at least.

**Comment by rchl** [comment]
For reference: encoding of paths was added to fix #7

**Comment by gokhancetiner** [comment]
Hello,

Do you have a target date to fix bug that is mentioned by @adi-zz ?

**Comment by Eliav2** [comment]
I have problem uploading projects with non-Latin characters.
demo: https://codesandbox.io/s/non-latin-encode-issue-kf8kh

**Comment by rchl** [comment]
That demo project is using React. Doesn't seem relevant.
