### ISSUE TITLE
Add dateTimeFormats option to config like in Vue i18n

### ISSUE THREAD

**Issue by georgefeast** [nuxt-community/nuxt-i18n#126]
I tried submitting through CMTY but it errored and wouldn't submit

Adding the dateTimeFormats option to the config would allow for auto formatting of localized dates through $d

**Comment by tegola** [comment]
Did you manage to fix this? I'm currently trying to passing dateTimeFormats, but it won't work neither in the main options config or the `vueI18n` property.

**Comment by torgheh** [comment]
Did you guys find a solution for this?

**Comment by rchl** [comment]
See the description of `vueI18n` option in https://nuxt-community.github.io/nuxt-i18n/options-reference.html. You can configure that option using an external JS file which allows you to pass anything you want including functions like `dataTimeFormats`

**Comment by matthiassommer** [comment]
The url given by @rchl ist broken. I suppose https://i18n.nuxtjs.org/options-reference/#vuei18n and https://kazupon.github.io/vue-i18n/api/#constructor-options are the correct ones now.

You can define date filters in nuxt.config.js like so:

```
i18n: {
    vueI18n: {
      dateTimeFormats: {
        en: {
          short: {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
          },
          long: {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            weekday: 'long',
            hour: 'numeric',
            minute: 'numeric',
          },
        },
      },
    },
  },
  ```

**Comment by parabellumKoval** [comment]
Check this breaking changes for Vue 3 (Nuxt 3). `dateTimeFormats` and `datetimeFormats` are not the same. 
https://vue-i18n.intlify.dev/guide/migration/breaking.html#rename-to-datetimeformats-from-datetimeformats
