### ISSUE TITLE
Seo meta data broken

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#127]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/3957#issuecomment-424345190](https://github.com/nuxt/nuxt.js/issues/3957#issuecomment-424345190)

### Steps to reproduce

See [this issue](https://github.com/nuxt/nuxt.js/issues/3957#issuecomment-424345190).

### What is expected ?

No errors

### What is actually happening?

Errors

### Additional comments?

Can be prevented by disabling seo (`seo: false`)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c134">#c134</a>)</em></sub></div>

**Comment by manniL** [comment]
This is not a bug with `nuxt-i18n` but with `vue-meta`. I'll let this open for visibiliy

**Comment by billyshena** [comment]
It seems that downgrading to vue-meta 1.5.3 fixes it for the moment

**Comment by melrefaie** [comment]
After downgrading to vue-meta 1.5.3  i got this error with nuxt 2 

✖ error TypeError: Cannot read property 'text' of undefined
  at Renderer.renderRoute (/myporject/node_modules/nuxt/dist/nuxt.js:2006:15)

**Comment by manniL** [comment]
Resolved with `vue-meta@1.5.5`
