### ISSUE TITLE
Cannot read property 'iso' of undefined

### ISSUE THREAD

**Issue by Livog** [nuxt-community/nuxt-i18n#131]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/Livog/nuxt-i18n-bug](https://github.com/Livog/nuxt-i18n-bug)

### Steps to reproduce

Node Version: 9.7.1
NPM Version: 6.4.1
Nuxt Version: 2.1.0
Nuxt i18n Version: 5.3.0

I m getting this error whenever I install the repo that I linked.
TypeError: Cannot read property 'iso' of undefined

### What is expected ?

No bugs.

### What is actually happening?

This does not seem to cause any problem, just worried it will cause a problem later.

### Additional comments?

I have noticed that I did set parsePages to true I think and then I stopped happening but not sure if that's the case. I have tested it on my mate's computer and he got the same error. This is a very scaled down version of what I m currently working on but it got the same dependencies. If there are parts missing going to API that doesn't work I m sorry.

I renamed the package-lock since my git did not want to push it, don't know why. Just rename it back to lock dependencies. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c142">#c142</a>)</em></sub></div>

**Comment by zlzdp** [comment]
https://nuxt-community.github.io/nuxt-i18n/options-reference.html
read the doc,

you can try this config:
 locales: [
  { code: 'en', iso: 'en-US' }
],

**Comment by priezz** [comment]
I have the same issue, when `vueI18nLoader` is set to `true`, same as in your example repo.  Looks like this loader breaks the `$i18n` contents.
