### ISSUE TITLE
Getting 404 HTTP error code whenever nuxt-i18n is used

### ISSUE THREAD

**Issue by begueradj** [nuxt-community/nuxt-i18n#139]
### Version

v5.4.3

### Reproduction link

[https://github.com/begueradj/nuxti18n-404](https://github.com/begueradj/nuxti18n-404)

### Steps to reproduce

Clone my repo and follow the steps described in README file.

### What is expected ?

I expect to launch the server and not get a 404 error page

### What is actually happening?

The server launches but I am landing all the time on a 404 error page even if I have a simple and clean **/pages/index.vue** file.

### Additional comments?

- It is good if you read this issue first and see the workaround for it: https://github.com/nuxt-community/nuxt-i18n/issues/137

- This problem remains the same even when I downgrade nuxt-i18n version to 5.3.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c150">#c150</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @begueradj 
Does the latest release solve the issue for you?

**Comment by begueradj** [comment]
@paulgv The new release fixed the bug I linked to (#137 ), so congratulations for the good job ! However, I am still getting a 404 error page whenever I declare  nuxt-i18n plugin in **nuxt.config.js** as the official documentation suggests.

**Comment by paulgv** [comment]
Hi @begueradj 
THe problem is you're using nuxt-i18n without any locale, you should configure at least one locale for it to work.

```js
// nuxt.config.js
modules: [
  ['nuxt-i18n', {
    locales: ['en']
  }]
],
```

**Comment by begueradj** [comment]
@paulgv Yes, I know, actually I did 2 projects using this plugin during the last weeks (sorry for not including that in my present settings), however I keep having the same issue after I did what suggested (anyway my 2 previous projects did not work with this version ... and strangely even when I downgrade to 5.3.0 version)

**Comment by paulgv** [comment]
@begueradj when running your updated setup, the app behaves as expected on my end: a `/en` route is created and accessible at [http://localhost:3000/en](http://localhost:3000/en).
Maybe the confusion here comes from the fact that you don't have a default locale set? If you'd like the EN language to be accessible at [http://localhost:3000/](http://localhost:3000/), you'd have to set `defaultLocale` to en too:

```js
['nuxt-i18n', {
  locales: ['en'],
  defaultLocale: 'en',
}]
```

**Comment by begueradj** [comment]
Oh ... I think I am drunk ... I totally forget about the `strategy` option !!! I am VERY sorry to disturb you with this .... it should not be a bug in this case, I guess ... Thank you so much for your patience and help, have a nice weekend and thank you for this great tool

**Comment by paulgv** [comment]
No worries @begueradj !
