### ISSUE TITLE
Feature request: Custom route keys

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#15]
Heyho! First of all: Thanks for marking this module 🙏 

I'm currently building my companies page with "German" (de) as the default language. So far so good. The only thing that annoys me a bit is that the keys in the routes object should match the base routes from Nuxt. I think it'd be better to use them as custom/general keys.

Currently, my route file would look like this:

```js
routes: {
    'about-us': {
      de: '/über-uns'
    },
    work: {
      de: '/referenzen'
    },
    'some-other-long-route-here': {}
   // ...
  },
```

It's a bit annoying because I can't keep the route keys short and often I need to "escape" them with quotes (because of the hyphens).

The best case for the routes file would be 
```js
routes: {
    about: {
      de: '/über-uns',
      en: '/about-us'
    },
    work: {
      de: '/referenzen',
      en: '/work'
    },
    whatever: {
      en: ' some-other-long-route-here'
    }
  },
```

Short and meaningful keys, and clear routing that doesn't depend on the actual components.

But I guess that's a lot of work because you'd need to find out the component for each custom route as well. I'm not sure if that's even possible (except you set it in the config)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c5">#c5</a>)</em></sub></div>

**Comment by paulgv** [comment]
Using Nuxt's base routes feels like the safest thing to do for this feature to prevent any confusions.
Ideally, I'd like to have an option to configure custom routes right in the `.vue` files rather than putting them all in a config file but I'm lacking time to give it a try atm.

**Comment by paulgv** [comment]
Closing this as paths customization has changed a bit since this issue was open.
https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths
