### ISSUE TITLE
Dynamic routes can hijack more specific routes

### ISSUE THREAD

**Issue by rchl** [nuxt-community/nuxt-i18n#152]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/s/ly9pnqvp79](https://codesandbox.io/s/ly9pnqvp79)

### Steps to reproduce

1. Open codesandbox testcase
2. Add `/us` to the URL

### What is expected ?

Page shows 'US' in big letters

### What is actually happening?

Page shows 'FR'

### Additional comments?

This error happens with dynamic nuxt routes. Those are named with `_.vue` (or `_slug.vue` but I haven't checked those).

The bug seems to be in the order in which routes are generated. For example in this case:

```
['nuxt-i18n', {
            locales: [
                {code: 'pt', iso: 'pt-PT', file: 'pt.json'},
                {code: 'fr', iso: 'fr-FR', file: 'fr.json'},
                {code: 'us', iso: 'us-US', file: 'us.json'},
                // ...
            ],
            // ...
            defaultLocale: 'fr',
        }],
```

routes are generated in the order in which languages are defined in `locales` array. With this setting, generated routes will look like this:

```
routes: [
        {
                path: "/pt/*",
                component: _865a92ea,
                name: "all___pt"
        },
        {
                path: "/*",
                component: _865a92ea,
                name: "all___fr"
        },
        {
                path: "/us/*",
                component: _865a92ea,
                name: "all___us"
        }
],
```

As you can see, the 'catch-all' route (default language) was placed before more specific 'us' route. With this setup, 'us' route is inacessible due to routes being matched by iterating routes in the order they are defined.

Problem can be fixed by generating routes in proper order.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c168">#c168</a>)</em></sub></div>

**Comment by rchl** [comment]
More mature implementations like ui-router for angular sort the rules by specificity. It's quite complex algorithm though and I'm not sure exactly about specifics.

**Comment by rchl** [comment]
This is quite a gotcha so should be fixed.

**Comment by pimlie** [comment]
Is case-insensitivity a must for the locale part of routes? If not, you could use similar routes as we do in nuxtpress: https://github.com/nuxt/press/blob/develop/packages/core/src/blueprint/index.js#L435-L440

But those routes are case sensitive due to an issue in path-to-regexp. That issue has been fixed but only in the v3 branch and vue-route and nuxt still use v1 due to breaking changes. I've submitted a pr to backport the fix to the v1 branch but that hasnt been accepted yet: https://github.com/pillarjs/path-to-regexp/pull/195

**Comment by rchl** [comment]
Do you mean to use route param (like `:locale`) for generated routes?
If so then that would mean the validation of supported locales would have to move from routes definition to a middleware.
Also, routes would have extra param. It could potentially be an interoperability issue with existing code.

**Comment by pimlie** [comment]
I am not fully sure how nuxt-i18n validation works in all cases, but if you create a list of supported locales for a route and apply them like we do in nuxtpress there is no validation needed anymore. `path: /:locale(en|pl)/` will match `/en/` and `/pl/` but not `/nl/`

**Comment by rchl** [comment]
Actually that would require quite some refactoring as now code relies on separate routes for each locale so that those can be matched by name. I think I will try fixing it by sorting routes by specificity.
