### ISSUE TITLE
Handle anchors correctly

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#16]
I want to use nuxt-i18n to "translate" anchor links (though it might sound weird).

Example config: 

```js
 locales: [
    {
      code: 'en',
      iso: 'en-US',
      name: 'English'
    },
    {
      code: 'de',
      iso: 'de-DE',
      name: 'Deutsch'
    }
  ],
  defaultLocale: 'en',
    work: {
      de: '/referenzen'
    },
    '#contact-us': {
      de: '#schreib-uns'
    },
```

If I iterate over all links and use the `localePath` function..

```js
  <nuxt-link
          v-for="link in links"
          :key="link"
          :to="localePath(link)">
          {{ $t(`links.link`) }}
```

the anchor tag isn't resolved correctly. I guess that the problem lies in the export of base routes while ignoring other routes that aren't included in the base routes of Nuxt

**Comment by paulgv** [comment]
Hi @manniL !
To translate anchor links, you could simply use **vue-i18n** to generate localized ID's for your DOM.
Here's how I'd do it:
```vue
<template>
  <section>
    <a :href="`#${$t('contactus_anchor')}`">Contact link</a>
    <!-- More stuff here -->
    <div :id="$t('contactus_anchor')">
      Contact content
    </div>
  </section>
</template>
```
And in your translations files:
```js
// en
module.exports = {
  contactus_anchor: 'contact-us'
}

// de
module.exports = {
  contactus_anchor: 'schreib-uns'
}
```

**Comment by manniL** [comment]
Thanks for the fast answer!
I pursued that approach, though it feels a little "hacky". But it works great ☺️

**Comment by israelmuca** [comment]
I know this is closed already, but if someone wants another workaround for this problem, I'm using a `button` with `@click="viewGallery"`
  
  

`viewGallery:`
```javascript
viewGallery() {
      let route = this.localePath("story")+"/#gallery"
      this.$router.push(route)
    }
```
