### ISSUE TITLE
Warning loop since router update in nuxt 2.3.4/1.4.5

### ISSUE THREAD

**Issue by Zsavajji** [nuxt-community/nuxt-i18n#160]
### Version

[v5.4.4](https://github.com/nuxt-i18n/releases/tag/v5.4.4)

### Reproduction link

[https://codesandbox.io/s/y7pqv48y19](https://codesandbox.io/s/y7pqv48y19)

### Steps to reproduce

Navigate to the dynamic route, console is spammed with loop of "[vue-router] missing param for named route "test-all___en": Expected "0" to be defined", in client when navigating, or in server when going directly.

### What is expected ?

Should not produce warnings.

### What is actually happening?

Produces warnings when the route is manually localized in nuxt config.

### Additional comments?

This is maybe a consequence of the new handling of dynamic route params in vue-router 3.0.2. Also happens in nuxt 1.4.5, which has the updated vue-router.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c171">#c171</a>)</em></sub></div>

**Comment by rchl** [comment]
It's this bug: https://github.com/vuejs/vue-router/issues/2505

**Comment by manniL** [comment]
Duplicate
