### ISSUE TITLE
docs: don't suggest to provide a function for lazy loading

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#161]
### What problem does this feature solve?

related: https://github.com/nuxt/nuxt.js/issues/4424
https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c172">#c172</a>)</em></sub></div>

**Comment by felixdenoix** [comment]
In my case an external API is providing me all of the website texts and placeholders and thus, I found that fetching this data asynchronously can be useful. 
The issue I'm facing right now is that I cannot use the installed nuxt-Axios module to fetch these datas and that I had to install the basic Axios module to be able to fetch these.

**Comment by manniL** [comment]
@michaelize Awesome!

@felixdenoix can you second this? ☺️

**Comment by felixdenoix** [comment]
@manniL Seems ok  for me !
