### ISSUE TITLE
Can't read property 'locale' of undefined

### ISSUE THREAD

**Issue by HapLifeMan** [nuxt-community/nuxt-i18n#166]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/HapLifeMan/nuxt-i18n-issue](https://github.com/HapLifeMan/nuxt-i18n-issue)

### Steps to reproduce

1) Clone git repository
2) Generate files with `npm run generate`
3) Open local server on `dist/` folder
4) Try to access `/`, see error

### What is expected ?

As the route generation strategy is configured on `prefix`, and there is no forced `rootRedirect`, it is expected that we are redirected to `/fr` or `/en` depending on the browser language.

### What is actually happening?

Actually, no `index.html` file that redirect us to localized routes is generated in the `dist` folder.
We're stuck on the `/` with no redirect (personally, I have an error `Can't read property 'locale' of undefined.`).

### Additional comments?

Everything is working fine with `npm run build` or `npm run start`, we are redirected correctly.
But I want to have a fully static website with a working root redirection...
Actually to fix temporarily the problem, I defined `fr` as my default locale (strategy `prefix_except_default`).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c179">#c179</a>)</em></sub></div>

**Comment by michaelize** [comment]
@HapLifeMan Can you check if this fix in https://github.com/nuxt-community/nuxt-i18n/pull/178 resolves your issue?

**Comment by HapLifeMan** [comment]
@michaelize Unfortunately this doesn't fix the issue, no `index.html` file is generated on root folder...

**Comment by michaelize** [comment]
I see. This is a different issue than in https://github.com/nuxt-community/nuxt-i18n/issues/173. The strategy is prefix and there isn't an index page to redirect to the default locale folder.

@paulgv Do you think we should have an index.html in the root directory to do the redirection?

**Comment by paulgv** [comment]
@michaelize hmm yeah maybe we should add a `/` when in `generate` mode with `prefix` strategy. But if we do this, users might be able to access an empty page at `/` after being redirected once (if `useCookie` is `true`).
@HapLifeMan how about using `prefix_and_default` strategy instead, would that make sense in your case?

**Comment by michaelize** [comment]
On second thought, creating an index.html seems a bad idea. The module only generates the pages that exist. Creating an index.html will have a higher chance of causing conflicts, for example, if the user has a common index.html in place, we cannot overwrite that index.html.

I think it makes more sense to have the user creates a common entry point for all locales. It can be a page where the user can pick their language preference, something like https://www.apple.com/choose-country-region/

**Comment by HapLifeMan** [comment]
Yes it can be a good solution and resolve a part of the problem @paulgv.
But I don't know what can be the impact on SEO with that kind of redirect...
What will be displayed when you type `myapp` in your browser, what URL will be showed and in which language etc...

**Comment by paulgv** [comment]
Having this kind of redirection will prevent the root path `/` from being indexed at all because all requests will be redirected to one of the prefixed path. More info on 301 redirects: https://moz.com/learn/seo/redirection
As for which URL will show up first in the results, it will probably be the one corresponding to the default redirect most of the time since googlebot does not set the `Accept-Language` header: https://support.google.com/webmasters/answer/6144055?hl=en
