### ISSUE TITLE
[V2.2.1] Localized url's are missing '/' at end, defaultLocale is loaded on full refresh 

### ISSUE THREAD

**Issue by FransTwisk** [nuxt-community/nuxt-i18n#17]
It seems that since V2.2.1 there is no slash added anymore to the localized route, which is a nice feature (because you want to be able to handle '/nl' and '/nl/' , but this doesn't work on initial load: e.g.: it loses the selected language on a full page refresh.

For example: _http://example.com/_ would load in the default locale ('en'). Switching to another language (e.g. 'nl') changes the route to  _http://example.com/nl_ and shows the localized content. However, if I do a full page refresh the route stays on _http://example.com/nl_ but the content is rendered in the default locale again, instead of 'nl'. 

It would be nice if both '/nl' and '/nl/' are supported or if '/nl' would always (try to) redirect to '/nl/'

**Feature request:**
Maybe I should create another issue for this, but I would like to be able to redirect users to a language found in the navigator.languages on initial load. I have a working workaround, also saving the last selected locale in localStorage (so a visitor can still overwrite the default behaviour of redirecting to a matching locale from navigator.languages) and then checking if a returning visitor on the index has a previous language set, but it's not perfect. Any ideas about this?

**Comment by paulgv** [comment]
@FransTwisk thanks for bringing up this issue, it should be fixed in v2.2.3!
The `/xx/` format is currently dropped in favor of `/xx` which seems more standard, if you think both formats should be supported, maybe we should add it as an option?
Concerning your redirect issue, I feel like the best way to do this would be to have your own plugin to override **nuxt-i18n**'s behavior.

**Comment by FransTwisk** [comment]
Thanks for the quick fix! Works perfectly now, with and without the slash at the end. I think this behaviour is fine, just wanted to make sure that if a user explicitly also adds a slash at the end that the right page + language also shows up. 

Concerning the auto-redirect: I'm afraid my Vue skills lack the ability to write a plugin myself, but I'll investigate. I think the only thing I need it so extend the "switchLocalePath" function to save the chosen language to localStorage. Or is there another way to programmatically switch the language through a JS function?

**Comment by bobcat1** [comment]
@FransTwisk let me know how the investigation goes :) I'm also interested in this feature but lack the skills to do it myself.

**Comment by FransTwisk** [comment]
I would like the server to handle this, but don' really know how. Anyway, I ended up using a redirect when locale is found in useragent and using vue-cookie to store the chosen locale if the user still decides to use a different locale. I only use this on the index page, something like:

```
created: function () {
    if (process.client) {
      let locale = cookie.get('locale')
      if (!locale) {
        let userLocale = navigator.languages ? navigator.languages : ([navigator.language] || [navigator.userLanguage])
        if (userLocale.includes('nl')) {
          locale = 'nl'
        }
      }
      this.$router.replace(this.switchLocalePath(locale))
    }
  }
```
