### ISSUE TITLE
Typings are wrong for localePath

### ISSUE THREAD

**Issue by CKGrafico** [nuxt-community/nuxt-i18n#170]
### Version

[v2.3.4](https://github.com/nuxt-i18n/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/nuxt-community/nuxt-i18n/blob/master/types/vue.d.ts](https://github.com/nuxt-community/nuxt-i18n/blob/master/types/vue.d.ts)

### Steps to reproduce

In your typing:
`localePath(route: string | Route, locale?: string): string`

Pass to localePath a string as route:
`this.localePath('performers'); // OK`

Pass to localePath a Route as route:
`this.localePath({ name: 'performers-id', params: { id: '233232' } })`
TypeScript error because Route needs path:

```
export interface Route {
  path: string;
  name?: string;
  hash: string;
  query: Dictionary<string | string[]>;
  params: Dictionary<string>;
  fullPath: string;
  matched: RouteRecord[];
  redirectedFrom?: string;
  meta?: any;
}

```
Working if:
`this.localePath({ name: 'performers-id', params: { id: '233232' } } as any)`
Because the Logic is ok but the typing is not working, path is not necessary in your parameter.

### What is expected ?

Explained in steps.

### What is actually happening?

Explained in steps.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c180">#c180</a>)</em></sub></div>

**Comment by CKGrafico** [comment]
any solution?

**Comment by iliyaZelenko** [comment]
I already did a PR for this: https://github.com/nuxt-community/nuxt-i18n/pull/167.
