### ISSUE TITLE
Nuxt generate

### ISSUE THREAD

**Issue by Frankwarnaar** [nuxt-community/nuxt-i18n#171]
### Version

[4.0.0](https://github.com/nuxt-i18n/releases/tag/4.0.0)

### Reproduction link

[https://deploy-preview-81--miele-laundry-club.netlify.com/nl/](https://deploy-preview-81--miele-laundry-club.netlify.com/nl/)

### Steps to reproduce

Enter a postalCode (for instance `2011JJ`) in the input. You will be redirected to another sub route of the index page.

### What is expected ?

When you refresh, the page should be found.

### What is actually happening?

A 404 is thrown.

### Additional comments?

I'm running a static website, using nuxt generate. On the index page, I'm using child routes. My page structure is as the following:
index.vue
index/
  index.vue
  afspraak-plannen.vue
  nog-niet-actief.vue

For the `afspraak-plannen.vue` and the `nog-niet-actief.vue` pages, the page is not being generated. Because of this, client side navigating to the child page does work, but the server side (static) version is not found, because it's not generated. While generating I see the following errors:

```
 Error generating /nl//nog-niet-actief
 Error generating /nl//afspraak-plannen  
```

It looks like the index folder is not being removed properly from the generated output, causing a duplicate `/` in the path.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c181">#c181</a>)</em></sub></div>

**Comment by michaelize** [comment]
Can you post your configuration? Including the path definition in case it's done in-component.

**Comment by Frankwarnaar** [comment]
My nuxt-i18n config, where defaultLocale is `nl` and `locales` is: 
```
[
  {
    "code": "nl",
    "name": "Nederlands"
  },
  {
    "code": "en",
    "name": "English"
  }
]
```
```
const { locales } = require('../lib/data')
const defaultLocale = locales[0]

/**
 * @see https://nuxt-community.github.io/nuxt-i18n/
 */
module.exports = [
  'nuxt-i18n',
  {
    defaultLocale,
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
    },
    lazy: true,
    langDir: 'static/data/',
    locales: locales.map(locale => ({
      code: locale.code,
      file: `${locale.code}/messages.json`,
      iso: locale.code,
      name: locale.name,
    })),
    rootRedirect: defaultLocale,
    strategy: 'prefix',
    vueI18n: {
      fallbackLocale: defaultLocale,
    }
  }
]
```

The path defined by my folder structure.

**Comment by rchl** [comment]
@Frankwarnaar have you fixed it or maybe new version fixed it for you?
