### ISSUE TITLE
Cannot set property 'locale' of undefined

### ISSUE THREAD

**Issue by willin** [nuxt-community/nuxt-i18n#173]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

- demo: [https://willin.guru](https://willin.guru)
- source: https://github.com/willin/willin.github.io

### Steps to reproduce

when development mode it's ok, but when built and deployed it shown error.

### What is expected ?

works properly

### What is actually happening?

```
c6b25ed7d1e571a9b85f.js:1 [nuxt] Error while initializing app TypeError: Cannot set property 'locale' of undefined
    at f.<anonymous> (c6b25ed7d1e571a9b85f.js:1)
    at 33b42310abd05a803713.js:2
    at 33b42310abd05a803713.js:2
    at Array.forEach (<anonymous>)
    at 33b42310abd05a803713.js:2
    at f._withCommit (33b42310abd05a803713.js:2)
    at f.commit (33b42310abd05a803713.js:2)
    at f.commit (33b42310abd05a803713.js:2)
    at o.commit (33b42310abd05a803713.js:2)
    at f.setLocale (c6b25ed7d1e571a9b85f.js:1)
```

source code: https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/main.js#L41

<img width="1078" alt="wx20181230-005037 2x" src="https://user-images.githubusercontent.com/1890238/50540455-f6998180-0bcc-11e9-9012-5aa5901880fd.png">

state got `undefined`

### Additional comments?

Config:

```js
  modules: [
    ['nuxt-i18n', {
      locales: [
        { name: '简体中文', code: 'zh', iso: 'zh-CN', file: 'zh.js' },
        { name: 'English', code: 'en', iso: 'en-US', file: 'en.js' }
      ],
      lazy: true,
      langDir: 'locales/',
      strategy: 'prefix',
      defaultLocale: 'zh',
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected'
      },
      rootRedirect: 'en',
      vueI18n: {
        fallbackLocale: 'en'
      }
    }]
  ],
```

deployed files: https://dev.tencent.com/u/willin/p/willin.wang/git/tree/master

- ROOT
 - 404.html
 - zh/ folder
 - en/ folder 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c183">#c183</a>)</em></sub></div>

**Comment by michaelize** [comment]
Same issue as in https://github.com/nuxt-community/nuxt-i18n/issues/166

My Nuxt config is: 

```
[
      'nuxt-i18n',
      {
        defaultLocale: 'zh',
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: 'i18n_redirected'
        },
        locales: [
          {
            code: 'en',
            iso: 'en-US',
            file: 'en-US.js',
            name: 'EN'
          },
          {
            code: 'zh',
            iso: 'zh-CN',
            file: 'zh-CN.js',
            name: '中'
          }
        ],
        lazy: true,
        langDir: 'lang/',
        rootRedirect: null,
        strategy: 'prefix_except_default'
      }
    ]
```

I'm deploying with `nuxt generate`. Suspecting that Nuxt hasn't initialized Vuex successfully so that state is returning undefined instead of a function: https://nuxtjs.org/guide/vuex-store#modules-mode

**Comment by pixlforge** [comment]
So funny enough, this issue started happening after I installed Vue devtools beta 5 on Chrome. Went right away after I removed the extension.

**Comment by sustained** [comment]
I have this issue too when clicking "load state" in Vue Devtools.

**Comment by rchl** [comment]
@sustained Can you also check with v6.0.2 just to establish whether it's a recent regression or not.

Also, where is `load state` button in Vue Devtools? I couldn't find that one but if I click `Force refresh` then whole devtools kinda crash (stop reacting).

**Comment by sustained** [comment]
![image](https://user-images.githubusercontent.com/5995080/63867678-2e033c80-c9ad-11e9-9061-b995e93f222c.png)

![image](https://user-images.githubusercontent.com/5995080/63867869-7cb0d680-c9ad-11e9-986a-8f13f1f3d99b.png)

![image](https://user-images.githubusercontent.com/5995080/63867939-a407a380-c9ad-11e9-96c7-de99468caaac.png)

```bash
[sustained@aurora nuxt-dynamic-markdown-example-project]$ cat node_modules/nuxt-i18n/package.json | grep '"version":'
  "version": "6.0.2"
```

@rchl
