### ISSUE TITLE
Detect browser language when using `nuxt generate` (in 'universal' mode)

### ISSUE THREAD

**Issue by tex0l** [nuxt-community/nuxt-i18n#177]
### Version

[v5.4.4](https://github.com/nuxt-i18n/releases/tag/v5.4.4)

### Reproduction link

[https://github.com/tex0l/nuxt-i18n-repro-case](https://github.com/tex0l/nuxt-i18n-repro-case)

### Steps to reproduce

Start a static server on a project built using `nuxt generate` in `'universal'` mode. The test case provided does exactly that with an nginx server started with the result of the `nuxt generate` with docker.

### What is expected ?

The `detectBrowserLanguage` feature should be used, just as in `'spa'` mode.

### What is actually happening?

The `detectBrowserLanguage` feature isn't used, considering it should be done server-side, but since there's no server, it doesn't word at all.

### Additional comments?

The problem lies in the fact that it is done in a middleware: https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js#L101

When using `nuxt generate`, the middlewares are executed at build-time, not at run-time.

I worked around the issue by putting this in my layout's `mounted` method:
```
    if (process.browser) {
      if (this.$cookie.get('i18n_redirected') !== '1') {
        const lang = navigator.language.toLocaleLowerCase().substring(0, 2)
        this.$cookie.set('i18n_redirected', '1')
        this.$router.push(this.switchLocalePath(lang))
      }
    }
  }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c185">#c185</a>)</em></sub></div>

**Comment by T-Zahil** [comment]
Same problem here

**Comment by natemate90** [comment]
Above solution works, but this should be mentioned in the documentation.

**Comment by Sopamo** [comment]
While the above solution might work in specific cases, the middleware is doing [a lot more](https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js) in the meantime. Imo this issue should be fixed in nuxt-i18n, instead of just mentioning it in the documentation.

**Comment by LeBenLeBen** [comment]
I agree on this, it's a pity not to have the detection on generated websites (also trying desperately to make the bot reopen it 😬 )

**Comment by bpeab** [comment]
Also agree. The above solution works but shows the default/fallback language translations before - almost immediately - switching to the detected language which, of course, isn't a wanted behavior.

**Comment by Tommytto** [comment]
Have the same problem, really don't want to use custom decisions, also it is so redundant to make serverside only for language detection(

**Comment by rchl** [comment]
The current code does detect browser language in that case (generated static pages on initial page load). So if you have a specific issue with it please create a new issue with clear steps and/or reproduction.

**Comment by Tommytto** [comment]
@rchl you are right, browser detection works, but it was really strange.
When I've deployed it on Netlify it didn't work, but on Firebase hosting everything works properly

**Comment by heavywar** [comment]
any solution for nuxt 3?
