### ISSUE TITLE
[Nuxt] Error while initializing app TyprError: Object doesn't support property or method 'findIndex'

### ISSUE THREAD

**Issue by andrade1379** [nuxt-community/nuxt-i18n#18]
Hello,

I recently added this module to my project and was running just fine until I tested in IE. I noticed the error in my subject for this ticket. Wanted to know if this is a known issue or if there is a workaround that you recommend?

![screen shot 2018-02-12 at 4 49 36 pm](https://user-images.githubusercontent.com/1234484/36127473-3caddd48-1023-11e8-80f5-9a0702315d7e.png)

I also checked the example website here: [https://nuxt-i18n-example-fzvklkzrln.now.sh/](https://nuxt-i18n-example-fzvklkzrln.now.sh/) and I'm getting the same error being thrown. Is there a workaround for this?

![screen shot 2018-02-13 at 11 02 53 am](https://user-images.githubusercontent.com/1234484/36163259-738afebe-10ae-11e8-8727-addac4bd09a9.png)

The problem that I'm having is in IE it's killing all my other JS from being called like click events etc...

**Comment by andrade1379** [comment]
I ended up using babel es6 polyfill and seems to be working.

**Comment by andrade1379** [comment]
@hlozancic, of course, I can.

1. Add the es6 package to your project. https://yarnpkg.com/en/package/babel-es6-polyfill
2. Add the config for the package within your Nuxt config file like so:
```
/*
     ** Build configuration
     */
    build: {

        vendor: [
            'babel-es6-polyfill',
```
That should be all you need to do. Let me know if that works for you. Good luck!

**Comment by hlozancic** [comment]
Nope still same error... But we resolved this issue on another way.

If anyone else has same problems... this was our solution:

1. To /plugins add findIndex-polyfill.js (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill)
2. to nuxt config, inside plugins add that plugin ~/plugins/findIndex-polyfill.js

Thats it...

**Comment by andrade1379** [comment]
@hlozancic well, I don't know what error you're getting but glad you found a solution.

**Comment by ChrisDillinger** [comment]
Hi all,

Has anyone ran into a similar problem for versions 2.4+ ?
And could someone help me gain some context around what I'm building for by default?

Trying to figure out if I need to add nuxt-polyfill dependency just to add this findIndex polyfill, or if this would be solved by changing a babel related setting?
