### ISSUE TITLE
Feature request: Using json files for storing messages 

### ISSUE THREAD

**Issue by mahmoudmy** [nuxt-community/nuxt-i18n#20]
Thank you guys for this awesome module.
Using `json` files for messages is a standard in i18n.
Another important feature is loading just the active language messages.

**Comment by paulgv** [comment]
Hi @mahmoudmy !
There should be no problem using JSON files to store your translations.
```js
vueI18n: {
  messages: { en: require('./lang/en-US.json') }
}
```
Loading active language only seems to be a most wanted feature, I'd really like to implement it but I'm not sure how to approach it yet and did not have much time to think about it, I hope I'll be able to get to it soon. Any help or ideas are very welcome :)

Thanks!
