### ISSUE TITLE
Support passing path to localePath for easier resolving of dynamic routes

### ISSUE THREAD

**Issue by rchl** [nuxt-community/nuxt-i18n#215]
### What problem does this feature solve?

`localePath` takes either string or object.
String is expected to be route's internal name.
Object, with current implementation of `localePath`, will be passed to VueRouter's resolve function but the `name` property will get `___[locale]` appended to it.

The problem is that the object variant expects `name` to be set, otherwise it will create `name` value like `undefined___[locale]` and route will not match.

Given that it won't work to pass an object with just `{path: '/about'}`, for dynamic routes like `pages/_.vue`, we must instead do an awkward localePath call like `localePath({name: 'all', params: {0: 'about'}})` (haven't really tested but I think it should work). This is IMO too cumbersome and what's more, it requires knowledge of internal route's name. It's basically not user friendly.

### What does the proposed changes look like?

It should be possible to call code below to get localized path to dynamic route
```js
localePath({path: '/about'});
```
and let router figure out the path.

Note that with PREFIX_AND_DEFAULT mode, it should ideally only return path with locale prefix added, if resolving to non-default language OR when current route includes locale prefix.

So (with `en` being default locale):
 - `/about` >> localePath({path: '/about'}) >> `/about`
 - `/en/about` >> localePath({path: '/about'}) >> `/en/about`
 - `/fr/about` >> localePath({path: '/about'}) >> `/fr/about`

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c201">#c201</a>)</em></sub></div>

**Comment by sambrezo** [comment]
I found this information to be very useful for decoupling my CMS and serving content with Nuxt. I'm using the slightly less awkward syntax `{name: 'all', params: ['about']}`, but support for the `path` property is definitely preferable.

I'd like to add that you must add your default locale last to the locales definition, eg:

```
{
  modules: [
    ['nuxt-i18n', {
      locales: [
        { code: 'en', name: 'English', iso: 'en-US' },
        { code: 'de', name: 'Deutsch', iso: 'de-DE' } // <-- Add this last
      ],
      defaultLocale: 'de'
    }]
}
```
So you get the following routes generated for your `_.vue` page in this particular order:
```
[{
  path: '/en/*',
  name: 'all___en'
},
{
  path: '/*',
  name: 'all___de'
}]
```
Else your localized dynamic route never matches.

**Comment by rchl** [comment]
> I'd like to add that you must add your default locale last...

Indeed. It's #152

**Comment by mornir** [comment]
Yes, that would be really nice to have!

**Comment by rchl** [comment]
Makes sense to support it IMO.
