### ISSUE TITLE
Disable route translations for a whole app section

### ISSUE THREAD

**Issue by francoislevesque** [nuxt-community/nuxt-i18n#218]
### What problem does this feature solve?

We are currently building an app with a public section and an admin (protected) section. We need to make the public part fully translated (routes and texts). However, this is not essential for the admin part, since it does not need to be SEO friendly. However, the admin section still needs to show the text in the user's language. The current language does not come from the URL, but from the user's preferences. 

I could build the entire admin section directly with vue-i18n since it does not need url translations. However, I would still need to disable nuxt-i18n on all admin routes (~60 routes), this seems pretty tedious... I haven't found a way to disable URL translations on a route group.

If there's a way, it should be added to the documentation, else I think it would be a pretty handy feature.

### What does the proposed changes look like?

One way of doing this could be to add 
`nuxtI18n: false` on a layout. This would disable route translations on pages using this layout.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c203">#c203</a>)</em></sub></div>

**Comment by rchl** [comment]
If you are willing to disable `parsePages` option, you can use `pages` option to disable language route generation per path. See https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths
If you set specific path to `false` then I think it will not generate prefixed routes.

But if you don't want to create such object for every admin route, then maybe a solution would be to extend that function to support regexp or glob for route paths. That seems like most straight forward way to do it for me.
