### ISSUE TITLE
Vuex store current locale is out of sync when swithing between locales if lazy loading is enabled

### ISSUE THREAD

**Issue by davecoggins** [nuxt-community/nuxt-i18n#221]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/nuxt-community/nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n)

### Steps to reproduce

Have lazy loading enabled and then switch between locales on frontend using the switchLocalePath helper.

### What is expected ?

The vuex store locale value should update

### What is actually happening?

It uses the previous locale value instead which means it lags by one locale as you switch between multiple locales

### Additional comments?

I have tracked in down to the generated code in .nuxt/nuxt-i18n/middleware.js in the if statement checking if lazy loading is enabled the generated code has syncVuex(locale, messages) but it should be syncVuex(newLocale, messages)

Ace plugin btw :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c205">#c205</a>)</em></sub></div>

**Comment by xibman** [comment]
Same problem on 5.8.1
