### ISSUE TITLE
Impossible to add pluralizationRules via the vueI18n options

### ISSUE THREAD

**Issue by lukaVarga** [nuxt-community/nuxt-i18n#237]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link
Not really needed

### Steps to reproduce

1) In `nuxt.config.js`, within the options for the `nuxt-i18n` module, add a `vuei18n` option
2) Add `pluralizationRules: {'en': function(choice, choicesLength) {  return 0 }}` object
3) run `npm run dev`

### What is expected ?

The generated `.nuxt/nuxt-i18n/plugin.main.js` file should initialize `new VueI18n` with `pluralizationRules: {'en': function(choice, choicesLength) {  return 0 }}` parameter

### What is actually happening?

`pluralizationRules` is an empty object

### Additional comments?

This happens because the `vuei18n` options get stringified using `JSON.stringify` [here](https://github.com/nuxt-community/nuxt-i18n/blob/6e11bbc5ecb0df987db71e48ea33a1b7d823cbc9/src/plugins/main.js#L52). The result of `JSON.stringify({foo: function() {return 'bar'}})` is an empty object as the method serializes function as `null` value as you can see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

The option to initialize `VueI18n` with pluralization rules was added recently (see [discussion](https://github.com/kazupon/vue-i18n/issues/464))

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c209">#c209</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment]
Any updates regarding this issue?

**Comment by AndrewBogdanovTSS** [comment]
This issue is not fixed, please, reopen

**Comment by rchl** [comment]
Passing functions through module options would require serialization of function and that is, while possible, generally discouraged by core team. Better option is to support external configuration file that would be `require`d by the module. Then you can use functions without problems.

But I agree it should be re-opened.

**Comment by oppianmatt** [comment]
this is the same problem that causes custom formatter not to work, raised issue here https://github.com/nuxt-community/nuxt-i18n/issues/585

the json.stringify removes any functions/methods so you can't pass a custom formatter as an option

**Comment by pampi848** [comment]
@lukaVarga  try `pluralRules` instead of `pluralizationRules`

**Comment by parabellumKoval** [comment]
Here is the answer #605 
This issue is solved by adding an external configuration file.
