### ISSUE TITLE
Cannot access localePath in middleware

### ISSUE THREAD

**Issue by RomainLK** [nuxt-community/nuxt-i18n#24]
I'm making a middleware which redirects users to some pages depending on the store informations. However, I'm lacking `localePath` to localise the path for the redirect. I expected it to be available as `context.app.localePath`, but it's not.

More interestingly, it's available at `context.app.i18n.vm.localePath` but the `this` context is not correct. `localePath` is somehow bound to a component which has neither `$router` or `$i18n` resulting in an error in i18n.routing.plugin.js

For now I'm running out of idea. I suspect that it might be a problem with nuxt lifecycle between plugins / middleware but it's still obscure.

Versions:
nuxt: 1.3
nuxt-i18n: 2.2.4

**Comment by dave2k2** [comment]
@RomainLK did you ever find a resolution to this? facing a similar issue  using middleware to redirect based on a token existing within the store

**Comment by unr** [comment]
Still haven't found any resolution to this, :(

**Comment by unr** [comment]
Nevermind, actually found the answer to this looking at #25. 

https://github.com/nuxt-community/nuxt-i18n/pull/25/files#diff-6aeb88ffa6a6d00ecc6e8f0487e8d069R66

You can access localePath via `app.localePath`, not `app.i18n.localePath`, like we're all expecting.

**Comment by mrleblanc101** [comment]
Could this be corrected in the doc ? See: https://nuxt-community.github.io/nuxt-i18n/basic-usage.html#nuxt-link

**Comment by paulgv** [comment]
@mrleblanc101 done! Feel free to open PRs to help improve the doc, it can be done right in GitHub by clicking the `Edit this page on GitHub` link at the bottom of each documentation page.
