### ISSUE TITLE
nuxt-i18n does not generate a file named index.html for non default locales

### ISSUE THREAD

**Issue by OfekA** [nuxt-community/nuxt-i18n#240]
### Version

[5.8.5](https://github.com/nuxt-i18n/releases/tag/5.8.5)

### Reproduction link

N/A

### Steps to reproduce

This is my `nuxt-i18n` config:
```js
['nuxt-i18n', {
      locales: [
        { code: 'en', iso: 'en-US', name: 'English', file: 'en-US.js' },
        { code: 'ja', iso: 'ja', name: '日本人', file: 'ja.js' }
      ],
      defaultLocale: 'en',
      lazy: true,
      langDir: 'locale/',
      seo: false
    }]
```

- run `nuxt generate`
- look in the `/dist` folder under non-default locale
- the file that should be `index.html` is called `.html` (no name for the file)

### What is expected ?

`nuxt-i18n` needs to generate a file named index.html for each locale, just like it does for the default locale.

### What is actually happening?

`nuxt-i18n` generates a file named `.html` and not `index.html`, which interferes with site hosting like `Netlify` which expect a file with that name.

### Additional comments?

Is that the expected behavior or am I experiencing a bug?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c211">#c211</a>)</em></sub></div>

**Comment by OfekA** [comment]
I currently solved the issue by running a small renaming script after running `nuxt generate`:

`fix-index-locales.js`
```js
const nuxtConfig = require('../nuxt.config');
var fs = require('fs');

let nuxtI18nConfig = nuxtConfig.modules.find(m => m[0] === 'nuxt-i18n')[1];

nuxtI18nConfig.locales.filter(l => l.code !== nuxtI18nConfig.defaultLocale).forEach(locale => {
  fs.rename(`./dist/${locale.code}/.html`, `./dist/${locale.code}/index.html`, function (err) {
    if (err) console.log('ERROR: ' + err);
  });
});

```

`package.json`
```json
"scripts": {
    "generate": "nuxt generate && node ./build-utils/fix-index-locales.js"
}
```

Hopefully it will help people who have the same issue..

**Comment by miteyema** [comment]
@OfekA I ran into the same problem, see https://github.com/nuxt-community/nuxt-i18n/issues/370

Why has this issue been labelled wontfix?

**Comment by rchl** [comment]
Duplicate of #370

(You didn't mention but I guess you have also used `{ generate: { subFolders: false } }` since that is the prerequisite for the bug to trigger.)

**Comment by rchl** [comment]
(You didn't mention but I guess you have also used `{ generate: { subFolders: false } }` since that is the prerequisite for the bug to trigger.)

**Comment by OfekA** [comment]
> (You didn't mention but I guess you have also used `{ generate: { subFolders: false } }` since that is the prerequisite for the bug to trigger.)

Yup we use that.
