### ISSUE TITLE
Add ability to alter status code with rootRedirect option.

### ISSUE THREAD

**Issue by elisiondan** [nuxt-community/nuxt-i18n#245]
### What problem does this feature solve?

By default, the redirect function sets the HTTP response code to **302 Found**. However, there are situations when it is desirable to set a different status. Specifically, this change avoids the issue with google crawlers which mark the root page and the target page of the *rootRedirect* property as duplicates. This occurs because the crawler expects one of the pages to marked as canonical. In case when the situation is solved with a redirect, the crawler [expects](https://support.google.com/webmasters/answer/139066?hl=en) status code 301. This simple change improves the website SEO when using rootRedirect.

### What does the proposed changes look like?

I attach the updated code and a provided example in the documentation [here](https://github.com/elisiondesign/nuxt-i18n/commit/868b96d60aa46f56d1a3d9a857203fc36a8fab17).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c212">#c212</a>)</em></sub></div>

**Comment by gaelreyrol** [comment]
This issue is real :disappointed:

**Comment by gaelreyrol** [comment]
Does his suggestion suitable ? Do you need a PR @rchl ?

**Comment by rchl** [comment]
I think it makes sense. PR welcome.

**Comment by rchl** [comment]
Resolved by #639
