### ISSUE TITLE
Use different web font when switching language

### ISSUE THREAD

**Issue by nathakits** [nuxt-community/nuxt-i18n#253]
### What problem does this feature solve?

This problem allows for the user to use different types of webfonts suited for different languages. From a design standpoint this is very helpful and essential in showing many webfonts in a website.

### What does the proposed changes look like?

A website that has different webfont for different language.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c214">#c214</a>)</em></sub></div>

**Comment by reneroth** [comment]
Use `vm.$i18n.locale` to read the current language, and use that to apply a class to body / import the correct webfonts.
