### ISSUE TITLE
Locale files are loaded into the rendered html code

### ISSUE THREAD

**Issue by victor192** [nuxt-community/nuxt-i18n#254]
### Version

[v5.8.5](https://github.com/nuxt-i18n/releases/tag/v5.8.5)

### Reproduction link

[https://www.example.org](https://www.example.org)

### Steps to reproduce

1. `npm run build`
1. `npm run start`
2. Open source code of the page

### What is expected ?

That the locale files will be located in a separate js file and not in the page code

### What is actually happening?

Locale files are added in the `<script >` tag in the html code on each page.

### Additional comments?

I use `lazy: true` in module options.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c215">#c215</a>)</em></sub></div>

**Comment by rchl** [comment]
I think it might be due to `vuex` store being enabled (it is by default). You can disable it if you don't need it with `vuex: false`.
