### ISSUE TITLE
I can't setup nuxt-i18n

### ISSUE THREAD

**Issue by Akhail** [nuxt-community/nuxt-i18n#257]
![image](https://user-images.githubusercontent.com/22435967/54826710-bd7e2400-4c86-11e9-87cf-54436d5a22da.png)
![image](https://user-images.githubusercontent.com/22435967/54826755-db4b8900-4c86-11e9-9b0e-3514684b09c4.png)

I follow the official guide but it didn't work, nuxt-i18n has not been injected correctly in the vue instance, it throws me that _vm.$t and this.$i18n does not exists

**Comment by JuanxCursed** [comment]
Hi, did u figure out? 
I've been trying setup this for hours by now and nothing works =/
