### ISSUE TITLE
Not apply detectBrowserLanguage when use redirect in other middleware

### ISSUE THREAD

**Issue by orblazer** [nuxt-community/nuxt-i18n#258]
### Version

[V5.8.5](https://github.com/nuxt-i18n/releases/tag/V5.8.5)

### Reproduction link

Not really needed

### Steps to reproduce

1. Create middleware like that :
```js
export default function ({ app, redirect }) {
  const hasToken = !!app.$apolloHelpers.getToken()

  if (!hasToken) {
    redirect('login')
  }
}
```
2. Enable `detectBrowserLanguage`. I use :
```js
detectBrowserLanguage: {
  useCookie: true,
  alwaysRedirect: true,
  fallbackLocale: 'en'
}
```
3. Try to go `http://localhost:3000/`

### What is expected ?

When use middleware auth and i am not logged need redirect `/` to `/fr/login`

### What is actually happening?

When use middleware auth and i am not logged i am redirect `/` to `/login`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c219">#c219</a>)</em></sub></div>

**Comment by rchl** [comment]
Can you try with latest version (5.11.0)? I believe #283 should have fixed it.
