### ISSUE TITLE
Route is break when nuxt.config is updated

### ISSUE THREAD

**Issue by orblazer** [nuxt-community/nuxt-i18n#259]
### Version

[v5.8.5](https://github.com/nuxt-i18n/releases/tag/v5.8.5)

### Reproduction link

Not really needed

### Steps to reproduce

1. Install `nuxt-i18n`
2. Create routes with like config :
```js
[
  'nuxt-i18n',
  {
  locales: [
    { code: 'en', name: 'English', iso: 'en-US', file: 'en.js' },
    { code: 'fr', name: 'Français', iso: 'fr-FR', file: 'fr.js' }
  ],
  defaultLocale: 'en',
  lazy: true,
  langDir: 'locale/',
  vueI18n: {
  fallbackLocale: 'en',
  dateTimeFormats: {
    fr: {
      long: {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        weekday: 'long'
      },
      timeShort: {
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric'
      },
      timeLong: {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        weekday: 'long',
        hour: 'numeric',
        minute: 'numeric'
      }
    },
    en: {
      long: {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        weekday: 'long'
      },
      timeShort: {
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric'
      },
      timeLong: {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        weekday: 'long',
        hour: 'numeric',
        minute: 'numeric'
      }
    }
  },
  detectBrowserLanguage: {
    useCookie: true,
    alwaysRedirect: true,
    fallbackLocale: 'en'
  },
  onLanguageSwitched: (previous, current) => {
    if (process.client) {
      cookie.serialize('i18n_redirected', current, {
        expires: new Date(new Date() + 365),
        path: '/'
      })
    }
  }
]
```
3. Update `nuxt.config.js`

### What is expected ?

Just update

### What is actually happening?

When `nuxt.config.js` is updated we have
```
 WARN  [vue-router] Route with name 'index___en' does not exist                                                               11:26:56
 WARN  [vue-router] Route with name 'index___fr' does not exist                                                               11:26:56
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c220">#c220</a>)</em></sub></div>

**Comment by dappiu** [comment]
I just experienced a problem that may be related, but seems that your proposed fix it does not solve that too:
the `strategy: 'prefix_except_default'` does not work anymore and prefixes also the defaultLocale, breaking `nuxt-link` references

**Comment by orblazer** [comment]
@dappiu Hello, i have try and not this is work, if the refresh the page this is redirect because `i18n_redirected` is present and is not update when switch locale (i go fix that today)

**Comment by robinscholz** [comment]
Experiencing the same issue

**Comment by Atinux** [comment]
Should this issue be closed since https://github.com/nuxt-community/nuxt-i18n/pull/291 is merged?

**Comment by orblazer** [comment]
@Atinux probably yes, i can't try beacause i no longer use nuxt for now
