### ISSUE TITLE
Long loading time, when use 90 or more languages

### ISSUE THREAD

**Issue by vodniciarv** [nuxt-community/nuxt-i18n#262]
### Version

[v5.8.5](https://github.com/nuxt-i18n/releases/tag/v5.8.5)

### Reproduction link

Not really needed

### Steps to reproduce

1. Create an app.
2. Add 10-20 routes.
3. Add 100 languages.

### What is expected ?

Spped!

### What is actually happening?

Slow loading app.

### Additional comments?

What options (settings) is recoomend to use when in app is 92 languages?
Due to the fact that a huge number of routes (routes) are generated, each page is loaded for a very long time.

Can I somehow solve this problem?

For example, to make so that the routes are not automatically generated for each language ...
Thank you in advance.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c222">#c222</a>)</em></sub></div>

**Comment by vodniciarv** [comment]
Maybe this [pull request](https://github.com/nuxt-community/nuxt-i18n/pull/165) solve this problem?

**Comment by vodniciarv** [comment]
Any Ideas?

**Comment by vodniciarv** [comment]
My `nuxt.config.js`:
```
modules: [
    [
      'nuxt-i18n',
      {
        defaultLocale: 'en',
        strategy: 'prefix',
        detectBrowserLanguage: {
          useCookie: true,
          alwaysRedirect: true,
          cookieKey: 'user_language'
        },
        seo: true,
        lazy: true,
        parsePages: true,
        vuex: {
          moduleName: 'i18n',
          mutations: {
            setLocale: 'I18N_SET_LOCALE',
            setMessages: 'I18N_SET_MESSAGES'
          },
          preserveState: false
        },
        langDir: 'locale/',
        locales: [...]
      }
    ]
  ]
```

**Comment by vodniciarv** [comment]
Any Ideas?

**Comment by vodniciarv** [comment]
@paulgv hello,
will it be possible to solve this problem in future versions?

**Comment by sowinski** [comment]
Same problem here.
Actually I run 90 different domains. en.exmaple.com; fr.example.com etc. 
At the end I just need to load for each "subdomain" only one language file. How can I do this?

**Comment by rchl** [comment]
@sowinski with `lazy` option enabled, only one (or max 2) languages are loaded.

@vodniciarv does `no_prefix` strategy fix your problem?

**Comment by sowinski** [comment]
@rchl 

Thank you for the fast response. I am very happy to get help! :)

I use server side rendering and have only one language per Domain.

Is it possible to just load the exact language which is necessary for each domain?

For example:
www.example.com => en
it.example.com => it
de.example.com => de
...

**Comment by rchl** [comment]
@sowinski configure your nuxt-i18n like described in https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html

Only one language (or two if considering fallback language) is loaded that way.

**Comment by sowinski** [comment]
@rchl 
Thank you. The solution works great!

**Comment by sowinski** [comment]
@rchl 
There is one last problem. If I use lazyloading I see for one second the default language in the browser and after that everything is jumping to the other language.

Can I do this somehow on the server side?

I am using the differentDomains options.

**Comment by rchl** [comment]
@sowinski are you able to reproduce that in a minimal repo?
It shouldn't happen as server side should return page in proper language already and client side should block hydration until language files are loaded. So it would help if you could create small repro (maybe on codesandbox) or at least show your configuration of nuxt/nuxt-i18n.

**Comment by sowinski** [comment]
@rchl 
Yes, I started to build a small repo und it worked. On my current server it is not working ...

**Problem**: I use Apache to proxy all calls to the "Nuxt" server. The "nuxt server" don't see the actual domain. 
_.htaccess_
```
RewriteRule ^myapp/(.*) http://localhost:3000/myapp/$1 [P]
RewriteRule ^_nuxt/(.*) http://localhost:3000/_nuxt/$1 [P]
```
But Apache is adding a header where the traffic came from. I use this also to add it to my store on server side. 
```
xport const actions = {
  async nuxtServerInit({ dispatch }, context) {
    if (context.req.headers['x-forwarded-host']) {
      dispatch('setHostname', context.req.headers['x-forwarded-host'])
    } else {
      context.store.dispatch('setHostname', '10.8.0.1:8000')
    }
    await dispatch('websiteskeleton/getWebsiteSkeleton')
  },
  setHostname({ commit }, hostname) {
    commit('hostname', hostname)
  }
}
```

Can I use the information from: **context.req.headers['x-forwarded-host'])** and pass it to nuxt-i18n to choose the correct language?

**Comment by sowinski** [comment]
Found this: https://github.com/nuxt-community/nuxt-i18n/pull/92
I think this will fix the problem. I will report it tomorrow. 

Thank you :)

**Comment by sowinski** [comment]
On production I got this error:

> [undefined] The `differentDomains` option and `no_prefix` strategy are not compatible. Change strategy or disable `differentDomains` option.
Why can I not use them together?

**Comment by vodniciarv** [comment]
> @vodniciarv does `no_prefix` strategy fix your problem?

Yes, but we need prefix strategy

**Comment by vodniciarv** [comment]
Any ideas to solve it issue?

**Comment by rchl** [comment]
This was never analyzed properly so not sure exactly what was the problem here but it's likely the same as https://github.com/nuxt-community/nuxt-i18n/issues/690

**Comment by nelsonlarocca** [comment]
did you solve the issue ?
Prefix or not prefix should not be a problem.
