### ISSUE TITLE
nuxt-i18n doesn't work with pm2

### ISSUE THREAD

**Issue by WouterFlorijn** [nuxt-community/nuxt-i18n#268]
### Version

[v5.8.5](https://github.com/nuxt-i18n/releases/tag/v5.8.5)

### Reproduction link

[https://dyme.app](https://dyme.app)

### Steps to reproduce

- Install and configure nuxt-i18n.
- `npm run build`
- `pm2 start npm --name "my-project" -- start`
- Configure nginx with `proxy_pass http://localhost:3000`

### What is expected ?

The website works.

### What is actually happening?

Every page shows a standard nginx 502.

### Additional comments?

Note that the link provided is currently working because I rolled back to a version without nuxt-i18n.

When I run locally using `npm run dev` or `npm run build` + `npm run start`, everything works fine.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c228">#c228</a>)</em></sub></div>

**Comment by WouterFlorijn** [comment]
Update: The error logs are pretty clear about what's going on:

> 2019/04/11 19:21:43 [error] 16988#16988: *2823065 upstream sent too big header while reading response header from upstream, client: 77.251.236.80, server: dyme.app, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:3000/", host: "dyme.app"

Why is this happening though? Is my Nginx config too strict regarding header size? Or is there a bug in nuxt-i18n causing huge header sizes?

Also, any idea how I can debug this locally? The response header looks normal when I use `npm run dev`:

```
HTTP/1.1 200 OK
Set-Cookie: @@=1; Max-Age=8640000; Path=/
ETag: "50334-M2zspSvET944Rs/6ptY6UqyLPak"
Content-Type: text/html; charset=utf-8
Accept-Ranges: none
Content-Length: 328500
Date: Thu, 11 Apr 2019 19:32:57 GMT
Connection: keep-alive
```

**Comment by rchl** [comment]
Are you able to log the too-big response?

**Comment by WouterFlorijn** [comment]
@rchl do you happen to know how to do that directly for a nodejs process? The ones I get in the browser (so after going through nginx) are

date: Fri, 12 Apr 2019 11:47:45 GMT
server: nginx
set-cookie: @@=1; Max-Age=8640000; Path=/
status: 304

**Comment by WouterFlorijn** [comment]
By the way, I increased the max header size to 128k and now everything works fine. I mostly would just like to know if this is normal or if there's an underlying issue somewhere.

**Comment by rchl** [comment]
Response header size shouldn't be bigger than few KB. 128k is definitively too much to allow.

All nuxt does is set a language cookie if browser language detection is enabled. Maybe your code is wrong and sets some big string there. Show how you initialize nuxt-i18n maybe.
