### ISSUE TITLE
Warning when langDir is not specified

### ISSUE THREAD

**Issue by lucpotage** [nuxt-community/nuxt-i18n#27]
I got some warnings when using nuxt-i18n 2.3.0 with the last version of the starter template.

```
warning in ./static/robots.txt
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
| User-agent: *
| Disallow: /

 @ . lazy ^\.\/.*$
 @ ./.nuxt/i18n.utils.js
 @ ./.nuxt/i18n.plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js
```

I suspect this is due to the regex in the latest lazy loading feature. If you make an error in your configuration, let's say you don't specify the `langDir` property, then, you will get this error. Maybe, you could prompt a clearer message in such a case.

In async loading mode, if the language file does not exist, there is no error in the terminal.

Hope this can help improve this module.

**Comment by paulgv** [comment]
Hi @lucpotage 
This might be related to #28 and should be fixed in v2.3.2
