### ISSUE TITLE
Structure subpages - not loading

### ISSUE THREAD

**Issue by berenicestr** [nuxt-community/nuxt-i18n#286]
Good Morning,

When I generate subpages in my structure it doesn't generate the link to my url and appears a vue-router error. Any help?

I have this sample structure pages:

pages
 - test
-- index.vue
--dt
---index.vue

In my configuration I have this:

const I18N = {
  vueI18nLoader: true,
  locales: [
    {
      code: 'en',
      name: 'English',
      iso: 'en-US',
      file: 'en-US.js',
      flag: '/EN-flag.png'
    },
    {
      code: 'es',
      name: 'Español',
      iso: 'es-ES',
      file: 'es-ES.js',
      flag: '/ES-flag.png'
    }
  ],
  defaultLocale: 'es',
  fallbackLocale: 'es',
  lazy: true,
  langDir: 'lang/',
  strategy: 'prefix_except_default',
  detectBrowserLanguage: {
    useCookie: true,
    cookieKey: 'i18n_redirected',
    alwaysRedirect: false
  },
  baseUrl: 'https://domain',
  seo: false,
  parsePages: false, // Disable acorn parsing
  pages: {

 test: {
      en: '/test',
      es: '/prueba'
    },
    'test/dt/index': {
      en: '/test/dt',
      es: '/prueba/dt'
    }
...
}

in my view the link to my subpage:
router :to="localePath('test/dt/index')"

this is my error, and it doesn't generate any link:
WARN  [vue-router] Route with name 'test/dt/index___es' does not exist 

Instead when I link to the parent this is OK:
router :to="localePath('test')" 

Please, ¿Any help?

**Comment by ValentinCrochemore** [comment]
Try with `localePath('test-dt')` or look into .nuxt/router.js where all your routes are registered

**Comment by berenicestr** [comment]
Thanks @ValentinCrochemore !!! with localePath('test-dt') it goes OK!!! :-)
