### ISSUE TITLE
Setting base property in Nuxt's router breaks localePath links.

### ISSUE THREAD

**Issue by mcapu** [nuxt-community/nuxt-i18n#29]
Setting this property in `nuxt.config.js`, as per https://nuxtjs.org/api/configuration-router#base:

```javascript
module.exports = {
  ...
  router: {
    base: '/baseURL/'
  },
  ...
}
```

When calling:
```
<router-link :to="localePath('someroute')" />
```

* Expected href: `/baseURL/locale/someroute` (or `/baseURL/someroute` in case it's the default locale).
* Getting: `/baseURL/baseURL/someroute`.

Currently using version 1.1.0, the 2.* versions are crashing for me.

**Comment by paulgv** [comment]
Hi @mcapu ! This issue should be fixed in v2.3.3.
