### ISSUE TITLE
Duplicate route names with prefix_and_default strategy and nuxt-child

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/nuxt-i18n#292]
### Version

[5.12.0](https://github.com/nuxt-i18n/releases/tag/5.12.0)

### Reproduction link

[https://codesandbox.io/s/q3lyoq6vkq](https://codesandbox.io/s/q3lyoq6vkq)

### Steps to reproduce

Structure is following:

```
pages
  account
     child.vue
  account.vue
```

account.vue content
```
<template>
  <nuxt-child/>
</template>
```
### What is expected ?

no duplicate children route generated

### What is actually happening?

duplicate children route generated
```
11:00:57  WARN  [vue-router] Duplicate named routes definition: { name: "account-child___en-us___default", path: "/en-us/account/child" }


11:00:57  WARN  [vue-router] Duplicate named routes definition: { name: "account-child___en-us", path: "/en-us/account/child" }
```

### Additional comments?

Related https://github.com/nuxt-community/nuxt-i18n/issues/140 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c235">#c235</a>)</em></sub></div>

**Comment by rchl** [comment]
Relevant generated routes:
```js
    {
      path: "/account",
      component: _2479bbc0,
      name: "undefined___default",
      children: [{
        path: "child",
        component: _8329b026,
        name: "account-child___en-us___default"
      }, {
        path: "child",
        component: _8329b026,
        name: "account-child___en-us"
      }]
    }, {
      path: "/en-us/account",
      component: _2479bbc0,
      children: [{
        path: "child",
        component: _8329b026,
        name: "account-child___en-us___default"
      }, {
        path: "child",
        component: _8329b026,
        name: "account-child___en-us"
      }]
    }, {
      path: "/fr/account",
      component: _2479bbc0,
      children: [{
        path: "child",
        component: _8329b026,
        name: "account-child___fr"
      }]
    }
```
Problems:
- there are two children per locale route (should be just one)
-  the `undefined` in /account route also looks wrong

**Comment by aldarund** [comment]
undefined goes from https://github.com/nuxt-community/nuxt-i18n/blob/dc668952c4501c2e0b95603dd838b47ec18db0b9/src/plugins/routing.js#L28
e.g. name is not undefined and it appends prefix to it and hence the undefiend__default

**Comment by rchl** [comment]
Yes, looks like routes with children are not supposed to have name because one is not supposed to navigate to child routes directly.
