### ISSUE TITLE
multiple domains is broken - 'req is not defined'

### ISSUE THREAD

**Issue by gianniskarmas** [nuxt-community/nuxt-i18n#293]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/s/wwwp0jpxow?from-embed](https://codesandbox.io/s/wwwp0jpxow?from-embed)

### Steps to reproduce

still haven't dug deep enough but after upgrading I started getting this error

### What is expected ?

Multiple domains to work

### What is actually happening?

req is not defined

### Additional comments?

Adding req in
```
export default async (context) => {
  const { app, route, store, res, req } = context;
```
within /node_modules/nuxt-i18n/src/main.js solves the problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c236">#c236</a>)</em></sub></div>

**Comment by rchl** [comment]
Clearly a bug from my changes, will fix ASAP.
