### ISSUE TITLE
Implicit dependency on `vue-template-compiler`

### ISSUE THREAD

**Issue by pi0** [nuxt-community/nuxt-i18n#297]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/nuxt/now-builder/issues/42](https://github.com/nuxt/now-builder/issues/42)

### Steps to reproduce

-

### What is expected ?

-

### What is actually happening?

-

### Additional comments?

This module has an implicit dependency on `vue-template-compiler` [here](https://github.com/nuxt-community/nuxt-i18n/blob/master/src/helpers/components.js#L6). All direct dependencies like this should be specified in `dependencies` section of package.json.  When using `nuxt-start` (a serverless) build of nuxt, this dependency is not available.

It is also better to only require build related deps on `build:before` nuxt hook to prevent additional overhead when running in production mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c237">#c237</a>)</em></sub></div>

**Comment by rchl** [comment]
This code is running when generating extra locale routes.

Nuxt generates routes in this order:
 - generate default routes
 - call `build:extendRoutes` hook
 - process routes returned from `options.router.extendRoutes` function (if defined)

This module uses `ModuleContainer.extendRoutes(fn)` to hook into processing of `options.router.extendRoutes`.

So even when no actually using a hook (because `build:extendRoutes` would happen at wrong time for this module anyway), I think it's OK to keep using `ModuleContainer.extendRoutes(fn)` as then the function shouldn't be called on start of built app, right?

**Comment by rchl** [comment]
@pi0 you think #298 is a good solution to both problems?

**Comment by pi0** [comment]
@rchl yes, that totally makes sense. Thanks for the PR.

**Comment by rchl** [comment]
@pi0 @paulgv I have just noticed a problem with this change.

With nuxt@2.4.5 version at least, I see this error when trying to `build`:

```
Vue packages version mismatch:

- vue@2.6.7 (/Users/rchlodnicki/workspace/tidal-com/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/rchlodnicki/workspace/tidal-com/node_modules/nuxt-i18n/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


  Error:

  Vue packages version mismatch:

  - vue@2.6.7 (node_modules/vue/dist/vue.runtime.common.js)
  - vue-template-compiler@2.6.10 (node_modules/nuxt-i18n/node_modules/vue-template-compiler/package.json)

  This may cause things to work incorrectly. Make sure to use the same version for both.
  If you are using vue-loader@>=10.0, simply update vue-template-compiler.
  If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

  at Object.<anonymous> (node_modules/nuxt-i18n/node_modules/vue-template-compiler/index.js:10:9)
  at Generator.next (<anonymous>)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)


   ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                    │
   │   ✖ Nuxt Fatal Error                                                                                                                               │
   │                                                                                                                                                    │
   │   Error:                                                                                                                                           │
   │                                                                                                                                                    │
   │   Vue packages version mismatch:                                                                                                                   │
   │                                                                                                                                                    │
   │   - vue@2.6.7 (/Users/rchlodnicki/workspace/tidal-com/node_modules/vue/dist/vue.runtime.common.js)                                                 │
   │   - vue-template-compiler@2.6.10 (/Users/rchlodnicki/workspace/tidal-com/node_modules/nuxt-i18n/node_modules/vue-template-compiler/package.json)   │
   │                                                                                                                                                    │
   │   This may cause things to work incorrectly. Make sure to use the same version for both.                                                           │
   │   If you are using vue-loader@>=10.0, simply update vue-template-compiler.                                                                         │
   │   If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.                    │
   │                                                                                                                                                    │
   │                                                                                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```

It seems like versions of `vue` and `vue-template-compiler` must match exactly. I think this line is responsible for that:
https://github.com/vuejs/vue/blob/1137e415c9e8701d1b0a25e5812f8c4dffeeeaaa/packages/vue-template-compiler/package.json#L29
Given that `vue` comes from `nuxt`, I don't know how to ensure that those are always synchronized. Any idea?

**Comment by pi0** [comment]
@rchl we can either come back to implicit dependency (and only require for build time) or use `this.nuxt.resolver.requireModule` to require `vue-template-compiler`.

**Comment by rchl** [comment]
@pi0 thanks. Created #305. Please double check I did the right thing.
