### ISSUE TITLE
How to have multiple aliases for the same page?

### ISSUE THREAD

**Issue by adi-zz** [nuxt-community/nuxt-i18n#30]
I want URLs having 2 different patterns to point to the same page:
- for cars with odd id: `/en/car/1`, `/voiture/1`
- for cars with even id: `/en/latest/2`, `/nouveau/2`

(both should render the same `/pages/cars/show.vue` component)

Could this be implement with the current version? And I wonder how both `routes: { ... }` object and `localePath( ... )` call should look.

Thanks for this module.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c20">#c20</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @adi-zz 
This is currently not possible with current version but it would certainly be an interesting feature.
In the meantime you could probably "hack" your way to a solution by using other pages that export the page's module you'd like to translate, kinda like it's done in Nuxt's i18n official example: https://nuxtjs.org/examples/i18n

**Comment by 1hakr** [comment]
How can you use this when you have dynamic routes, i mean how do you pass params to a vue page

**Comment by 1hakr** [comment]
I was able to achieve this with declaring another path in extendRoutes instead of using `alias` by extending router module

```
extendRoutes (routes) {
  routes.push({name: 'old-path', path: '/old-path', component: '~pages/index.vue'})
}
```

I hope this i will be useful to others.
