### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by rchl** [nuxt-community/nuxt-i18n#300]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html](https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html)

### Steps to reproduce

-

### What is expected ?

-

### What is actually happening?

-

### Additional comments?

There are some changes to documenation that are not yet deployed to documentation site. For example https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html should have some more stuff.
Can we deploy new documentation?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c238">#c238</a>)</em></sub></div>

**Comment by paulgv** [comment]
Just came across this issue. Closing as there have been a few docs deploys since.
