### ISSUE TITLE
Dynamic import is broken when using nuxt-i18n

### ISSUE THREAD

**Issue by tex0l** [nuxt-community/nuxt-i18n#301]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/embed/l4921qqll7](https://codesandbox.io/embed/l4921qqll7)

### Steps to reproduce

Run `yarn run dev` in the repro link.

### What is expected ?

It should work.

### What is actually happening?

`ERROR  Unexpected token (6:16)`

### Additional comments?

The dynamic import of `Logo.vue` in `index.vue` breaks nuxt-i18n. Dynamic import is supported (and even used on their website) by nuxtjs to enable webpack to split the code.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c239">#c239</a>)</em></sub></div>

**Comment by rchl** [comment]
Dup of #134

**Comment by paulgv** [comment]
Should be fixed in [`v5.12.4`](https://github.com/nuxt-community/nuxt-i18n/blob/master/CHANGELOG.md#5124-2019-06-02)
