### ISSUE TITLE
Cannot read property '_t' of null & Cannot read property 'locale' of null

### ISSUE THREAD

**Issue by fanwenfu** [nuxt-community/nuxt-i18n#317]
Version
v5.12.3

Reproduction link
Not necessarily reproduce
![image](https://user-images.githubusercontent.com/25945917/58614230-6af65f00-82ea-11e9-84f2-8b466152e5cd.png)
![image](https://user-images.githubusercontent.com/25945917/58614257-7c3f6b80-82ea-11e9-849b-21564c4447d7.png)
![image](https://user-images.githubusercontent.com/25945917/58614281-8fead200-82ea-11e9-9b09-b6fd9c85efc0.png)

What is expected ?
Working normally

My configuration
![image](https://user-images.githubusercontent.com/25945917/58614116-1652e400-82ea-11e9-889b-bcd3e4eebbc9.png)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c242">#c242</a>)</em></sub></div>

**Comment by rchl** [comment]
Are you able to create minimal testcase on codesandbox? I feel this could be a problem with how you use i18n instead of the module itself.

**Comment by MLDMoritz** [comment]
I also get `Cannot read property 'locale' of null` in this part:

```js
if (!route) return;
locale = locale || this[i18nPath].locale;

**Comment by rchl** [comment]
Can't help unless you show the code. It can happen if i18n mixin methods are used from wrong `this` context but that doesn't mean there is a bug in this module, necessarily.

**Comment by fanwenfu** [comment]
> Can't help unless you show the code. It can happen if i18n mixin methods are used from wrong `this` context but that doesn't mean there is a bug in this module, necessarily.

Because it's not inevitable.So I don't know how to create minimal testcase on codesandbox.
![image](https://user-images.githubusercontent.com/25945917/59249135-a5e78380-8c56-11e9-850f-f8f089287fcc.png)

Except for pages, there are only two places where locale is used
![image](https://user-images.githubusercontent.com/25945917/59249767-1c38b580-8c58-11e9-9505-5d20dbaaaa7a.png)

**Comment by fanwenfu** [comment]
> Can't help unless you show the code. It can happen if i18n mixin methods are used from wrong `this` context but that doesn't mean there is a bug in this module, necessarily.

Because it's not inevitable.So I don't know how to create minimal testcase on codesandbox.
Except for pages, there are only two places where locale is used

![image](https://user-images.githubusercontent.com/25945917/59250548-32e00c00-8c5a-11e9-9102-073b596e51f9.png)

**Comment by dschreij** [comment]
I have the same problem. It mainly seems to occur when I use i18n functions in the head(){} function of my page (in which i use them to populate ld+json fields). Strangly, it only occurs on a second load of the page. On first load, or after a hard reload, everything works as expected.
Using:
nuxt: 2.9.2
vue: 2.6.10
nuxt-i18n: 6.2.1
vue-i18n; 8.14.1 (it is separately listed in my package.json).

**Comment by rchl** [comment]
@dschreij your problem seems to be related to using `head` (vue-meta) more so than i18n itself.  You've posted two completely different stack traces, one is unrelated to `$t` or `vue-i18n` itself. I'm pretty sure using any property of Vue object, even one unrelated to nuxt-i18n or vue-i18n will crash. So I would look for problems elsewhere.

**Comment by rchl** [comment]
For example try replacing `this.$t` with `this.$route.path`. I think it might fail similar way.

**Comment by dschreij** [comment]
> For example try replacing this.$t with this.$route.path. I think it might fail similar way.

That works, otherwise it would have crashed on the first line of `head(){}` in the first example, which uses `this.$route.path` 

> You've posted two completely different stack traces, one is unrelated to $t or vue-i18n itself.

The first stack trace refers to `this.localePath`, which is a function of nuxt/vue-i18n as far as I know. The second example chokes on this.$t. 

I agree this error is likely caused by a combination of vue-meta and i18n, but am I and the OP the only ones experiencing them?

**Comment by dschreij** [comment]
This has been fixed in the newest versions of nuxt, and potentially vuetify

**Comment by rchl** [comment]
Just a note for people potentially finding this through search - using `$t` or other `vue-i18n` APIs can crash if using them from async functions since component can get destroyed in the meantime.

**Comment by SebastienTainon** [comment]
Thanks, I has exactly the same problem and that helped a lot!

**Comment by rhwilr** [comment]
I encountered this problem as well but it is caused by a slightly different scenario:

```html
<template>
  <div @click="navigate">To Dashboard</div>
</template>

<script>
export default {
  methods: {
    navigate () {
      this.$router.push(this.localePath({ name: 'dashboard' }))
    }
  }
}
</script>
```

This works perfectly fine. However, when the user douple-clicks the link, the first click will trigger the navigation, the second click will throw the error, since the component has already been unmounted.

**Comment by rchl** [comment]
@rhwilr Thanks for that example - can be useful for people who stumble on this error.

Just a note that that particular case can be simplified to something that potentially won't have the same problem (I haven't tried though):
```vue
<template>
  <nuxt-link :to="localePath('dashboard')">To Dashboard</nuxt-link>
</template>
```
(But maybe that example was oversimplified to just show the issue)
