### ISSUE TITLE
Assets and routes

### ISSUE THREAD

**Issue by lucpotage** [nuxt-community/nuxt-i18n#32]
I try to bind my image src attribute and use a path that depends on the current locale:

`<img :src="'~/assets/image-' + $i18n.locale + '.svg'">`

However it does not work and the output is:

`<img src="~/assets/image-en.svg">`

Another issue is with video posters, my paths don't work. Any idea?

`<video poster="~/assets/poster.png">...</video>`

**Comment by manniL** [comment]
You cannot use "dynamic paths" that change at runtime because webpack evaluates them before.

An easy solution for this is to move the images in the static folder and link to them with `:src= "'/image-' + $i18n.locale + '.svg'"`

**Comment by nelsonlarocca** [comment]
so for each image also we would need to check if the image exists otherwise get the "fallback" one.
