### ISSUE TITLE
Release brokes IE 11

### ISSUE THREAD

**Issue by shlima** [nuxt-community/nuxt-i18n#329]
### Version

[v5.2.1](https://github.com/nuxt-i18n/releases/tag/v5.2.1)

### Reproduction link

[http://ie11.com](http://ie11.com)

### Steps to reproduce

nuxt-i18n v5.12.5 adds the `is-https` dependency, which code is not transpiled properly.

IE 11 fails in the following line here: (default function arg xForwardedProto = true)

```js
function isHTTPS(req, xForwardedProto = true) {
...
}
```
With the following error:

```
SCRIPT1006: Expected ')'
```

### What is expected ?

Works

### What is actually happening?

Not working

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c250">#c250</a>)</em></sub></div>

**Comment by paulgv** [comment]
@rchl WDYT? Could you have a look?

**Comment by rchl** [comment]
It does indeed look like default arguments are not transpiled in nuxt. Compiled bundle has this code:
```
t.exports = function(t, e = !0) {
```
@pi0 Do you have any take on this? Is Nuxt supposed to support IE11?

**Comment by rchl** [comment]
BTW. Given that it's not even needed on the client, we could work around that by conditionally requiring it but then I would need to mix `require` and es6 imports which I'm not sure is a good idea...

**Comment by shlima** [comment]
> @pi0 Do you have any take on this? Is Nuxt supposed to support IE11?
 
Nuxt, vue and nuxt-i18n worked perfect in IE 11 before

**Comment by rchl** [comment]
Then I wonder why is Nuxt not transpiling that construct...

**Comment by rchl** [comment]
I will require it conditionally for now which will fix that problem (and as a bonus, make client bundle tiny bit smaller). I would be vary of mixing `require` and `es imports` but since `middleware.js` already does that for `./utils`, I guess it should work (for now at least).

**Comment by paulgv** [comment]
Sounds good, thanks @rchl
