### ISSUE TITLE
Nested fixed routes example

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#33]
Hey again!

I'm currently having the following route construct:
```
pages/
├── work/
│   ├── index.vue
│   ├── foobar.vue
│   ├── bazfoo.vue
```

Now I want to translate the work route but leave the child routes "as they are".

`/work` -> `/newname` (linking to /work/index.vue)
`/work/foobar` -> `/newname/foobar`
`/work/bazfoo` -> `/newname/bazfoo`

Is this achievable? If so, do I need to add each route manually? :thinking:

**Comment by paulgv** [comment]
Hi @manniL 
With your current files structure, foobar and bazfoo aren't treated as children routes and you would have to setup each route translation manually to achieve what you want.
However, you could add a `work.vue` page in the `pages/` directory, this would cause all pages in the `pages/work/` directory to be considered as children of `work`, in this case, you'd be able translate the root `work` route only.
In any case, I'd recommend you keep an eye on `.nuxt/route.js` where your real routes reside, it can be very useful to understand exactly how Nuxt & nuxt-i18n are dealing with your routes.
Hope it helps! :)

**Comment by manniL** [comment]
Thanks for the great explanation! :relaxed:
