### ISSUE TITLE
Load fallback language when needed (lazy-load)

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#34]
nuxt-i18n version: 2.3.4

Imagine you have two languages, `en` (default) and `de`.
But only parts of the `en` language is localized in the `de` file.
If you now enter a page (e.g. `/de/only-half-localized-route`), you see the correct translations (for de) where it applies, but no en translation because the fallback language isn't loaded properly because of lazy-loading. Instead, you see the translation keys.

A naive fix for it would be to load the fallback language every time, but I guess there is a way to check if a fallback is needed and load the fallback language in that case (if not already loaded).

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c39">#c39</a>)</em></sub></div>

**Comment by maximivanov** [comment]
Any update on this? Or before feature is implemented, what's the way to load fallback language every time? (and not load all of language files at the same time)

**Comment by scippio** [comment]
Any news?

**Comment by RecuencoJones** [comment]
As a workaround for now we might be using the following:

```javascript
// nuxt.config.js
module.exports = {
  srcDir: './src',
  ...
  modules: [
    '@nuxtjs/pwa',
    [
      'nuxt-i18n',
      {
        locales: [
          { code: 'en', iso: 'en-US', file: 'en.js' },
          { code: 'es', iso: 'es-ES', file: 'es.js' }
        ],
        defaultLocale: 'en',
        vueI18n: {
          fallbackLocale: 'en'
        },
        lazy: true,
        langDir: 'locales/'
      }
    ]
  ],
  ...
};

// src/locales/es.js
import { assignWith } from 'lodash';
import { loadTranslation } from '../services/contents';

const useDefault = (value, defaultValue) =>
  typeof value === 'object' ?
    assignWith({}, value, defaultValue, useDefault) :
    value || defaultValue;

export default () => Promise.all([
  loadTranslation('en'),
  loadTranslation('es')
])
.then(([ defaultMessages, localizedMessages ]) => 
  assignWith({}, localizedMessages, defaultMessages, useDefault));
```

**Comment by JkmAS** [comment]
@RecuencoJones how does the `loadTranslation` function look like? Are you using axios or nuxt-axios in `loadTranslation`? Thx.

**Comment by rchl** [comment]
Would it be possible to prioritize it? I think it's a major missing feature.

**Comment by rchl** [comment]
Possibly simpler workaround:

In nuxt_config.js, using `require` or `import`, load default locale manually and pass to `vue-i18n` configuration:

```
[
      'nuxt-i18n',
      {
            // ...
            vueI18n: {
                fallbackLocale: 'en',
                messages: {
                    en: require(`./app/locales/en.json`),
                },
            },
      }
],
```

**Comment by kevinpiac** [comment]
@rchl you solution works well and seems to be the simplest one. 

However, this missing feature is really important and should be prioritized!

**Comment by MarvinMiles** [comment]
My function for load fallback language when needed

/plugins/i18n.js:

```
export default ({ app }, inject) => {

inject ('loadLanguageAsync', async (lang) => {
    if (app.i18n.locale !== lang) {
      if (!app.i18n.loadedLanguages.includes(lang)) {
        try {
          const module = await import(/* webpackChunkName: "lang-[request]" */ `@/lang/${lang}`)
          const messages = module.default ? module.default : module
          app.i18n.setLocaleMessage(lang, typeof messages === 'function' ? await Promise.resolve(messages()) : messages)
          app.i18n.loadedLanguages.push(lang)
        } catch (error) {
          console.error(error)
        }
      }
      app.i18n.locale = lang
    }
  })

}
```
then call "this.$loadLanguageAsync(lang)" from anywhere

I am using this for translating via keyboard shortcuts events :)

Hope this will help someone

**Comment by rasgo-cc** [comment]
I can confirm this as well. Using nuxt `2.5.0`.
Meaning this option won't work at all for lazy loaded messages.
```
        vueI18n: {
          fallbackLocale: 'en'
        }
```

**Comment by manniL** [comment]
@MarvinMiles 	would you mind sending in a PR?

**Comment by sugoidesune** [comment]
> ```js
>         vueI18n: {
>           fallbackLocale: 'en'
>         },
> ```

This is what i needed! thank you!

**Comment by tvld** [comment]
No sure why this issue is closed. Today, bug still exists in latest nuxt. ``2.11.0``.  It really is needed to add t o literature that fallback settings in nuxt.config are useless without, the ``vueI18n: {
          fallbackLocale: 'en'
        },`` mentioned above

**Comment by golubvladimir** [comment]
I have this bug.
My nuxt version `2.11.0`.

This solution does not work.

```
            vueI18n: {
                fallbackLocale: 'en',
                messages: {
                    en: require('./app/locales/en.json'),
                },
            },
````

**Comment by rchl** [comment]
@golubvladimir Since this bug was fixed, you don't need to manually load messages using `require`. You are probably breaking the fallback functionality by doing so.

And I don't understand why do you have different paths to `en` messages in different places. In one it's `./app/locales/en.json`, in another the file is called `en-US.js`.

I think the issue is with your configuration. You can create a separate issue if you need some help but you should create reproduction on https://codesandbox.io/

**Comment by golubvladimir** [comment]
@rchl 
My config:
```
  i18n: {
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en'
    },
    detectBrowserLanguage: {
      useCookie: false,
    },
    strategy: 'no_prefix',
    locales: [
      {
        code: 'ru',
        name: 'Russian',
        file: 'ru-RU.js'
      },
      {
        code: 'en',
        name: 'English',
        file: 'en-US.js'
      }
    ],
    differentDomains: false,
    forwardedHost: false,
    lazy: true,
    langDir: 'lang/',
    parsePages: false,
  },
```
// en-US.js
```
export default require('./json/en');
```

**Comment by golubvladimir** [comment]
It does not work.
```
    locales: [
      {
        code: 'ru',
        name: 'Russian',
        file: 'json/ru.json'
      },
      {
        code: 'en',
        name: 'English',
        file: 'json/en.json'
      }
    ],
```

**Comment by rchl** [comment]
@golubvladimir You are repeating yourself, please create small reproducible case on codesandbox if you want some help.

**Comment by golubvladimir** [comment]
@rchl created, but it did'nt work on codesandbox
https://codesandbox.io/s/optimistic-brook-dc77u?fontsize=14&hidenavigation=1&theme=dark

**Comment by golubvladimir** [comment]
@rchl it work on codesandbox https://codesandbox.io/s/optimistic-brook-dc77u?fontsize=14&hidenavigation=1&theme=dark

**Comment by rchl** [comment]
@golubvladimir so no problem then?

**Comment by golubvladimir** [comment]
@rchl Yes, update to 6.5.0. It helped.

**Comment by tvld** [comment]
Related to this issue is a problem that if we have a non-language file like for example ``README.md`` in the ``langDir``, the compiler breaks. Which I think is weird, as should nuxt-i18n not _only_ load the files specified with ``locales: [{file: 'en.js',..},..]`` ?
