### ISSUE TITLE
No way to set default locale dynamically?

### ISSUE THREAD

**Issue by AsamyX** [nuxt-community/nuxt-i18n#341]
Do I have to set default locale in `nuxt.config`?

The case with my project is that the locale consists of both language and country.   i.e  en-UK

So I set `defaultLocale` to `null` in `nuxt.config`
I capture user country from their IP @ nuxtServerInit, and I try to dispatch `i18n/setLocale, 'en-UK'` right after.

Unfortunately `app.i18n.locale` always returns null, and the whole project just crashes.

Is there any way to achieve my goal with nuxt-i18n?

**Comment by Eleventiy** [comment]
Same problem. Anyone have solution?

**Comment by rchl** [comment]
There is feature request for it that should probably be re-opened #207

**Comment by rchl** [comment]
There is now `setLocale` API (in version 6.x) which might work for this (hopefully, depends on the order of things happening).
