### ISSUE TITLE
Translate function breaks when used in store or asyncData

### ISSUE THREAD

**Issue by Frankwarnaar** [nuxt-community/nuxt-i18n#343]
### Version

[5.12.7](https://github.com/nuxt-i18n/releases/tag/5.12.7)

### Reproduction link

[https://github.com/Frankwarnaar/nuxt-i18n-translate-from-store-bug-report](https://github.com/Frankwarnaar/nuxt-i18n-translate-from-store-bug-report)

### Steps to reproduce

Run `npm install` and then `npm run dev`. Then open http://localhost:3000.

### What is expected ?

In vue's `mounted` lifecycle hook on the index page, I dispatch my action  `alertTranslation`, in which I alert the output of i18n's `$t` function.

### What is actually happening?

When running the $t function in the store, an exception is thrown: `TypeError: Cannot read property 'apply' of undefined`

### Additional comments?

I've seen the same issue before, when I was trying to use the `$t` function is nuxt's `asyncData` lifecycle hook.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c254">#c254</a>)</em></sub></div>

**Comment by rchl** [comment]
It probably never meant to work. `this` inside of store is an instance of `Store` and neither vue-i18n or nuxt module promises it working there.

**Comment by rchl** [comment]
That said, `nuxt-i18n` by default pushes all translations to the store so you can access your key with `context.state.i18n.messages.translation_key`.

**Comment by Frankwarnaar** [comment]
Alright, good to know we're not supposed to use it in the store. Your workaround will do, so thank you for that!

**Comment by lautr** [comment]
i'll just leave this here in case somebody needs to use the translate method inside `asyncData`

```
export default ({ app }, inject) => {
  const _t = (key, values) => {
    // this looks odd, but is the way the translate has to be called outside of a template
    return app.i18n._t.apply(
      app.i18n,
      [key, app.i18n.locale, app.i18n._getMessages(), this].concat(values)
    )
  }

  inject('ta', (key, values) => {
    return _t(key, values)
  })
}
```

**Comment by rchl** [comment]
Actually it should *just work* (not sure if it was fixed or I was wrong before).

Example here: https://codesandbox.io/s/nuxt-i18n-string-from-asyncdata-fx64z
