### ISSUE TITLE
Routes with children have no name thus localePath(route with children) always returns the root path

### ISSUE THREAD

**Issue by popescuandrei9mai** [nuxt-community/nuxt-i18n#356]
### Version

[5.12.7](https://github.com/nuxt-i18n/releases/tag/5.12.7)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-8go7n](https://codesandbox.io/s/codesandbox-nuxt-8go7n)

### Steps to reproduce

On the home page, press the About button.

### What is expected ?

If the romanian language is selected, the button should redirect us to '/despre'.
If the english language is selected, the button should redirect us to 
'/en/about'

### What is actually happening?

The button, no matter what language is selected, redirects us to '/'

### Additional comments?

The problem comes from this line: https://github.com/nuxt-community/nuxt-i18n/blob/master/src/helpers/routes.js#L74

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c258">#c258</a>)</em></sub></div>

**Comment by mastix** [comment]
Looks like I have the same issue.

`:to="localePath('test/add')"
` creates link to "http://localhost:3000/".

If I use it directly (without i18n) the link is created correctly. (https://localhost:3000/test/add)

I can see that nuxt created the routes correctly in the router.js file.

`
      path: "/test/add",
      component: _63366ab3,
      name: "test-add___en___default",
`
...
`
      path: "/de/test/add",
      component: _63366ab3,
      name: "test-add___de"
`

**Expected:**

Have link created correctly based on the language.

Greetz,

Sascha

**Comment by rchl** [comment]
@mastix Your issue is not the same. When passing string to `localePath` it's supposed to be route name, not path. So `localePath('test-add')` in your case.

**Comment by mastix** [comment]
> @mastix Your issue is not the same. When passing string to `localePath` it's supposed to be route name, not path. So `localePath('test-add')` in your case.

Hi @rchl,

you're right! Thanks for the hint! 

Greetz,

Sascha
