### ISSUE TITLE
Reload of JSON language files

### ISSUE THREAD

**Issue by katafractari** [nuxt-community/nuxt-i18n#36]
I store translations in JSON files and configure nuxt-i18n like this:

```
    ['nuxt-i18n', {
      locales: [locale.language],
      vueI18n: {
        messages: {
          [locale.code]: require('./locales/' + locale.code + '.json')
        }
      },
      defaultLocale: locale.code
    }]
```
My use case is that I use **nuxt generate** to generate separate sites for all languages that are served from different domains, so I only specify one language per build.

The problem I'm facing is that changes to **./locales/<code>.json** are only visible in the app after I restart the dev server.

Having
```
    watch: [
      '~/locales'
    ],
```
in nuxt.config.js does cause the page to reload when I save locales files, but the changes are not visible.

Any thoughs on this? 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c28">#c28</a>)</em></sub></div>

**Comment by mohanklein** [comment]
I am having the same problem, my use case is that I don't want to restart dev server everytime I change my translatin file (e.g. en.json or en.js)

**Comment by katafractari** [comment]
I'm currently using **nodemon** for this purpouse. But still a full restart of the dev server is needed to reload the translations.

package.json
```
{
  "scripts": {
    "dev": "nodemon --watch locales --watch config --exec \"cross-env NODE_ENV=development LOCALE=en nuxt\""
  }
}
```

**Comment by nghiepit** [comment]
using [lazy-load-translations](https://nuxt-community.github.io/nuxt-i18n/lazy-load-translations.html) to reload the translations.

```js
 [ 'nuxt-i18n',
      {
        locales: [
          {
            code: 'en',
            name: 'English',
            file: 'en-US.js',
          },
        ],
        lazy: true,
        langDir: 'locales/',
      }
]
```

```js
// locales/en-US.js
export default require('./en.json')
```

**Comment by awakash** [comment]
Hi @nghiepit Could you share what your en.json looks like?
Thanks

**Comment by awakash** [comment]
Nevermind, en.json can look like
`
{
    "breaking": "BREAKING",
    "stop": "stop this from happening."
}
`
