### ISSUE TITLE
first time translating does not work using switchLocalePath()

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/nuxt-i18n#378]
### Version

[v6.0.0](https://github.com/nuxt-i18n/releases/tag/v6.0.0)

### Reproduction link

[https://github.com/miteyema/nuxt-i18n-demo](https://github.com/miteyema/nuxt-i18n-demo)

### Steps to reproduce

- go incognito
- open https://nuxt-i18n-demo.netlify.com
- click Nederlands to change language
- click français to change language
- click English to change language

### What is expected ?

- URL changes to /nl
- page is translated in Dutch
- URL changes to /fr
- page is translated in French
- URL changes to /
- page is translated in English

### What is actually happening?

- URL changes to /nl
- page is NOT translated in Dutch and stays in English
- URL changes to /fr
- page is translated in French
- URL changes to /
- page is translated in English

### Additional comments?

Please see the following GIF below to see the problem in action:
![problem.gif](https://cmty.s3.eu-west-1.amazonaws.com/110467581/87d2c520-aceb-11e9-9b7d-61cf2a83b3e5.gif)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c267">#c267</a>)</em></sub></div>

**Comment by rchl** [comment]
That seems to be due to not getting `set-cookie` header in first page response. I don't know netlify, is that something that you have to configure (allow)? It's either netlify blocking the cookie or preventing it from being sent somehow or code of this module doesn't go the right path for some reason...

**Comment by miteyema** [comment]
@rchl Thanks for the reply.

I have the same problem if I test my project locally.
Steps to reproduce:
- `npm run generate`
- `http-server ./dist/`
- go in incognito to http://127.0.0.1:8080 

The app behaves the same locally as on Netlify.
So I guess it's code of the module, do you have any idea with can be the problem?

**Comment by rchl** [comment]
That would explain it. Statically generated page can't respond with a cookie header. It will only work when running on a node server.

I don't have time to look into it more now, I guess it might be fixable in some way and if not, it should be documented better.

**Comment by miteyema** [comment]
@rchl Thanks for the reply, it gave me an idea for a quick fix in my case.
The following line seems to solve my problem for `npm run generate`
```
detectBrowserLanguage: false
```

Can you point me to the code regarding the cookie header, maybe I can have a look at the problem?

**Comment by rchl** [comment]
The very initial load of the page sets the cookie here https://github.com/nuxt-community/nuxt-i18n/blob/5aeab8bd7f4b05ce3b05558eedf1150f58c19514/src/templates/middleware.js#L117

But I think middlewares are only ran on generating pages so the code has no chance of triggering when loading static pages...

**Comment by MLDMoritz** [comment]
> ```
> detectBrowserLanguage: false
> ```

this fixed a big issue with memory leakage for me too.

**Comment by rchl** [comment]
This bug is caused by Nuxt not invoking middleware for initial request (see this comment for more info: https://github.com/nuxt/rfcs/issues/28#issuecomment-527939500). It can most likely be worked around by moving some part of the code to the `plugin`.

**Comment by miteyema** [comment]
@rchl Thanks again for having looked at the bug I was having!

**Comment by JuliaUsanova** [comment]
that kind of settings worked for me:
`detectBrowserLanguage: {
          // If enabled, a cookie is set once a user has been redirected to his
          // preferred language to prevent subsequent redirections
          // Set to false to redirect every time
          useCookie: true,
          // Cookie name
          cookieKey: 'i18n_redirected',
          // Set to always redirect to value stored in the cookie, not just once
          alwaysRedirect: false,
          // If no locale for the browsers locale is a match, use this one as a fallback
          fallbackLocale: 'en'
        },`

**Comment by supakornkim** [comment]
i am facing this issue, may i know how to fix this?
detectBrowserLanguage : false .... not work
set option for detectBrowserLanguage also not work.

Thanks

**Comment by danilsdf** [comment]
@supakornkim Also have this problem, if you have found the solution, please let me know. Thank you
