### ISSUE TITLE
How i can detect current language?

### ISSUE THREAD

**Issue by swearwalker** [nuxt-community/nuxt-i18n#380]
Hi, how can i detect current language. At previously, i  got it like that:

**Comment by rchl** [comment]
- `context.app.i18n.locale` where you have access to NuxtContext
 - `this.$i18n.locale` in component
 - `$i18n.locale` in template

**Comment by swearwalker** [comment]
@rchl but how can i get locale from asyncData:
async asyncData({ store }) {
    const currentProduct = await axios.get(process.env.BASE_API + store.state.i18n.locale + '/v1/products')
    return {
      products: currentProduct.data
    }
  }

**Comment by rchl** [comment]
`asynData` is passed the NuxtContext so my first suggestion applies here

**Comment by swearwalker** [comment]
@rchl Thanks, that works for me)

**Comment by qkveri** [comment]
If set to detectBrowserLanguage.alwaysRedirect I cannot get the current locale:
```
    @Component({
        async asyncData(ctx: Context): Promise<any> {
            console.log(ctx.app.i18n.locale); // prev locale
        },
    })
```

Only works if setTimeout is used:
```
    @Component({
        async asyncData(ctx: Context): Promise<any> {
            return new Promise(((resolve) => {
                setTimeout(() => {
                    console.log(ctx.app.i18n.locale); // current locale

                    resolve();
                }, 10);
            }));
        },
    })
```

How can I get the current locale without setTimeout?

**Comment by rchl** [comment]
Please create new issue and try to include reproduction steps and/or repo (can use https://codesandbox.io).

**Comment by arishojaei** [comment]
> * `context.app.i18n.locale` where you have access to NuxtContext
> * `this.$i18n.locale` in component
> * `$i18n.locale` in template

How can I access i18n in nuxt store?

**Comment by rchl** [comment]
`this.$i18n`

**Comment by MahbodHastam** [comment]
> > * `context.app.i18n.locale` where you have access to NuxtContext
> > * `this.$i18n.locale` in component
> > * `$i18n.locale` in template
> 
> How can I access i18n in nuxt store?

@arishojaei Did you found any solution?

**Comment by nx-josepcrespo** [comment]
> * `context.app.i18n.locale` where you have access to NuxtContext
> * `this.$i18n.locale` in component
> * `$i18n.locale` in template

This should be more clearly written into the documentation. Just a simple list like in the example above would be enough.

**Comment by zed-wong** [comment]
> > * `context.app.i18n.locale` where you have access to NuxtContext
> > * `this.$i18n.locale` in component
> > * `$i18n.locale` in template
> 
> This should be more clearly written into the documentation. Just a simple list like in the example above would be enough.

agree
