### ISSUE TITLE
Support multiple <template> sections with different locales?

### ISSUE THREAD

**Issue by kyrsquir** [nuxt-community/nuxt-i18n#386]
### What problem does this feature solve?

Is it possible to support multiple `<template>` blocks in a .vue file and automatically build routes based on that?

If this functionality is not wanted, please point me out to a proper way of translating pages which consist of large amounts of localised text mixed with markup.

### What does the proposed changes look like?

Support welcome.vue file looking like this:
```
<template lang="pug" locale="en">
  article 
    h3 Welcome!
    //  Lots of localised content with markup here
</template>

<template lang="pug" locale="de">
  article
    h3 Willkommen!
    // Lots of localised content with markup here
</template>
```
and automatically create routes `/en/welcome` and `/de/welcome` or similar based on settings.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c275">#c275</a>)</em></sub></div>

**Comment by rchl** [comment]
I think that would be quite hard to achieve as the functionality would probably need to be baked into vue-loader.

You can always just use `v-if="$i18n.locale === 'de'` to have separate blocks of code for different languages but that's of course not so clean.
