### ISSUE TITLE
Remove lodash from nuxt-i18n middleware

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#39]
nuxt-i18n version: 2.5.1

With the new language detection feature, lodash was added into the middleware and the front-end bundle. This has some heavy side effects concerning the bundle size:

![image](https://user-images.githubusercontent.com/640208/37246985-d2e3d8ea-24b3-11e8-91db-937311ecf22b.png)

You could also go for importing [`lodash.has`](https://www.npmjs.com/package/lodash.has) instead of the whole lodash module.

![image](https://user-images.githubusercontent.com/640208/37247171-a69e8088-24b7-11e8-92e8-9331db0275ca.png)

**Comment by paulgv** [comment]
Thanks @manniL ! I rewrote the check so it doesn't require `lodash.has`, probably was a bit overkill :P

**Comment by manniL** [comment]
Thank you :relaxed:
