### ISSUE TITLE
Document Vuex module feature in a dedicated page

### ISSUE THREAD

**Issue by paulgv** [nuxt-community/nuxt-i18n#406]
Documentation about nuxt-i18n's module is very hard to find currently, let's add a dedicated page to document what it does and how to enable it.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c286">#c286</a>)</em></sub></div>

**Comment by rchl** [comment]
I'm curious myself what's the use case for it because when using `v-t` directive or `$t` everywhere, it shouldn't be necessary to read strings from store.
