### ISSUE TITLE
differentDomains totally crashes browser

### ISSUE THREAD

**Issue by seltsam23** [nuxt-community/nuxt-i18n#411]
### Version

[6.0.2](https://github.com/nuxt-i18n/releases/tag/6.0.2)

### Reproduction link

[https://github.com/paulgv/nuxt-i18n-example](https://github.com/paulgv/nuxt-i18n-example)

### Steps to reproduce

1.) Clone example Repo
2.) Update nuxt-i18n & nuxt to newest version
3.) Change config/index.js as shown below
4.) Make hosts-file entries for domains
5.) Make sure you don't have  the i18n_redirected cookie set in your browser / clear cookies 

``` /etc/hosts
127.0.0.1 en.nuxt.breaks
127.0.0.1 fr.nuxt.breaks
127.0.0.1 es.nuxt.breaks
```

``` /config/index.js
const I18N = {
  differentDomains:true,
  locales: [
    {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      domain: 'en.nuxt.breaks:3000'
    },
    {
      code: 'fr',
      iso: 'fr-FR',
      name: 'Français',
      domain: 'fr.nuxt.breaks:3000'
    },
    {
      code: 'es',
      iso: 'es-ES',
      name: 'Español',
      domain: 'es.nuxt.breaks:3000'
    }
  ],
  defaultLocale: 'en',
  parsePages: false,
  pages: {
    'about': {
      fr: '/a-propos',
      en: '/about-us'
    },
    'posts': {
      fr: '/articles'
    },
    'post/_id': {
      fr: '/article/:id?',
      es: '/articulo/:id?'
    },
    'dynamicNested/_category': {
      fr: 'imbrication-dynamique/:category'
    }
  },
  vueI18n: {
    fallbackLocale: 'en',
    messages: { en, fr, es }
  }
}
```

### What is expected ?

Navigation works as expected, i18n_redirected cookie is set.

### What is actually happening?

Browser is freezing as soon as you try to navigate the page via the nav-menu.  i18n_redirected cookie is not set. 

### Additional comments?

If you set the cookie  i18n_redirected  manually it works as expected, but until then the browser just crashes.
It feels like there is some redirect-looping going on in the background. No Errors are thrown anywhere.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c288">#c288</a>)</em></sub></div>

**Comment by rchl** [comment]
`detectBrowserLanguage: false` fixes it as far as I can see. It makes sense as detection should be purely domain based in that case and there is no need for a cookie either.

This module should probably force `detectBrowserLanguage: false` if `differentDomains === true`...

**Comment by rchl** [comment]
This should now be fixed (regardless if `detectBrowserLanguage` is enabled or not) as of version 6.1.2.
