### ISSUE TITLE
How to handle localised dynamic route segments (slugs)

### ISSUE THREAD

**Issue by matsrietdijk** [nuxt-community/nuxt-i18n#42]
How should localised dynamic route segments be handled or what is recommended?

We fetch articles from an external api and receive articles with available translations (including localised slugs for each available translation). I would like not to use Vuex to "fix" the slug in the global language switch which we use in the default layout.

**Comment by paulgv** [comment]
Hi @matsrietdijk !
Do you mean to translate routes that contain dynamic fragments? If that's what you want to do, have a look at the "Customize route" section in the doc, there's an example with a `slug` parameter: https://nuxt-community.github.io/nuxt-i18n/routing/customize-routes.html

**Comment by matsrietdijk** [comment]
Hey @paulgv, I'm actually trying to translate the ":slug" part.

**Comment by paulgv** [comment]
Oh ok, in that case I think you should handle this API-side, it would be more flexible.
I guess you could also store all your slugs in your translation files and translate slugs in the default language before calling your API but that doesn't seem as convenient:

```es6
export default {
  async asyncData ({ params }) {
    const slug = this.$t(params.slug, this.$i18n.defaultLocale)
    let { data } = await axios.get(`https://my-api/posts/${slug}`)
    return { title: data.title }
  }
}
```

**Comment by matsrietdijk** [comment]
@paulgv I can't really fix this API side as the slugs are only unique in combination with the locale. So I guess the only realistic way is using the Vuex store with some custom language switcher logic. Thanks any ways!

**Comment by kamarkiewicz** [comment]
I've just implemented this kind of feature in my project, in a way described by @matsrietdijk 
Now one can have some reference [here](https://github.com/kamarkiewicz/Strona_KSI/commit/e7963f70e629371926dc39144135af28c8bdc52a) and [example of how to connect that with dynamic routes](https://github.com/kamarkiewicz/Strona_KSI/commit/dbdcb6edeaa7ec8501b73349a220c73e103f9d58).
