### ISSUE TITLE
Change the locale Vuetify with nuxt-i18n

### ISSUE THREAD

**Issue by berenicestr** [nuxt-community/nuxt-i18n#440]
Hi, 

I have a problem. I am using the  new Nuxt-vuetify module https://github.com/nuxt-community/vuetify-module
And I have Nuxt-i18n to internationalization.

But now there is some Vuetify components that I have to configure the internationalisation too. https://vuetifyjs.com/en/customization/internationalization

I don't know how can I sincronize. I have 

this in my Nuxt.config.js 

  modules: [
    "@nuxtjs/vuetify",
    ['nuxt-i18n', I18N]
]
...
import es from 'vuetify/es5/locale/es';
import en from 'vuetify/es5/locale/en'
const  I18N = require('./config')

  // Doc: https://github.com/nuxt-community/vuetify-module
  vuetify: {
    lang: {
      locales: { es , en },
      current: 'es',
    }
}

I don't know hot to sincronize when I change the locale in the Nuxt switcher with the Vuetify locale.

Thanks in advance for the help,
Regards

**Comment by rchl** [comment]
Seems like vuetify integrates with vue-i18n which this module uses. So if you just include your vuetify strings in your strings under the `$vuetify` key then it should just work - see https://vuetifyjs.com/en/customization/internationalization#vue-i-18-n

**Comment by Juanmabs22** [comment]
Your englush file should be like this:

```
import en from "vuetify/es5/locale/en";

export default {
    $vuetify: en,
    Hello: "Hello, it's me, Juanman",
};
```
