### ISSUE TITLE
"This page could not be found" with the default (empty) settings

### ISSUE THREAD

**Issue by tats-u** [nuxt-community/nuxt-i18n#444]
### Version

[v6.1.3](https://github.com/nuxt-i18n/releases/tag/v6.1.3)

### Reproduction link

[https://github.com/tats-u/nuxt-ts-vuetify-i18n-test](https://github.com/tats-u/nuxt-ts-vuetify-i18n-test)

### Steps to reproduce

```bash
git clone https://github.com/tats-u/nuxt-ts-vuetify-i18n-test.git -b i18n-empty-settings
yarn run dev
chrome http://localhost:3000/
# or firefox http://localhost:3000/
```

### What is expected ?

Page is successfully rendered
or maybe proper error message (e.g. "Prepare translations" or "Set default locales") shown

### What is actually happening?

This page could not be found (rendered by Nuxt)

### Additional comments?

- It works correctly without `nuxt-i18n`.
- Do you update the version selecting pull-down menu?  It stops at v5.3.0.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c299">#c299</a>)</em></sub></div>

**Comment by rchl** [comment]
Seems to be due to the fact that you haven't specified any locales.

It would probably make sense to just leave original routes if no locales are specified...

**Comment by tats-u** [comment]
> Seems to be due to the fact that you haven't specified any locales.

I believe so because because the page was successfully rendered after I set up nuxt-i18n properly.

>It would probably make sense to just leave original routes if no locales are specified...

It doesn't matter for me whether nuxt-i18n ignores absence of locales or encourages the developers to set up by raising an error.
