### ISSUE TITLE
is this typo ? STRATEGIES.NO_REFIX

### ISSUE THREAD

**Issue by hisayan** [nuxt-community/nuxt-i18n#457]
https://github.com/nuxt-community/nuxt-i18n/blob/0fae93785dd41972e5d4eed4f6f453ba45015702/src/plugins/routing.js#L44

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c303">#c303</a>)</em></sub></div>

**Comment by rchl** [comment]
Indeed. Thanks.
