### ISSUE TITLE
localePath utility function does not work with child pages

### ISSUE THREAD

**Issue by lifenautjoe** [nuxt-community/nuxt-i18n#469]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/s/example-i18n-xwgtf?fontsize=14](https://codesandbox.io/s/example-i18n-xwgtf?fontsize=14)

### Steps to reproduce

Try to use localePath with a page and it's childrens.

```html
      <nuxt-link
        :to="localePath('auth/login')"
      >Non working nuxt-link with localePath and page children</nuxt-link>
```

Watch it not work.

Try the same without `localePath`, see it work.

### What is expected ?

localePath should be able to handle children pages

### What is actually happening?

localePath can't handle children pages

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c313">#c313</a>)</em></sub></div>

**Comment by rchl** [comment]
`localePath` takes route's `name` not `path`. So in your case use `auth-login`. Alternatively, you can pass path like so `localePath({ path: 'auth/login' })` but that is less reliable.

You can find out route names by looking at generated `.nuxt/router.js` after building.

**Comment by reubenlimos** [comment]
You can try

`<nuxt-link
    :to="localePath('auth-login')"
 >
Non working nuxt-link with localePath and page children
</nuxt-link>`

Just replace "/" to "-" to every child.
Example
localePath('parent-child-child')
