### ISSUE TITLE
Locale keep switching to default locale when visit non ignore route

### ISSUE THREAD

**Issue by Azeranex** [nuxt-community/nuxt-i18n#47]
How can I prevent locale switch to default when visit ignore route?

Example, my default locale is `th` my current page is `/en/view-blablabla`. I go some page that in ignore `/settings`. I would like it to stay in `en` but it just switching to `th`.

Every localized route now is also switched to `th` too.

**Comment by paulgv** [comment]
Hi @Azeranex !
Thanks for reporting this, I made a small change to nuxt-i18n's middleware to prevent it from switching the locale when navigating to an ignored route, this should fix your issue.
