### ISSUE TITLE
To get localeName instead of localePath ...

### ISSUE THREAD

**Issue by jskorlol** [nuxt-community/nuxt-i18n#476]
### What problem does this feature solve?

If you use ... Sometimes you need to pass params. Although it is not visible in the url, there are times when you have to pass data ...
In this case, name can be used to pass params. I would like to have localeName.

### What does the proposed changes look like?

We need a function that allows us to get the name, not the path of the router. localeName

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c317">#c317</a>)</em></sub></div>

**Comment by rchl** [comment]
I don't understand your request. Can you give an example code? What do you think `localeName` should be set to?

**Comment by jskorlol** [comment]
I want to send params with route push. (Data transfer)

this. $ router.push ({name: 'account-register-sign-up-sent-email ___ en', params: {id: 1234, token: 'test'}, query: {id: 1234, token: 'test' }});

If you send by, you can receive params and queries.

this. $ router.push ({path: this.localePath ('account-register-sign-up-sent-email'), params: {id: 1234, token: 'test'}, query: {id: 1234, token: 'test'}});

If you send to, you will not receive params.

When you go to the page, you have to use it when you want to send specific params.

Otherwise, I have to use vuex .. because it is a one-time .. I don't want to do that.

If so, I would like to have a Name, not a Path.

**Comment by rchl** [comment]
I believe you can do this since `localePath` accepts same parameters as `push`:
```
this.$router.push(localPath(this.localePath({
  name: 'account-register-sign-up-sent-email',
  params: {id: 1234, token: 'test'},
  query: {id: 1234, token: 'test'},
}));

**Comment by jskorlol** [comment]
That way ... I can't get params.

**Comment by rchl** [comment]
It depends on how you've defined the `user` route. Please create a repro in codesandbox. I've created one that shows it working for a dynamic route: https://codesandbox.io/embed/i18n-plugin-txymu

**Comment by jskorlol** [comment]
[https://codesandbox.io/s/i18n-plugin-nijp9](https://codesandbox.io/s/i18n-plugin-nijp9)

Thank you for spending your precious time.
I want to do params check in middleware like this.

But I know this is the wrong way,
I want to send data when route push ...

**Comment by jskorlol** [comment]
And what do you think about this?

There is a link to the auth code that is sent after the subscription.
```
domain/auth/JDJ5JDEwJGtLQmxmSkprTy95VWRkd1gzQU55V08vS2RLU29kLnlEOWI3NzU1YjYwLzZaRDh6dmtOVVF1
```
However,
```
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      // alwaysRedirect: true,
      // fallbackLocale: 'en'
    },
```
In the state, when you follow that link, it is set to the default en.
The cookie is set to ko, but because the link is en ...

To solve this,
```
alwaysRedirect: true,
fallbackLocale: 'en'
```
But if you do this, you will run into a problem where switchLocalePath does not work.

How to apply alwaysRedirect to only a specific page so that only that page is changed via cookie values.

Now is
alwaysRedirect: false
Take locale from backend,
```
domain/auth/~~~
domian/**ko**/auth/~~~
```
You need to insert the language value into the link.
Of course, it's not that complicated, but maybe ...

**Comment by rchl** [comment]
Please don't mix unrelated issues/questions in one issue.

**Comment by rchl** [comment]
I guess you have a point that this is not possible easily now. I do wonder though, if passing params to route that doesn't technically accepts params is actually supported on purpose or it's undefined behavior. I can't find mention of it in VueRouter documentation.

**Comment by jskorlol** [comment]
Yes, that's right...
I also don't know if this is the right way or the wrong way ...

But it doesn't seem to be intended.
I guess, I need to find another way.
(use vuex or more ...)
Is it okay to write new topics for other topics above?

**Comment by rchl** [comment]
> Is it okay to write new topics for other topics above?

I'd suggest discussing on Discord (https://discordapp.com/channels/473401852243869706/ ) first and then creating feature request or issue, depending on the outcome.

**Comment by jskorlol** [comment]
Okay !
Thanks for the kind explanation.
