### ISSUE TITLE
[Feature Request] Generate Proper Language Attribute on Static Generated Nuxt

### ISSUE THREAD

**Issue by jefrydco** [nuxt-community/nuxt-i18n#48]
### Problem to Solve
Hi I tried to generate nuxt project using `nuxt generate` command, then I inspect the source code. I see that the lang attribute on html tag isn't generate according to its locale. For instance if my default language was Indonesia, then all of another language also generate in Indonesia.

### Proposed Solution
The language attribute generate according to its locale.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c30">#c30</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @jefrydco !
Could you share the config you are using with nuxt-i18n, as well as the module's version and a preview of your files structure?
I've done some tests locally with v2.7.1 and the lang attribute seems to be set properly for each language.

**Comment by jefrydco** [comment]
Hi @paulgv 

Thanks for replying, I tried it again using new project setup and its worked as expected. I don't know why that could be happen. On my other project it doesn't work.
