### ISSUE TITLE
switchLocalePath() doesn't work in plugins

### ISSUE THREAD

**Issue by LionelPaulus** [nuxt-community/nuxt-i18n#480]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/embed/nuxt-i18n-switchlocalepath-bug-dbi7h](https://codesandbox.io/embed/nuxt-i18n-switchlocalepath-bug-dbi7h)

### Steps to reproduce

Create a Nuxt plugin and try using `switchLocalePath()` in it.

### What is expected ?

Function working: returning the locale path for the desired locale.

### What is actually happening?

Function crashes with error:
> Cannot destructure property `params` of 'undefined' or 'null'.
> const { params, ...routeCopy } = this.$route

### Additional comments?

I'm using nuxt 2.10.0 and nuxt-i18n 6.3.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c318">#c318</a>)</em></sub></div>

**Comment by LionelPaulus** [comment]
Hey @rchl, any update on this? :)
If you have a workaround, it would be very helpful 🙏

**Comment by rchl** [comment]
No workarounds. It needs a proper fix that requires some refactoring. Seems like this was never supported so it's not a trivial bug fix
