### ISSUE TITLE
page infinitely loading in spa mode

### ISSUE THREAD

**Issue by divisey** [nuxt-community/nuxt-i18n#490]
### Version

[v6.3.0](https://github.com/nuxt-i18n/releases/tag/v6.3.0)

### Reproduction link

[https://github.com/divisey/nuxt-i18n-path-issue](https://github.com/divisey/nuxt-i18n-path-issue)

### Steps to reproduce

yarn 

yarn dev

then visit http://localhost:3000/#/es/ in browser

### What is expected ?

it should work well when url is either http://localhost:3000/#/es, http://localhost:3000/#/es/ or http://localhost:3000/#/es/?a=1

### What is actually happening?

it works when url is  http://localhost:3000/#/es, but page infinitely loading when you visit http://localhost:3000/#/es/, or when you have a 
query like http://localhost:3000/#/es?a=1

### Additional comments?

this issue does not appear in v6.0.0, maybe somewhere has a bug in the later version.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c322">#c322</a>)</em></sub></div>

**Comment by rchl** [comment]
Note: This bug triggers because now we are triggering all the language detection code on navigating in SPA mode while previously that was broken. So that fix uncovered this bug where due to an extra trailing slash we are not able to match the current page with an existing route.
