### ISSUE TITLE
iso code for locales config not used

### ISSUE THREAD

**Issue by TimonPeng** [nuxt-community/nuxt-i18n#499]
https://github.com/nuxt-community/nuxt-i18n/blob/3a64fdad274571f160046f08f861aa7c3c4d7a15/src/helpers/utils.js#L15

**Comment by TimonPeng** [comment]
https://github.com/nuxt-community/nuxt-i18n/issues/37#issuecomment-419415526

**Comment by TimonPeng** [comment]
https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/main.js#L243

Here check the browser language is in `localeCodes` array or not.

https://github.com/nuxt-community/nuxt-i18n/blob/3a64fdad274571f160046f08f861aa7c3c4d7a15/src/index.js#L43

`localeCodes` defined here.

https://github.com/nuxt-community/nuxt-i18n/blob/3a64fdad274571f160046f08f861aa7c3c4d7a15/src/helpers/utils.js#L15

But didn't use iso code.

**Comment by rchl** [comment]
Code looks fine to me. Please provide reproducion on https://codesandbox.io because I don't understand what problem do you see here.

**Comment by TimonPeng** [comment]
@rchl Review please. https://codesandbox.io/s/codesandbox-nuxt-rng17

When don't set a cookie, it always choose English not depending on the http header `accept-language`.

You can use the following command for environment replication.

```
curl 'https://rng17.sse.codesandbox.io/' -H 'accept-language: zh-CN,zh;q=0.9,ja;q=0.8' --compressed -L -v
```

You can see two 302 redirects happend.

- The first time is depend on `rootRedirect: "cn"`
- The second time is depend on `detectBrowserLanguage`? I think.

**Comment by rchl** [comment]
In a locale defined this way:
```
      {
        name: "简体中文",
        code: "cn",
        iso: "zh-CN",
        file: "cn.js"
      }
```
The `code` property is used to match the browser language. In your case, it doesn't match because nuxt-i18n matches it against `zh` from the `accept-language` header, not `cn`. So I think the issue here is with configuration - you should change `code` property to `zh`. Same for `rootRedirect`.

**Comment by rchl** [comment]
The `iso` code is only used for some SEO functionality, not for matching browser locale.

**Comment by TimonPeng** [comment]
@rchl Ok, thank you.

Would you mind adding an alias configuration for router path or domain name? 

Like apple.com:

- https://www.apple.com/jp/
- https://www.apple.com/hk/
- https://www.apple.com/tw/

For example:

```
{
  ...
  locales: [
    {
      code: 'ja',
      alias: 'jp',
      iso: 'ja-JP',
      file: 'ja-JP.js'
    },
    {
      code: 'zh-HK',
      alias: 'hk',
      iso: 'zh-HK',
      file: 'zh-HK.js'
    },
    {
      code: 'zh-TW',
      alias: 'tw',
      iso: 'zh-TW',
      file: 'zh-TW.js'
    },
  ],
  ...
}
```

**Comment by TimonPeng** [comment]
alias is country code.

**Comment by TimonPeng** [comment]
Like next-i18next's localeSubpaths.

https://github.com/isaachinman/next-i18next#5-locale-subpaths

**Comment by rchl** [comment]
It probably makes sense to have something like that but would have to figure out how to best implement it.

Browser language detection needs to be considered also - currently it only looks at first two characters of accept-language token.

**Comment by progvb** [comment]
I'm wondering what motivation was behind the decision to use only the first two characters?
