### ISSUE TITLE
[Feature Request] Use Folder Name Without Index in Custom Routes

### ISSUE THREAD

**Issue by jefrydco** [nuxt-community/nuxt-i18n#50]
### Problem to Solve
If I use folder-based routing, i have to write
```
   'register/index': {
      id: '/masuk',
      en: '/login'
    }
```

### Proposed Solution
Why not just write the name of folder without `index` as same as for file-based routing,
```
   'register': {
      id: '/masuk',
      en: '/login'
    }
```

**Comment by manniL** [comment]
I think this is already working with the right folder structure.

```
pages/
├── register.vue
├── register/
│   ├── index.vue
│   ├── foobar.vue
│   ├── bazfoo.vue
```

Use the `register.vue` component to always display the child:

```
<template>
  <nuxt-child/>
</template>
```

**Comment by jefrydco** [comment]
Thanks, it worked!
