### ISSUE TITLE
It seems that nuxt-link can only monitor one level of directory

### ISSUE THREAD

**Issue by baymax2** [nuxt-community/nuxt-i18n#514]
### Version

[6.3.0](https://github.com/nuxt-i18n/releases/tag/6.3.0)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-r3cpv](https://codesandbox.io/s/codesandbox-nuxt-r3cpv)

### Steps to reproduce

- `localePath('demo')`can work well
- `localePath('demo/test')` will get an error `[vue-router] Route with name 'demo/test___en' does not exist`

### What is expected ?

it can work well

### What is actually happening?

get an error `[vue-router] Route with name 'demo/test___en' does not exist

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c336">#c336</a>)</em></sub></div>

**Comment by rchl** [comment]
The argument you pass to `localePath` needs to match internal route name which you can look up in a generated `.nuxt/router.js` file. I think that one will be called `demo-test`

**Comment by baymax2** [comment]
非常感谢 我在`.nuxt/router.js`中发现:
```js
// .nuxt/router.js
routes: [{
    path: '/demo/test',
    component: _4ee3360c,
    name: 'demo-test'
},
{
    path: '/demo/test',
    component: _4ee3360c,
    name: 'demo-test__fr'
},
{
    path: '/demo/test',
    component: _4ee3360c,
    name: 'demo-test__es'
}]
```
It works fine, when I change `localePath('demo/test')` in `index.vue` to `localePath('demo-test')`,

**Comment by mixn** [comment]
I just spent 2h debugging this and think this should still be an open bug. 🤔😌 

Documentation says to use it as [follows](https://nuxt-community.github.io/nuxt-i18n/basic-usage.html#nuxt-link), but that doesn’t work.

My particular (very simplified) example:

`nuxt.config.js`
```
import pages from './lang/config/pages.js';

module.exports = {
  modules: [
    [
      'nuxt-i18n',
      {
        parsePages: false,
        pages
      }
    ],
  ]
}
```

`lang/config/pages.js`
```
export default {
  'projects/golden-hill-academy/index': {
    en: '/projects/golden-hill-academy',
    de: '/projekte/golden-hill-academy'
  },
  'projects/index': {
    en: '/projects',
    de: '/projekte'
  }
};

`index.vue`
```

<n-link :to="localePath('projects')">
  Golden Hill Academy
</n-link>


<n-link :to="localePath('projects/golden-hill-academy')">
  Golden Hill Academy
</n-link>


<n-link :to="localePath('projects-golden-hill-academy')">
  Golden Hill Academy
</n-link>
```

Note I had to use `projects-golden-hill-academy` for it to work, instead of `projects/golden-hill-academy`, how it’s actually defined in `lang/config/pages.js`.

Hoping to get some feedback on this and sorry if I’m misunderstanding something here.

**Comment by rchl** [comment]
Yes, by path won't work as paths are different for different languages and the path has to match the route path **exactly**.

There is #641 for making that work but until then you have to use route's name, not path.

**Comment by mixn** [comment]
@rchl Thank you for the quick response, I appreciate it. :)

Maybe it’d help to point this out a bit more in the usage section? It can get lost in the many examples, out of which, technically, only one works?
