### ISSUE TITLE
Allow "sameSite" for detectBrowserLanguage cookie configuration

### ISSUE THREAD

**Issue by Borisstoy** [nuxt-community/nuxt-i18n#516]
### What problem does this feature solve?

As per Chrome requirement:

A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute.

In order to be able to use cookies for browsers language detection, we need the "sameSite" option while setting the "i18n_redirected" cookie.

### What does the proposed changes look like?

Add an extra option "sameSite", boolean value.
  
detectBrowserLanguage: {
    ...
    sameSite: true
    ...
  },

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c337">#c337</a>)</em></sub></div>

**Comment by rchl** [comment]
@Borisstoy
I think it would make sense to create cookie with `SameSite=Lax` attribute by default. I don't really see why would we need an option for it.

**Comment by Borisstoy** [comment]
@rchl , indeed.

**Comment by e-lobo** [comment]
this issue still persists
