### ISSUE TITLE
SEO: missing region-independant link for language

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/nuxt-i18n#522]
### What problem does this feature solve?

When enabling the `seo` option, the plugin correctly generates `<link rel="alternate" hreflang="x">` tags for every language configured in `nuxt.config.js`.
However, it is also recommended to generate a catchall URL for geographically unspecified users of that language.
For example, you may have specific URLs for English speakers in Ireland (en-ie), Canada (en-ca), and Australia (en-au), but should also provide a generic English (en) page for searchers in, say, the US, UK, and all other English-speaking locations. It can be one of the specific pages, if you choose.

Please see https://support.google.com/webmasters/answer/189077 for more information.

### What does the proposed changes look like?

We already have the properties `code` (e.g. en)  and `iso` (e.g. en-AU) in the `locales` object when configuring the module in `nuxt.config.js`.
We could use the `code` property to generate the catchall URL tag.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c340">#c340</a>)</em></sub></div>

**Comment by rchl** [comment]
We can't use the `code` property alone as we wouldn't know which of the country-specific locale (for example, whether en-US or en-GB) should be used as the catchall locale. We would need to use another property of the locale object like `isCatchallLocale: true` or similar to indicate which locale should act like one.

With `isCatchallLocale: true`, we could then just automatically derive locale to use from the iso code (so only **en** from **en**-GB). That would be better than using `code` IMO as `code` doesn't have any special meaning and could be anything really.

**Comment by miteyema** [comment]
@rchl Thanks for that very elaborate reply. Indeed, solely relying on `code` would not cut it for everyone.

**Comment by manniL** [comment]
Maybe we could even do it "per language"? (`{ code: 'gb', iso: 'en-GB', isRegionIndependent: true ... },`)
