### ISSUE TITLE
custom middleware cause conflicts with other module

### ISSUE THREAD

**Issue by mercs600** [nuxt-community/nuxt-i18n#531]
### What problem does this feature solve?

Hi guys, 
this line https://github.com/nuxt-community/nuxt-i18n/blob/56ae21a27bab9bc03dffbe7015cd85a843ce2d88/src/index.js#L133  adds custom middleware with key `i18n`

Our module does exactly the same thing, so we have conflict here. Obviously we should change the key name on our side, but I think this module should do the same, because this is tricky to debug. 

What do you think ? I can prepare some PR to fix that. 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c344">#c344</a>)</em></sub></div>

**Comment by rchl** [comment]
I believe the name of middleware shouldn't have any functional meaning so I don't mind changing it (to `nuxti18n` for example). Otherwise, it would have to be a breaking change and that wouldn't be so nice.
