### ISSUE TITLE
vue router warning

### ISSUE THREAD

**Issue by javialon26** [nuxt-community/nuxt-i18n#55]
In all routes with more than one level i have this warning:

```[vue-router] Route with name 'usuario-editar-perfil-es-es' does not exist```

Examples:

Route: http://localhost:3000/usuario/editar-perfil
[vue-router] Route with name 'usuario-editar-perfil-es-es' does not exist

Route: http://localhost:3000/usuario/mis-anuncios
[vue-router] Route with name 'usuario-mis-anuncios-es-es' does not exist

But in routes with only one level it is okay, for example:

http://localhost:3000/ayuda
http://localhost:3000/quienes-somos

My Nuxt version is 1.4.0 and nuxt-i18n version is 2.9.1.
Configurations:
```
  defaultLocale: 'es',
  locales: [
    {
      code: 'es',
      iso: 'es-ES',
      name: 'Español',
      langFile: 'es-ES.js'
    },
    {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      langFile: 'en-US.js'
    }
  ],
  loadLanguagesAsync: true,
  langDir: 'locales/'
```

**Comment by javialon26** [comment]
@paulgv

**Comment by paulgv** [comment]
Duplicate of https://github.com/nuxt-community/nuxt-i18n/issues/57
