### ISSUE TITLE
Is there a way to set cookie's domain

### ISSUE THREAD

**Issue by bayun2** [nuxt-community/nuxt-i18n#555]
### What problem does this feature solve?

For example, my site is a.xxx.com,  i want to set cookie in root domain(xxx.com) for other site like b.xxx.com can get the same cookie 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c360">#c360</a>)</em></sub></div>

**Comment by thnima** [comment]
@rchl Is there any update on this?
We actually have the same situation: The app is hosted on a different subdomain than the website. To share the cookie we would need to set the cookie domain to the root domain.
As this is very important: Is there any workaround to achieve this behaviour right now?

Thank you for your efforts on this repo!

Best,
Thomas

**Comment by rchl** [comment]
It would be easy to add that functionality.
Unfortunately, I'm quite busy right now, but maybe I'll find some time this week but anyone is welcome to contribute.

**Comment by thnima** [comment]
Setting a `cookieDomain` property looks pretty easy indeed. I will have a look at it.

**Comment by rchl** [comment]
This was implemented by looked PR
