### ISSUE TITLE
this.$i18n.locales undefined when specifying i18n options through component option

### ISSUE THREAD

**Issue by coin-au-carre** [nuxt-community/nuxt-i18n#557]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html](https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html)

### Steps to reproduce

Follow the steps on the first section of [Lang Switcher](https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html#lang-switcher)

### What is expected ?

this.$i18n.locales should contain an array of 3 objects which are defined in nuxt.js.config. 

### What is actually happening?

`this.$i18n.locales` is undefined 

```
TypeError
Cannot read property 'filter' of undefined
```

### Additional comments?

this.$i18n.availableLocales returns an array `['en','es','fr]`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c365">#c365</a>)</em></sub></div>

**Comment by rchl** [comment]
It works in my test sandbox: https://codesandbox.io/s/i18n-plugin-i18nlocales-f82pn

(Just remember that you have to navigate the `/en` path, for example, as there is no index page generated for default `prefix` strategy.)

**Comment by coin-au-carre** [comment]
Ok thank you this is weird if I do this in your code :

```
 availableLocales() {
      console.log(this.$i18n)
      return this.$i18n.locales.filter(i => i.code !== this.$i18n.locale);
    }
```

I can indeed see that `this.$i18n.locales` is well defined. Something is preventing that on my side...

**Comment by coin-au-carre** [comment]
Ok I think I got the problems. Putting a pages/test.vue files works. However if I put this code in layouts/default.vue, it does not work. My vue knowledge is newbish I guess I try to do things I am not supposed to do in layouts/ ?

**Comment by rchl** [comment]
If you can reproduce this problem in codesandbox then I can have a look.

**Comment by Holi0317** [comment]
Codesandbox sample: https://codesandbox.io/s/i18n-plugin-i18nlocales-it7n5

The `$i18n` property of current component will get override without `nuxt-i18n` augmentation if there is an `<i18n>` tag exist in the SFC with `vueI18nLoader` enabled in `nuxt.config.js`

In my test, the format of i18n does not affect this bug. Whether it's yaml or with `locale` defined will trigger this bug

One workaround (hack) would be attach a `ref` to a random child component and use it's `$i18n` property. Provided the child component does not have an `<i18n>` tag

**Comment by rchl** [comment]
Did some preliminary investigation and found out that this is the code responsible for this behavior:
https://github.com/kazupon/vue-i18n/blob/f42e81f65a88eeeccc311b970d2d4fd4181712ed/src/mixin.js#L33-L42

When there is custom `i18n` block in a component then `options.__i18n` is set to plain JSON object and a local `$i18n` property is created that has original `vue-i18n` properties copied into it but obviously that doesn't include properties added by `nuxt-i18n`.
