### ISSUE TITLE
404 error when reloading on non-default lang

### ISSUE THREAD

**Issue by 34r7h** [nuxt-community/nuxt-i18n#558]
Please point me to the right docs or workaround, spent hours already so would love any help. 

When loading to an ru route, i get 404. Upon navigating to another link, the routing responds appropriately. Here's my options on nuxt config:

`['nuxt-i18n', {
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected',
        alwaysRedirect: true
      },
      parsePages: false,
      vueI18nLoader: true,
      strategy: 'prefix_except_default',
      pages: {
        about: {
          en: "/about",
          ru: "/около"
        },
        contact: {
          en: "/contact",
          ru: "/контакт"
        },
        'listings/tours/index': {
          en: "/listings/tours",
          ru: "/объявления/туры"
        },
        'listings/excursions/index': {
          en: "/listings/excursions",
          ru: "/объявления/экскурсии"
        },
        'offer/tours/_id/index': {
          en: "/offer/tours/:id",
          ru: "/объявления/туры/:id"
        },
        'offer/excursions/_id/index': {
          en: "/listings/excursions/:id",
          ru: "/объявления/экскурсии/:id"
        },
        partners: {
          en: '/partners',
          ru: '/партнеры'
        },
        transfers: {
          en: '/transfers',
          ru: '/трансфер'
        }
      },
      seo: true,
      locales: [{
        code: 'en',
        iso: 'en-GB'
      },
      {
        code: 'ru',
        iso: 'ru-RU'
      }],
      defaultLocale: 'en'
    }]`

**Comment by rchl** [comment]
I can try to help if you'll create minimal reproduction on codesanbox (for example).

**Comment by 34r7h** [comment]
@rchl I appreciate the offer. Problem was loading Cyrillic characters into URL isn't allowed. The vue router permits it after the app loads, however. I've changed to latin characters and problem solved. Newb error :/
