### ISSUE TITLE
Switch off prefixes for all locales in the client

### ISSUE THREAD

**Issue by adetbekov** [nuxt-community/nuxt-i18n#56]
It would be nice to add toggle of removal locale codes in URLs exactly for the client. And automatically redirects to "clean" version of url in the client only. 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c45">#c45</a>)</em></sub></div>

**Comment by DreaMinder** [comment]
Agree. For example if you use i18n for web-app, it would be nice to remove locale prefixes from URLs.

**Comment by lrosa007** [comment]
this might be useful. https://nuxt-community.github.io/nuxt-i18n/routing.html#module-s-configuration-2

<img width="771" alt="screen shot 2018-08-11 at 20 30 44" src="https://user-images.githubusercontent.com/12070598/43997315-807a71ca-9da5-11e8-90b6-a3a0d1e7c149.png">

**Comment by HapLifeMan** [comment]
Any plan to add this feature @paulgv? It could be very useful 🙂

Maybe a `prefix: false, // or null` or `pages: false,` would do the job!

**Comment by imShara** [comment]
Yep, if you make app with interface localization only, there is no need to prefix language in routes.

**Comment by adetbekov** [comment]
@imShara I think it is necessary for Server Side Rendering part. Otherwise search engine bots will not be able to index multi-language sites. May be it should be neglected dynamically on the client side. Add some triggers, you know, some state, that remember current language(preferred locale).

**Comment by imShara** [comment]
@adetbekov E.g app is forum. Interface is multilangual, content - mixed. What should be in url? What should happens with locale when you send link to thread?
