### ISSUE TITLE
Problem in axios

### ISSUE THREAD

**Issue by prochorz** [nuxt-community/nuxt-i18n#562]
From v 6.3.1
with this code
```
const accessor: Plugin = (context: any) => {
    const i18n: any = context.app.i18n;
    context.app.$axios.onRequest((config: any) => {
        if (config.method === 'get' && i18n) {
            const lang = `${i18n.__route.name}`.replace(/^[^_]*___/g, '');
            ...
        }
    });
};
```
application return error
```
 ERROR  Cannot read property 'name' of undefined                                                                                                                    

  at $axios.onRequest.config (server.js:11251:36)
  at interceptors.request.use.config (server.js:396:45)

```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c369">#c369</a>)</em></sub></div>

**Comment by rchl** [comment]
`__route` was an internal property and was not supposed to be used by anyone. It was no longer needed in so was removed.

But since you have access to `context`, you can get the `route` object from it.

**Comment by prochorz** [comment]
`i18n.locale` don't work perfectly. After change route, it still has old slug. And in SSR I see, it's - `undefined`

**Comment by rchl** [comment]
I suppose it depends on the order of when nuxt-i18n versus your plugin runs.
`context.route` should be up to date tho (just make sure you don't store the reference to `route` and instead get it each time from `context` to see the most up-to-date object).
