### ISSUE TITLE
How to use vuex for storage select lang ?

### ISSUE THREAD

**Issue by golubvladimir** [nuxt-community/nuxt-i18n#565]
I want use only vuex for storage select lang.
How to setting get lang from vuex ?
How to disable generation routes ?

**Comment by golubvladimir** [comment]
I config i18n. 

```
  i18n: {
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en'
    },
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en-US.js'
      },
      {
        code: 'ru',
        name: 'Russian',
        file: 'ru-RU.js'
      }
    ],
    differentDomains: false,
    forwardedHost: false,
    lazy: true,
    langDir: 'lang/',
    parsePages: false,
  },
```

**Comment by golubvladimir** [comment]
I created store for lang.

```
const store = () => ({
  lang: 'en'
});

const mutations = {
  setLang: (state, lang) => {
    state.lang = lang
  }
};

const getters = {
  getLang: state => state.lang
};

```
and settings vuex-persistdate for save in cookie

    filter: (mutation) => {
      const conditionFilter =
        mutation.type === 'auth/setLang'
      ;
      return conditionFilter;
    },
    reducer: (state) => {
      return {
        lang: {
          lang: state.lang
        }
      }
    },

**Comment by golubvladimir** [comment]
For examle, I have one page with select lang.

// http://localhost:3001/changelang
```
<template>
  <div class="locale-changer">
    <select v-model="$i18n.locale">
      <option v-for="(lang, i) in langs" :key="`Lang${i}`" :value="lang">{{ lang }}</option>
    </select>
    <p>{{ $t('login.login_msg') }}</p>
  </div>
</template>

<script>
    export default {
        name: "changelang",
        data: () => ({
          langs: ['ru', 'en']
        }),
        mounted() {
            console.log(typeof this.$i18n.locale);
        }
    }
</script>

```

When I change my language by select, nothing happens.

I follow the link http://localhost:3001/ru/changelang, lang change. How to fix it ?

**Comment by golubvladimir** [comment]
I found the setting strategy: 'no_prefix', but after change lang by select. I have an error in console 
`vue-i18n.esm.js?a925:33 [vue-i18n] Cannot translate the value of keypath 'login.login_msg'. Use the value of keypath as default.`

**Comment by golubvladimir** [comment]
Function for change locale ```this.$i18n.setLocale(this.selectLang);```

**Comment by golubvladimir** [comment]
Example plugin
```
export default async function ({app, store}) {
  // on change locale
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    store.commit('lang/setLocale', newLocale, {root: true});
  };

  // set default locale from store (Cookie)
  if (store.getters['lang/locale']) {
    await app.i18n.setLocale(store.getters['lang/locale']);
  }
}
```

**Comment by fabiofdsantos** [comment]
@golubvladimir thanks for sharing!

I created something similar for `vuex-persistedstate`.

**Comment by rchl** [comment]
If `vuex` option is not disabled then the module already syncs locale to store as `i18n/locale`. So I'm not sure why all that would be needed.

**Comment by fabiofdsantos** [comment]
It was not working properly in SPA-mode and Vuex-persistedstate, so I have decided to create a custom plugin as I also wanted some extra features.
I will check later and I will open an issue if there's any bug related with i18n-module.
