### ISSUE TITLE
Cannot get translations when there is some special characters in locale's code name

### ISSUE THREAD

**Issue by dzcpy** [nuxt-community/nuxt-i18n#567]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://codesandbox.io/s/relaxed-ishizaka-tlpim](https://codesandbox.io/s/relaxed-ishizaka-tlpim) (it's not working for some other errors)

### Steps to reproduce

1. Set a `langDir` and `lazyload: true` and properly translate all message
2. Make sure there is a language which has a '-' in its code, for example `zh-CN` (which is required, since `zh-CN` and `zh-TW` are quite different)
```json5
{
  locales: [
    {  // works
      code: 'en',
      file: 'en.js'
    },
    { // does not work
      code: 'zh-CN',
      file: 'zh-CN.js'
    },
    { // works too
      code: 'zh_CN',
      file: 'zh-CN.js'
    }
  ]
}
```

### What is expected ?

Strings to be successfully translated

### What is actually happening?

Not working

### Additional comments?

However, if put a `_` instead of `-` in locale name, then it works.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c373">#c373</a>)</em></sub></div>

**Comment by rchl** [comment]
I've created a minimal test case at https://codesandbox.io/s/nuxt-i18n-lazy-load-eplid that appears to work just fine. Feel free to re-open if you can create a reproducible test case. You can fork my codesandbox and experiment.
