### ISSUE TITLE
get access to nuxt-i18n State from plain js

### ISSUE THREAD

**Issue by ctmqwe** [nuxt-community/nuxt-i18n#573]
Hi, I try to get access to nuxt-i18n State from plain js file:

from Vue components it looks like:
this.$i18n.locale // state data

1) from plain js I can't access to namespaced nuxt-i18n data
2) Importing vuex only have access to mapState, mapGetters functions. How to get access to namespaced nuxt-i18n state?

**Comment by rchl** [comment]
You need access to store. You can create nuxt plugin (https://nuxtjs.org/guide/plugins) where you have access and maybe pass store to your plain JS from it.

**Comment by EnzoBatista** [comment]
@rchl How can i do that, when i'm include nuxt-i18n as a module in nuxt.config?

**Comment by rchl** [comment]
I'm not sure what you want to do. Please describe your problem better.

**Comment by EnzoBatista** [comment]
@rchl 

I put nuxt-i18n as a module inside the nuxt.config of my project,  wich means that it can be globally accessible (right?).
I know maybe have no much sense but I NEED to do that. 

**Wanna do something like this:**

~~~
const createStore = () => {
    return new Vuex.Store({
      state: {
        services: [
          {
            id: 2,
            imageLink: '/img/services/desarrollo_web_sitios',
            title:  $t('Langkey'),
          }
       ]
    }
  })
}`

**Comment by rchl** [comment]
You probably can't do it this way.
You would need to commit that string later, for example from [nuxtServerInit](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) or a nuxt plugin.
