### ISSUE TITLE
Dont't load all availableLocales, when selected default language ?

### ISSUE THREAD

**Issue by golubvladimir** [nuxt-community/nuxt-i18n#575]
### Version

[v6.5.0](https://github.com/nuxt-i18n/releases/tag/v6.5.0)

### Reproduction link

[https://codesandbox.io/s/awesome-wozniak-ickli](https://codesandbox.io/s/awesome-wozniak-ickli)

### Steps to reproduce

When I selected en and reload page. I have in availableLocales only one language: ['en']
When I selected ru and reload page. I have in availableLocales two languages: ['en', 'ru']

### What is expected ?

```
['en', 'ru']
```

### What is actually happening?

```
ru - ['en', 'ru']
en - ['en']
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c382">#c382</a>)</em></sub></div>

**Comment by rchl** [comment]
`availableLocales` is exposed by `vue-i18n` and not this module and it only includes locales that are loaded. Since you are probably using lazy loading, only currently used and fallback locale are loaded.

You should create your own implementation of `availableLocales`. There are examples of that in docs.

**Comment by golubvladimir** [comment]
@rchl 
Create two function: 
1) formation array for nuxt config by readdir with json
2) formation array for client

```
function getLocalesObject() {
  const localesObj = [];

  const items = fs.readdirSync(path.join(__dirname, '..', '/lang/json'));

  items.map(item => {
    localesObj.push({
      code: item.slice(0, item.indexOf('.')),
      file: `json/${item.slice(0, item.indexOf('.'))}`
    })
  });

  return localesObj;
}

function getLocales() {
  const locales = [];

  const items = fs.readdirSync(path.join(__dirname, '..', '/lang/json'));

  items.map(item => {
    let locale = item.slice(0, item.indexOf('.'));

    locales.push({
      value: locale,
      title: locale
    })
  });

  return locales;
}
```

**Comment by rchl** [comment]
I don't see why would you do all this.

You have the `i18n.locales` object which matches what you have defined in nuxt.config.js. You can get locale codes from there.
