### ISSUE TITLE
Translating vue-meta and prefix_except_default strategy

### ISSUE THREAD

**Issue by gorbypark** [nuxt-community/nuxt-i18n#582]
### Version

[v6.5.0](https://github.com/nuxt-i18n/releases/tag/v6.5.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

I'm using nuxt with vue-meta, nuxt-i18n with the i18n compiler and `strategy: 'prefix_except_default',` in nuxt.config.js.  When going to `url.com/es/abouto` both $t('hello') and $t('title') are translated correctly.  When going to the default route, `url.com/about` only $t('hello') is translated, but $t('title') is not.
```
<template>
  <div>>
    {{ $t('hello') }}
  </div>
</template>

<i18n>
{
  "en": {
    "title:": "hello title",
    "hello": "hello world!"
  },
  "es": {
    "title": "Hola tital!",
    "hello": "Hola mondial!"
  }
}
</i18n>

<script>
export default {
  head() {
    return {
      title: this.$t('title'),
      meta: [
        {
          hid: 'description',
          name: 'description',
          content: 'My custom description'
        }
      ]
    }
  },
  nuxtI18n: {
    paths: {
      en: '/about',
      es: '/abouto'
    }
  }
}
</script>
```

### What is expected ?

Both $t('hello') and $('title') should be translated in the default route.

### What is actually happening?

Only $t.('hello') is translated, while the title ends up as "title" (or whatever the key happens to be set to).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c385">#c385</a>)</em></sub></div>

**Comment by rchl** [comment]
It's because you have extra colon in your English key -- `"title:"`. Should be `"title"` of course.

**Comment by gorbypark** [comment]
I don't know how I missed that 😮 !  Thanks.
