### ISSUE TITLE
How to turn off warnings messages ?

### ISSUE THREAD

**Issue by golubvladimir** [nuxt-community/nuxt-i18n#587]
Messages like this 
```
[vue-i18n] Value of key 'forms.fields.email_label' is not a string!
```

Options like ?
```
debug: false 
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c390">#c390</a>)</em></sub></div>

**Comment by golubvladimir** [comment]
```
    vueI18n: {
      silentTranslationWarn: true,
      silentFallbackWarn: true,
    },
```

**Comment by mhrabiee** [comment]
Why this message is outputted?
