### ISSUE TITLE
error  'localePath' is not defined

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-i18n#588]
### Version

[6.5.0](https://github.com/nuxt-i18n/releases/tag/6.5.0)

### Steps to reproduce

1) Installing nuxt-i18n.
2) Setting up default configs
3) Using localePath() in your components to reference a localized route inside a component method instead of on nuxt-link

The editor as well as the compiler will fail with error:

    /Users/me/Projects/jwr-nuxt/components/menu/Item.vue
      52:11  error  'localePath' is not defined  no-undef

### What is expected ?

The function running without any errors when using in a component method. Sometimes its required to dynamically figure out routes and it would be useful if localePath could also be used within a component method, instead of only on nuxt-link.

### What is actually happening?

It returns the function is undefined when called from a method instead of from nuxt-link.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c391">#c391</a>)</em></sub></div>

**Comment by rchl** [comment]
See here: https://codesandbox.io/s/2466w06q0r?fontsize=14&hidenavigation=1&theme=dark

It has `<nuxt-link :to="localePathAbout()">` with method defined as:
```js
  methods: {
    localePathAbout() {
      return this.localePath("about");
    }
  }
```

**Comment by rchl** [comment]
Closing due to no response and because it works for me.
Feel free to reopen if you can create a reproducible case.

**Comment by victororlyk** [comment]
@rchl 
Hello, I have  the same issue 

```
 <nuxt-link v-for="page in pages" :key="page.id" :to="localePath(page.to)">
      {{ page.title }}
    </nuxt-link>
```

![Screenshot 2021-04-26 at 00 45 16](https://user-images.githubusercontent.com/33072590/116010612-af025380-a628-11eb-95fd-dc1d218758d0.png)

in the [docs](https://i18n.nuxtjs.org/basic-usage) it is not saying to use method.

![Screenshot 2021-04-26 at 00 47 27](https://user-images.githubusercontent.com/33072590/116010667-0dc7cd00-a629-11eb-9365-ca38fb21e270.png)
And it  can crash only when you refresh the page or use force refresh

**Comment by rchl** [comment]
Sounds like there is something wrong with your project. Try to create a project that reproduces.

**Comment by AndriusTelesoftas** [comment]
@victororlyk Now 2 years later I am battling with this issue. 

I am wondering how you guys found solutions to this

**Comment by sammandanu** [comment]
I find the solution for this error, define this on your script `const localePath = useLocalePath();`
reference [here](https://phrase.com/blog/posts/nuxt-js-tutorial-i18n/)
@AndriusTelesoftas
