### ISSUE TITLE
switchLocalePath('the-language-code') returns root url instead of current page

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-i18n#589]
### Version

[6.5.0](https://github.com/nuxt-i18n/releases/tag/6.5.0)

### Steps to reproduce

1. Create a langauge swithcer component. Use: `switchLocalePath('da')` - like so: <nuxt-link :to="switchLocalePath('da')" class="flag da">
2. Go to a page, e.g. /pages/example. See the language swithcer component -- the url is: / instead of /da/pages/example.

### What is expected ?

The output should be /da/pages/example

### What is actually happening?

The output is /

### Additional comments?

This is how I configured my module config:

		[
			'nuxt-i18n',
			{
				lazy: true,
				langDir: 'lang/',
				defaultLocale: 'en',
				locales: [
					{
						code: 'en',
						file: 'en-US.js'
					},
					{
						code: 'da',
						file: 'da-DK.js'
					}
				]
			}
		]

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c392">#c392</a>)</em></sub></div>

**Comment by rchl** [comment]
This is basic functionality of the module and it's tested by tests so I don't think that it's fundamentally broken. Might be something else in your project causing the issue.

Here is a basic example where I have `nuxt-link :to="switchLocalePath('jp')` button on the /about page.
(It's not using lazy loading but that should be irrelevant.)

**Comment by simplenotezy** [comment]
Hey @rchl - thanks for your reply!

Is this parameter required, as you have set "inpage.vue"?

  nuxtI18n: {
    paths: {
      jp: "/inpagejp"
    }
  }

Because I don't have this.

**Comment by rchl** [comment]
No, `inpage.vue` is for another issue. For this issue only `about.vue` is relevant (`/about` path).

**Comment by simplenotezy** [comment]
OK great. I think I know the problem; if I use `switchLocalePath` in a Page, it works. However, if I use it within a component, say LanguageSwitcher, inside my Menu component, it won't work.

**Comment by simplenotezy** [comment]
Does your tests cover this scenario as well?

**Comment by simplenotezy** [comment]
By the way, this is how my `default.vue` layout looks like. Perhaps because Menu & Footer is outside `<nuxt />` is causing the problem?

**Comment by rchl** [comment]
You could fork my sandbox and try to reproduce it there.

**Comment by simplenotezy** [comment]
Wow. You were right. My flags had position absolute, but without z-index, so they were behind the logo banner, which always returned to `localePath('/')`. Setting the z-index on flags solved the problem. Sorry for any inconvenience.
