### ISSUE TITLE
Is there a way to add "github issues" for this project?

### ISSUE THREAD

**Issue by adi-zz** [nuxt-community/nuxt-i18n#59]
If I want to [add a new GitHub issue](https://github.com/nuxt-community/nuxt-i18n/issues/new), I see a message saying

> IMPORTANT: Please use the following link to create a new issue:
> https://nuxtjs.cmty.io/issues/new
> If your issue was not created using the app above, it will be closed immediately.

If I use [that link](https://nuxtjs.cmty.io/issues/new) to post my question, it will won't appear on this project GitHub page, but it will end up [here](https://nuxtjs.cmty.io/nuxt/docs/issues/c76).

**Comment by paulgv** [comment]
cmty is still a bit confusing for me too, I'd expect it to be a complement to GitHub issues, not an attempt to replace them completely. But since it's still a new thing, I guess we'll have to see how it evolves and how we get used to it :)

**Comment by adi-zz** [comment]
unfortunately, it was my fault, i didn't pay attention to the `I am opening an issue for` drop-down list. sorry

**Comment by adi-zz** [comment]
@paulgv as a small improvement, maybe you can change from the [GitHub new issue page](https://github.com/nuxt-community/nuxt-i18n/issues/new), from `https://nuxtjs.cmty.io/issues/new` to `https://nuxtjs.cmty.io/issues/new?repo=nuxt-community%2Fnuxt-i18n`.

**Comment by paulgv** [comment]
Done! Thanks @adi-zz
