### ISSUE TITLE
Type declarations missing for this.$i18n and this.$t

### ISSUE THREAD

**Issue by brandonwoo** [nuxt-community/nuxt-i18n#598]
### Version

[v6.5.0](https://github.com/nuxt-i18n/releases/tag/v6.5.0)

### Reproduction link

[https://codesandbox.io/s/github/brandonwoo/nuxt-i18n-type-definition-issue](https://codesandbox.io/s/github/brandonwoo/nuxt-i18n-type-definition-issue)

### Steps to reproduce

npm install
npm run dev

### What is expected ?

`this.$i18n.t`
`this.$t`
should be accessible on Vue instance without compile errors

### What is actually happening?

compile error will be output in console

```
 ERROR  ERROR in /Users/JPZ2487/Workspace/test/pages/index.vue(41,18):                              nuxt:typescript 14:37:14
41:18 Property '$t' does not exist on type '{ components: { Logo: {}; }; data(): any; }'.
    39 |   data () {
    40 |     return {
  > 41 |       test: this.$t('test'),
       |                  ^
    42 |       test2: this.$i18n.t('test')
    43 |     }
    44 |   }


 ERROR  ERROR in /Users/JPZ2487/Workspace/test/pages/index.vue(42,19):                              nuxt:typescript 14:37:14
42:19 Property '$i18n' does not exist on type '{ components: { Logo: {}; }; data(): any; }'.
    40 |     return {
    41 |       test: this.$t('test'),
  > 42 |       test2: this.$i18n.t('test')
       |                   ^
    43 |     }
    44 |   }
    45 | }
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c399">#c399</a>)</em></sub></div>

**Comment by rchl** [comment]
So you haven't added the `vue-shim.d.ts` shim, like [documentation suggest to do](https://typescript.nuxtjs.org/guide/setup.html#configuration) but to be fair that appears to make no difference for Vue files with `lang="ts"` script blocks. It seems like for TS components you need to explicitly annotate your Vue components (pages and components) with `Vue.extend()`. I've added those in my fork: https://codesandbox.io/s/laughing-hertz-x4bem . Examples at https://typescript.nuxtjs.org/cookbook/components/#template also use that so I guess it's the official way of doing things.

Just don't test my fork on codesandbox as it appears that it's UI is not really working correctly in terms of types. Export to zip and test locally instead.

@kevinmarrec Can you confirm my observation that vue-shim.d.ts doesn't really work when using Options API with TS and that `Vue.extend()` is the way to go?

But in the end there is no issue with `nuxt-i18n` types. You just need to make sure that your components are export with proper types.

**Comment by brandonwoo** [comment]
@rchl still getting the same issue with my project, using `Vue.extend`. updated the sandbox code, please take a look again

**Comment by brandonwoo** [comment]
doesn't seem to display properly on codesandbox, please run locally instead
https://github.com/brandonwoo/nuxt-i18n-type-definition-issue

i think i found the problem in my project
i'm injecting another plugin into the Vue instance in my project, and defining the interface for that seems to overwrite the nuxt-i18n type definitions, resulting in an error

https://github.com/brandonwoo/nuxt-i18n-type-definition-issue/blob/master/plugins/app-api.ts#L10-L12

is there any way to preserve nuxt-i18n type definitions on the Vue instance while adding definitions of my own?

**Comment by brandonwoo** [comment]
think i may be wrong, I still get the compilation error even after removing my custom plugin

https://github.com/brandonwoo/nuxt-i18n-type-definition-issue/tree/removed-plugin

**Comment by rchl** [comment]
In your latest case you have a typo in name of this module in tsconfig.json. `nuxt-18n` instead of `nuxt-i18n`. After fixing that (and removing your company's specific package), it works.

**Comment by brandonwoo** [comment]
@rchl ah, dumb typo miss on my side... thanks for the help, much appreciated
