### ISSUE TITLE
DateTime localization

### ISSUE THREAD

**Issue by veiss-com** [nuxt-community/nuxt-i18n#608]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://estadioberria.fundacionvital.eus/envivo/arranca-la-reforma-del-espacio-social/18](https://estadioberria.fundacionvital.eus/envivo/arranca-la-reforma-del-espacio-social/18)

## Version

"nuxt-i18n": "^6.4.0"

The date do not change its format when switching languages only in Chrome(79.0.3945.130) its works fine in Firefox(74.0b7) and Edge (44.17763.831.0)

This is my nuxt.config.js section :
~~~js
['nuxt-i18n', {
      strategy: 'prefix_except_default',
      locales: [
        {
          code: 'es',
          iso: 'es-ES',
          file: 'es-ES.js',
          name: 'Es'
        },
        {
          code: 'eu',
          iso: 'es-EU',
          file: 'es-EU.js',
          name: 'Eu'
        },
      ],
      langDir: 'lang/',
      lazy: true,
      defaultLocale: 'es',
      vueI18n: {
        dateTimeFormats: {
          es: {
            short: {
              day: 'numeric', month: 'numeric', year: 'numeric'
            }
          },
         eu: {
            short: {
              year: 'numeric', month: 'numeric', day: 'numeric'
            }
          },
        },
        fallbackLocale: 'es',
      }
    }]
~~~
In the template:
~~~vue
<time>{{$d(new Date(post.created_on), 'short' )}}</time>
~~~~

### What is expected ?

DateTime localization like that:
ES: 20/2/2020
EU :2020/2/20

### What is actually happening?

In Chrome only:
ES: 20/2/2020
EU: 20/2/2020

### Additional comments?

I´m very sorry but Ican provide you a repo I want to but ... company policy :(
My project is in production right now, so you can see the behavior in this [URL](https://estadioberria.fundacionvital.eus/envivo/arranca-la-reforma-del-espacio-social/18).
Simply change the language (in the top right in the header) and the dates are just below de post title.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c402">#c402</a>)</em></sub></div>

**Comment by rchl** [comment]
This package doesn't do any special handling for date formatting, it just uses functionality from https://github.com/kazupon/vue-i18n package directly. You probably can just as easily reproduce with pure Vue and vue-i18n.

And `vue-i18n` package just uses native browser API `Intl.DateTimeFormat` for date formatting so if you see any differences, it's most likely due to different levels of support from browsers or bugs or similar.

**Comment by rchl** [comment]
And you can test whether the browser is the reason by running this code in plain JS console:
```
new Intl.DateTimeFormat('eu').format(Date.now())
new Intl.DateTimeFormat('es').format(Date.now())
```

The results seem to match your observations for me.
