### ISSUE TITLE
[edge] Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”)

### ISSUE THREAD

**Issue by lucpotage** [nuxt-community/nuxt-i18n#61]
I was trying to use nuxt-i18n with the version 2 of Nuxt but I got the following errors:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: ;(function(e){let t={};if(e.hasOwnProper....

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: ;(function(e){setTimeout(()=>{const n=do....

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: ;(function(e){let n=null,t=0;const o={no....

**Comment by lucpotage** [comment]
Forgot to add with cmty. Sorry.

**Comment by paulgv** [comment]
Hi @lucpotage 
Hopefully I can give nuxt edge a try in the coming days, I want to take the opportunity to rewrite some parts of the module :)
