### ISSUE TITLE
npm run dev 遇到的一个问题

### ISSUE THREAD

**Issue by DeloYong** [nuxt-community/nuxt-i18n#618]
./.nuxt/nuxt-i18n/options.js 编译后出现
export const 0 = '.'
export const 1 = '/'
export const 2 = 'c'
export const 3 = 'o'
export const 4 = 'n'
export const 5 = 'f'
export const 6 = 'i'
export const 7 = 'g'
export const 8 = '/'
export const 9 = 'i'
export const 10 = '1'
export const 11 = '8'
export const 12 = 'n'
这样的报错～

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c404">#c404</a>)</em></sub></div>

**Comment by rchl** [comment]
It looks like an issue with how you are passing configuration options to the module.
