### ISSUE TITLE
The option ignorePaths does not work as expected

### ISSUE THREAD

**Issue by lucpotage** [nuxt-community/nuxt-i18n#62]
### Version

[v2.9.1](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v2.9.1)

### Reproduction link

https://github.com/lucpotage/bug-nuxt-i18n-ignore-routes

### Steps to reproduce

Using Nuxt 1.4.0 and Nuxt i18n 2.9.1, add the following config for the module:

```
{
  locales: [
    { code: 'en' },
    { code: 'fr' }
  ],
  defaultLocale: 'en',
  vueI18n: {
    fallbackLocale: 'en',
    messages: {
      'en': localesEn,
      'fr': localesFr
    }
  },
  ignorePaths: [
    '/fr/contact-us'
  ]
}
```

### What is expected ?

The route `/fr/contact-us`/ is reachable whereas the path is ignored in the configuration.

Better, I would expect Nuxt i18n to simply return a 404 instead of the page with default locale. Why isn't it the default behavior?

With the current implementation, it will affect the SEO because two different pages point to the same content:
- /contact-us (content in English)
- /fr/contact-us (content in English as fallback locale)

### What is actually happening?

From a page in French, I CAN reach `/fr/contact-us` an the page is translated in French.

From the English page `/contact-us`, I CAN reach the page `/fr/contact-us` but the page is not translated.

### Additional comments?

We can image another way to ignore routes with this module. In Nuxt, we can ignore a page by adding a `-` in front of its filename (see [here](https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0)).

So instead of:

```
ignorePaths: [
  '/fr/contact-us'
]
```

It could be:

```
routes: {
  'contact-us': {
    '-fr'
  }
}
```

And if there a several locales and you want to ignore all the translations of a page and only keep the English default route:

```
routes: {
  '-contact-us'
}
```

What do you think?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c54">#c54</a>)</em></sub></div>

**Comment by paulgv** [comment]
Thanks @lucpotage I like the idea of improving the `ignorePaths` option I'll keep your comments in mind for the next version.
I actually think it's working as expected in your case, what this option does is it does not generate localized paths for the given paths. So if you don't want `/contact-us` to be translated, you need to add `/contact-us` to your `ignorePaths`, then `/fr/contact-us` should throw a 404.

**Comment by lucpotage** [comment]
Unless I am mistaken, it does not work as expected. I have updated the reproduction link in my initial post. You will see I have added in Nuxt config the following snippet:

```
ignorePaths: [
  '/fr/contact-us'
]
```

According to your previous reply, the path '/fr/contact-us' should not be rendered nor generated. But it's not the case. I have noticed two issues:

1. With `nuxt generate`, the ignored paths are generated as HTML pages whereas they should not.
2. With `nuxt dev`, If you hit the page from another page with the same locale (let's say from `/fr`, the page is rendered instead of throwing a 404 error.

Could you please double check?

**Comment by paulgv** [comment]
Paths translation exclusion has changed a bit over the last versions, I'll assume this is working as expected now, feel free to open another issue if it doesn't!
https://nuxt-community.github.io/nuxt-i18n/routing.html#ignore-routes
