### ISSUE TITLE
`Cannot read property '_t' of null` when switching layouts

### ISSUE THREAD

**Issue by selfagency** [nuxt-community/nuxt-i18n#621]
### Version

[v6.6.0](https://github.com/nuxt-i18n/releases/tag/v6.6.0)

### Reproduction link

[https://gitlab.com/musiciansbass/musiciansbass-app](https://gitlab.com/musiciansbass/musiciansbass-app)

### Steps to reproduce

I am using a modal plugin called [Sweetalert2](https://github.com/avil13/vue-sweetalert2). This is the method I use to instantiate the popup:

```js
    showLogin(bus) {
      if (process.client) {
        // popup =
        this.$swal({
          ...this.popupOpts,
          title: this.$t('login.cta.login'),
          html: '<div id="alert-content"></div>',
          onOpen() {
            bus.emit('loadLoginForm')
          },
          onClose() {
            bus.emit('closePwForm')
          }
        })
      }
    },
```

This works just fine if I load my homepage (which uses one layout) or I enter from a different URL (a page using a different layout) and click the `login` button. If I click between internal pages which use the same layout and click `login`, everything works as expected.

If, *however*, I am on an internal page and click to return to the homepage (which switches layouts), or if I am on the homepage and click to an internal page (again, switching layouts) and I click the `login` button, I get the following error:

```console
TypeError: Cannot read property '_t' of null
    at VueComponent.Vue.$t (vue-i18n.esm.js?a925:178)
    at VueComponent.showLogin (Login.vue?7463:65)
    at eval (Login.vue?7463:47)
    at eval (mitt.es.js?14b7:57)
    at Array.map (<anonymous>)
    at Object.emit (mitt.es.js?14b7:57)
    at click (Buttons.global.vue?e4ea:27)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)
    at HTMLButtonElement.sentryWrapped (helpers.js?bf37:71)
```

And indeed, if I `console.log` the component, `_i18n` and `$i18n` are `null`:

```console
VueComponent {_uid: 22, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
[...]
_i18n: null
[...]
$i18n: null
[...]
__proto__: Vue
```

My navigation URLs are all variations of:

```jsx
<nuxt-link class="hoverline" :to="localePath(item.slug)">{{ item.title }}</nuxt-link>
```

Oddly, none of the components outside of the modal are having any trouble using the `$t` method. Only the modal has the problem. And I'm not doing anything asynchronously in terms of loading the modal itself, which I saw in a related issue as one proposed pain point.

Any help would be greatly appreciated.

Thanks

### What is expected ?

For the `i18n` object to not vanish from my Vue component when invoked in a modal window after changing layout contexts.

### What is actually happening?

The `i18n` object is vanishing from my Vue component when invoked in a modal window after changing layout contexts.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c406">#c406</a>)</em></sub></div>

**Comment by rchl** [comment]
I was thinking that the component might be in a destroyed state already but stack trace doesn't really support that suspicion, I think...

But still, please check this:
You could add `destroyed` hook (`or `beforeDestroy`, or both) to that component and check if it's triggered just before `showLogin` is called. vue-i18n is clearing all its APIs from the component when the component is destroying. Other things that you are using might not be doing the cleanup (maybe because they are sloppy or it's just not needed), so you might be getting away with those working.

Your repo is private so I can't check manually.

**Comment by selfagency** [comment]
This is what I get after loading a page, clicking to another page, and clicking `login`.

<img width="785" alt="Screenshot 2020-03-03 02 44 45" src="https://user-images.githubusercontent.com/2541728/75753516-f62cd700-5cf8-11ea-9bef-d51f0c212f0a.png">

**Comment by selfagency** [comment]
I also noticed my login button is firing twice for some reason

**Comment by rchl** [comment]
That is probably related to the issues. Maybe you can fork my codesanbox at https://codesandbox.io/s/nuxt-i18n-sweetaler2-issue-621-g29nw and try to reproduce your issue there. It seems to work for me in a simple case.

**Comment by selfagency** [comment]
Yeah I don't see anything so different between your configuration and my own and I see yours is working.

It looks like I have two different instances of my components instantiating for some reason. You can see two different components with different UIDs here. So my guess is, one is receiving the correct `this` and one is not. So this may not be an i18n issue at all then but an issue with Nuxt double-rendering components?

<img width="1054" alt="Screenshot 2020-03-03 13 31 23" src="https://user-images.githubusercontent.com/2541728/75807565-9879a880-5d53-11ea-8812-364a8773e906.png">

**Comment by selfagency** [comment]
Oh it's because I'm loading the component twice, in the main nav and the mobile nav. Duh.

**Comment by selfagency** [comment]
Ok, so I figured that the issue was that I had two instances of a component, both of which had the same event listener in it, listening for a command to open the modal. So I moved the event listeners into a separate component that is only invoked once so there aren't two copies of the event listeners. Sadly: No change.

<img width="394" alt="Screenshot 2020-03-03 14 35 01" src="https://user-images.githubusercontent.com/2541728/75812634-8cdeaf80-5d5c-11ea-8b69-09e56f49b03f.png">

**Comment by rchl** [comment]
Why is your click handler going through "mitt"? I don't think that's part of Vue/Nuxt/Sweetalert2? If your click handler doesn't execute in correct "this" context then it will fail.

**Comment by selfagency** [comment]
I use Mitt as an event bus on the main Vue prototype so I don't have to deal with bubbling up events from component to component.

**Comment by rchl** [comment]
Well, it's probably related to the problem.
If you are able to create repro then I'll have a look. Otherwise, I'm just guessing.
But you have to make sure that your `showLogin` method is invoked with `this` being the vue component instance. Maybe you have to bind it manually when adding event listener on mitt or use arrow function.

**Comment by rchl** [comment]
Since you said that it only fails after the layout has changed, it's probably because Vue component is recreated and you are not re-creating the event listener so the one set for the old component is triggering on "dead" component instance.
It would maybe be a better idea to create a Nuxt plugin that injects your "showModel" function into Vue so that you can call it from everywhere.
But again, that's without seeing your code so I'm just speculating that it might work.

**Comment by selfagency** [comment]
Thanks for all your help. Dropping Mitt and passing i18n tags as props instead of invoking `$t` in  seemed to do the trick.

**Comment by selfagency** [comment]
Wait, no it didn't. FFFFFFUUUUUUUU.

**Comment by selfagency** [comment]
Ok, if I take the `$t`'s out of my component methods and put them in as data, I can access them through `this`. Better than nothing!
