### ISSUE TITLE
allow custom pluralization

### ISSUE THREAD

**Issue by Graziel** [nuxt-community/nuxt-i18n#624]
### What problem does this feature solve?

https://kazupon.github.io/vue-i18n/guide/pluralization.html#custom-pluralization

### What does the proposed changes look like?

add it to options like
```beforeLanguageSwitch: (oldLocale, newLocale) => null,```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c411">#c411</a>)</em></sub></div>

**Comment by dschewchenko** [comment]
@Graziel create plugin for this and add to plugins: [] in nuxt.config
There write
`import VueI18n from "vue-i18n";

VueI18n.prototype.getChoiceIndex = function(choice, choicesLength) {
  // Your code here
}`

**Comment by davestewart** [comment]
Hey @dschewchenko

I'm new to Nuxt and have inherited a project using nuxt-i8n.

Do we also need to add the vue-18n package to the project?

**Comment by dschewchenko** [comment]
Hi
vue-18n is dependency of nuxt-i18n, you can to not include it in package.json
It's from [Docs](https://kazupon.github.io/vue-i18n/guide/pluralization.html#custom-pluralization)

**Comment by davestewart** [comment]
Thanks I saw that.

Just wasn't sure what to import:

```
// doesn't work :(
import <something> from 'nuxt-i18n'

// works :)
import VueI18n from 'vue-i18n
```

**Comment by rchl** [comment]
I'll close this since there is a solution.
There is not really any other great way to handle it since options need to be stringified when passed through the module and that limits the options.
