### ISSUE TITLE
trailing slash on localized index page

### ISSUE THREAD

**Issue by dschewchenko** [nuxt-community/nuxt-i18n#632]
I have:
- 2 locales en and cn(for example)
- underscore page(_.vue), for dynamic pages(data from backend).
- nuxt-i18n, strategy: "prefix_except_default", defaultLocale: "en".
- routes may to be without trailing slash at the end (example.com, example.com/cn)

If I use index.vue, all works as expected, but if I use _.vue, it cannot recognize cn locale
For _.vue works good, only with trailing slash at the end

### Version

[v6.6.0](https://github.com/nuxt-i18n/releases/tag/v6.6.0)

### Reproduction link

[https://codesandbox.io/s/fancy-haze-27wr0](https://codesandbox.io/s/fancy-haze-27wr0)

### Steps to reproduce

- go to /cn (without trailing slash on the end)
- get info
- you see "en" locale in console

### What is expected ?

Go to /cn and get current locale "cn"
Also correct behaviour of switchLocalePath method

### What is actually happening?

If you go to /cn, you will get current locale "en"
For now switchLocalePath method goes to "/cn/cn"(Chinese link) and "/cn"(English link) on "/cn" path

### Additional comments?

I'm using underscore page (_.vue), because of dynamic data from backend

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c416">#c416</a>)</em></sub></div>

**Comment by rchl** [comment]
I feel like technically it's doing the right thing. Otherwise, it wouldn't be possible to visit `/cn` path in english language, which might be an actual path of some site. The behavior you are asking for would be more magic and less compatible.

You could utilize https://nuxtjs.org/api/configuration-router#extendroutes to add /cn route that would redirect to /cn/cn. It would be quite specific fix but I don't think it's the right thing to have that logic in this module..

**Comment by dschewchenko** [comment]
@rchl /cn is not page, it's locale prefix

**Comment by rchl** [comment]
In your case it might not be expected but technically it's handled by `_.vue` route and that is not specific to this module but to Nuxt itself.

I'm not sure if https://nuxtjs.org/api/configuration-router#trailingslash option would help you here or just make things worse...

**Comment by dschewchenko** [comment]
No, it's handled by i18n. I've found problem. It generates "/cn/*" route for _.vue component. It will be good to change this behavior

**Comment by rchl** [comment]
Yeah, with your configuration that is expected:
`/*` for English
and
`/cn/*` for Chinese

I'm not sure what you would want to change and what do you consider a bug...

**Comment by dschewchenko** [comment]
I want to have generated route for localized pages without trailing slash
`/cn*`
I have configured `router.trailingSlash: false`, and it doesn't help me
Creating `index.vue` page doesn't help too. If I have `trailingSlash: false`, it must work everywhere, for every route

**Comment by rchl** [comment]
Your current configuration generates:
```
{
  path: "/cn/*",
  name: "all___cn"
},
{
  path: "/*",
  name: "all___en"
},
```

If you would write your routes manually, how would they look?
(Note that `/cn*` is not a valid route path)

**Comment by dschewchenko** [comment]
Page `/cn` loads without trailing slash, but it cannot recognize current locale from route. 

logs from `getLocaleFromRoute` function in utils.js
```
route.name: all___en
route.path: /cn
regexp: ___(en|ru|cn)(?:___default)?$ 
```

Generated routes in .nuxt/router.js
```
  {
    path: "/ru/*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___ru"
  }, {
    path: "/cn/*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___cn"
  }, {
    path: "/*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___en"
  }
```

if I manually change .nuxt/router.js to
```
{
    path: "/ru*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___ru"
  }, {
    path: "/cn*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___cn"
  }, {
    path: "/*",
    component: _00336638,
    pathToRegexpOptions: {"strict":true},
    name: "all___en"
  }
```
Logs will be:
```
route.name: all___cn
route.path: /cn
regexp: ___(en|ru|cn)(?:___default)?$ 
```
And it works as expected :)

**Comment by rchl** [comment]
So with that one someone can visit /cnfoo and still get page loaded. It doesn't seem right.

I believe you can't generate routes like `/cn*` through Nuxt's pages file structure so you need to use [router module](https://github.com/nuxt-community/router-module) for that.

But all in all, that doesn't seem like something for this module to handle.

**Comment by rchl** [comment]
I feel like there is no issue here that I could fix in a generic way. Just a very specific use case that should be handled in other ways. So I have to close this.

**Comment by gdg87** [comment]
@dschewchenko have you solved?
I need, for SEO optimization, my localized index page with no trailing slash but seems to be no option for that.
If I go on /en it redirect me to /en/.

Thanks

**Comment by dschewchenko** [comment]
No. I have added redirect from root pages. There was a lot of problems without it....
/en -> /en/
/es -> /es/
and for other pages redirect to without slash 
/es/downloads/ -> /es/downloads

**Comment by gdg87** [comment]
@rchl having all routes, also the prefixed, index without trailing spaces in important for SEO.
Nuxt router has  an option to remove trailing spaces and a good practice is to have all the route with the same pattern.
I try a fast change to the package to remove trailing slashes and it work.

So I can propose to add and option `trailingSlash` that if setted to false remove slashes from path.

I changed the line 120 of helpers/routes.js in this way
`path = `/${locale}${path.replace(/\/$/, "")}`
but it's must be change also the generated home url whene using localePath function.

Thaks in advantage

**Comment by rchl** [comment]
Try with the configuration option [mentioned earlier](https://github.com/nuxt-community/nuxt-i18n/issues/632#issuecomment-603172765).

**Comment by gdg87** [comment]
I already use this option and it works fine except for the index locale url that continue to use the trailing slashes.

**Comment by rchl** [comment]
@dschewchenko The outcome that you expect still kinda confuses me but I've made a fix for trailing slashes that you can try out: `yarn add nuxt-i18n@beta` or `npm i nuxt-i18n@beta`.

Your test on codesandbox doesn't seem to reproduce the problem anymore so I'm not sure how to test it.

**Comment by benjamincanac** [comment]
@rchl Has this fix been released yet?

**Comment by rchl** [comment]
@benjamincanac This particular issue was not considered a bug so was closed.

There were various other fixes to trailing slashes handling though.

And recently Nuxt had some regressions in that field also: https://github.com/nuxt/nuxt.js/issues/7823

So if you are having some issues it would be best if you could file a new issue.

**Comment by benjamincanac** [comment]
@rchl I see, I'm gonna investigate a bit more and file an issue if I can't find anything, it's about nuxt/content#412.

(Really nice to see that `nuxt-i18n` now uses content docs theme 🙂)
