### ISSUE TITLE
How can i set a nuxt-i18n $t(key) to a state key value ?

### ISSUE THREAD

**Issue by EnzoBatista** [nuxt-community/nuxt-i18n#637]
I put nuxt-i18n as a module inside the nuxt.config of my project,  wich means that it can be globally accessible (right?).
I know maybe have no much sense but I NEED to do that. 

**Wanna do something like this:**

~~~
const createStore = () => {
    return new Vuex.Store({
      state: {
        services: [
          {
            id: 2,
            imageLink: '/img/services/desarrollo_web_sitios',
            title:  $t('Langkey'),
          }
       ]
    }
  })
}`

**Comment by rchl** [comment]
Like every other Nuxt module that uses `inject` function, it's accessible from:
 - Vue instance
 - Nuxt Context object
 - Store instance

It's not accessible globally in all JS files like in your example.
You need to restructure the way you do things as that won't work.
