### ISSUE TITLE
When you try to change the language, the URL fragment changes but the data on the page does not

### ISSUE THREAD

**Issue by cawa-93** [nuxt-community/nuxt-i18n#643]
### Version

[v6.7.0](https://github.com/nuxt-i18n/releases/tag/v6.7.0)

### Reproduction link

[https://codesandbox.io/s/trusting-yalow-367bu](https://codesandbox.io/s/trusting-yalow-367bu)

### Steps to reproduce

- Open the sandbox.
- Use the link in the sandbox to change the language in my example

### What is expected ?

The URL fragment changes and the text in the h1 changes

### What is actually happening?

The URL fragment changes, but the text in the h1 remains unchanged

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c427">#c427</a>)</em></sub></div>

**Comment by rchl** [comment]
Are you using Firefox? I can reproduce on Firefox only.

**Comment by cawa-93** [comment]
@rchl I see this problem in the following browsers:
- macOS:
- - Firefox developer edition (75.0b7)
- - Google Chrome (80.0.3987.149)
- - Safari (13.0.5)
- Android
- - Firefox (68.6.0)
- - Google Chrome (80.0.3987.149)
- iPadOS
- - Google Chrome (unknown)

**Comment by JeremiGendron** [comment]
Same issue here, Windows Firefox has the bug but not Windows Chrome.

**Comment by rchl** [comment]
I found out what the issue is. It's a combination of default browser language that doesn't match any of supported locales and `nuxt-i18n` configuration not specifying `detectBrowserLanguage.fallbackLocale`.

I'll prepare a fix.
A possible workaround is to define fallback locale which is a good idea anyhow.

**Comment by JeremiGendron** [comment]
Thanks for the explanation

**Comment by Sshuichi** [comment]
Thank you so much for this PR! What an improvement!!!
