### ISSUE TITLE
syncRouteParams: false results in an error in plugin.routing when using switchLocalePath

### ISSUE THREAD

**Issue by lukaVarga** [nuxt-community/nuxt-i18n#644]
### Version

[v6.7.0](https://github.com/nuxt-i18n/releases/tag/v6.7.0)

### Reproduction link

[https://not-needed.com](https://not-needed.com)

### Steps to reproduce

Add the following config to vuex:
```
        vuex: {
          syncRouteParams: false,
        },
```

Reload the server / page

### What is expected ?

App should load and work

### What is actually happening?

App fails to load with an error coming from plugin.routing.js - `store.getters[`${vuex.moduleName}/localeRouteParams`](locale)` is not a function.

### Additional comments?

If `syncRouteParams` option is false, then the `localeRouteParams` getter within `plugin.main.js` does not get registered. However, `switchLocalePath` function within `plugin.routing.js` depends on `localeRouteParams` getter being present (if vuex and store are present, which both holds true with the configuration listed above)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c429">#c429</a>)</em></sub></div>

**Comment by rchl** [comment]
Thanks. Fixing in #645.
