### ISSUE TITLE
[BUG Report] getRouteBaseName and detectBrowserLanguage error 

### ISSUE THREAD

**Issue by MoeCasts** [nuxt-community/nuxt-i18n#65]
There are some errors in the moduld.

That's the getRouteBaseName function code.
```
return function getRouteBaseName(route) {
    route =  routeGetter.call(this, route)
    if (!route.name) {
      return null
    }
    const locales = <%= JSON.stringify(options.locales) %>
  for (let i = locales.length - 1; i >= 0; i--) {
      const regexp = new RegExp('-' + locales[i].code)
      if (route.name.match(regexp)) {
        return route.name.replace(regexp, '')
      }
    }
  }
```
```
const routeName = route && route.name ? app.getRouteBaseName(route.name) : 'index';
```
It's obvious that the function need a route argument, but there is a route.name been given.

It will cause that
```
Route Warning route xxx not exist.
```
I hope the author can fix as quick as possiable.

**Comment by MoeCasts** [comment]
@paulgv The bug just change app.getRouteBaseName(route.name) to app.getRouteBaseName(route). Can you change it in the new version?

**Comment by paulgv** [comment]
Thanks @MoeCasts ! This will be fixed in next release.
