### ISSUE TITLE
How to initialize language from localStorage

### ISSUE THREAD

**Issue by MoeCasts** [nuxt-community/nuxt-i18n#66]
I want to jump to the cached language in localStorage when the page loads

**Comment by jjhesk** [comment]
yes, how to do that?

**Comment by rchl** [comment]
You can probably implement that by creating a Nuxt plugin since you have access to `i18n` object and can manually load messages (strings). But since `localStorage` is client-only, it would only work in pure SPA mode so wouldn't be universally applicable. Not planning to add that natively.
