### ISSUE TITLE
setLocale on SSR in middleware gets overwritten to default locale on client side

### ISSUE THREAD

**Issue by silvio-e** [nuxt-community/nuxt-i18n#660]
### Version

[v6.8.1](https://github.com/nuxt-i18n/releases/tag/v6.8.1)

### Reproduction link

[https://github.com/silvio-e/nuxt-i18n-test](https://github.com/silvio-e/nuxt-i18n-test)

### Steps to reproduce

- clone, install, yarn dev
- click on ssr link for "se" or "en" locale.
- see correct set locale overwritten to default locale ("no")

### What is expected ?

That the ssr set locale persists.

### What is actually happening?

The ssr set locale gets overwritten with the default locale on client side.
![ssr-new-client-default-locale.gif](https://cmty.s3.eu-west-1.amazonaws.com/110467581/f685e080-7b15-11ea-a262-99cf556a3a93.gif)

### Additional comments?

I'm not sure if I'm on the right track to solve my goal - but at least does it work on client side. I want to use the i18n only for the translations but not for the routing as there will be to big difference between the countries. So I want to set the locale depending on the first part of the url which contains the locale like `/no/min-side/` or `/en/my-page/`. I thought to do that in a middleware which fires before every route change.

I set strategy to  `no_prefix` to avoid route changes and `detectBrowserLanguage: false`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c434">#c434</a>)</em></sub></div>

**Comment by rchl** [comment]
Your middleware runs on the server, where locale is set but then on the client, the locale is detected from the route again and reverts back to default.

There is actually a change on master (c8b05b123288574777046302e2a258558c841410) that is not released yet that will help with this case.

But, you have to fix your code also - the `setLocale` is an asynchronous method so you have to await it (or return its promise up the chain up to your middleware).

**Comment by rchl** [comment]
Should be resolved in `v6.11.0`.

**Comment by silvio-e** [comment]
Thanks, works great now!
