### ISSUE TITLE
detectBrowserLanguage: true / alwaysRedirect: true with nuxt generate --> redirection creates history entry in Safari.

### ISSUE THREAD

**Issue by XLeiSize** [nuxt-community/nuxt-i18n#661]
### Version

[v6.8.1](https://github.com/nuxt-i18n/releases/tag/v6.8.1)

### Reproduction link

[https://github.com/XLeiSize/nuxt-i18n-bug-demo](https://github.com/XLeiSize/nuxt-i18n-bug-demo)

### Steps to reproduce

- clone the project and install dependencies 
- run `nuxt generate`
- run a local server on your dist folder (if you have python3, you can run `npm run python-server`) 
- access localhost either in MacOS Safari, MacOS Firefox , or iOS Safari

### What is expected ?

redirect without creating history entry; meaning without being able click on "back" which display the website in default locale 

### What is actually happening?

redirection create a history entry : 

![FR.jpg](https://cmty.s3.eu-west-1.amazonaws.com/110467581/7e03e8d0-7b35-11ea-a262-99cf556a3a93.jpg)

And when you click on back, it shows the website in default locale : 

![EN.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/96178b70-7b35-11ea-a262-99cf556a3a93.png)

### Additional comments?

With a little bit of digging, I've found that the code responsible to the redirection is here : 
https://github.com/nuxt-community/nuxt-i18n/blob/3f6dbeacda351071202b2acb0cfbfd3092a30b3a/src/plugins/main.js#L181

During my test I've found a workaround that I believe is specific to my use case ; which is instead of using ``` redirect(redirectPath)
``` I've directly used ``` window.location.replace(redirectPath) ``` as it's what is used inside nuxt's redirect function ( https://github.com/nuxt/nuxt.js/blob/c02ded2d8622c290ba28c696d363426b825a0977/packages/vue-app/template/utils.js#L201 )

I know that the workaround compromises SSR so I'm not exactly sure what is the best solution for this use case, would love some inputs. 
And to be honest if it's even an issue with nuxt-i18n or with nuxt's redirect function.

Thanks :) 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c435">#c435</a>)</em></sub></div>

**Comment by rchl** [comment]
I think I have "accidentally" fixed it with latest version (6.11.0). Can you confirm?

**Comment by rchl** [comment]
BTW. Since it wasn't mentioned, I have to add that the precondition to reproducing this is to have primary language in the browser/OS set to one of the languages supported by your demo **that is not english**.

**Comment by XLeiSize** [comment]
Hey @rchl ! Thanks for your answer, indeed I forgot to mention that part.

Indeed it seems fixed with the latest version ! Thank you :) 
 So I assume it was fixed in[ this commit](https://github.com/nuxt-community/nuxt-i18n/commit/e99978dcba6ecea19c915e9aa6b5865dab2bc3b8) right ?

**Comment by rchl** [comment]
Yes.
