### ISSUE TITLE
No nuxt-i18n properties when using i18n one file component translation

### ISSUE THREAD

**Issue by rubat** [nuxt-community/nuxt-i18n#67]
### Version

[v3.2.3](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v3.2.3)

### Reproduction link

[https://github.com/nuxt-community/nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n)

### Steps to reproduce

Using Nuxt 1.4.0 and Nuxt i18n 3.2.3, vue-i18n-loader 0.3.0 

Config for the i18n module:
```javascript
locales: [
          { code: 'en', iso: 'en-US', name: 'English' },
          { code: 'de', iso: 'de-DE', name: 'Deutsch' }
        ],
        seo: false,
        vueI18n: {
          fallbackLocale: 'en',
          silentTranslationWarn: true,
          messages: {
            en: require('./locales/en.json'),
            de: require('./locales/de.json')
          }
        }
```

Config for the build loader:

```
vendor: ['element-ui', '@fortawesome/vue-fontawesome'],
    /*
    ** Run ESLint on save
    */
    extend(config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
        const vueLoader = config.module.rules.find(
          rule => rule.loader === 'vue-loader'
        )
        vueLoader.options.loaders['i18n'] = '@kazupon/vue-i18n-loader'
      }
    }
```

Component file:
```
<i18n>
...
</i18n>

<template>
  <div>
    {{ $i18n.locales }}
  </div>
</template>
```

### What is expected ?

Output of the $i18n properties, in this case the locales.

### What is actually happening?

No output of the locales. `$i18n.locale` print the locale.

### Additional comments?

Without the `<i18n>...</i18n` in the component file the locales are printed.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c59">#c59</a>)</em></sub></div>

**Comment by karellm** [comment]
I was wondering if there was any update on this front. I'm trying to use `<i18n>` for locale definitions too.
