### ISSUE TITLE
How to auto generate all the translation files which will scan all .vue and .js files in /pages and /components directories ?

### ISSUE THREAD

**Issue by HappyColour** [nuxt-community/nuxt-i18n#683]

**Comment by rchl** [comment]
Please explain properly what you want to achieve.

**Comment by HappyColour** [comment]
> Please explain properly what you want to achieve.
Hello rchl , My Nuxt project are multi languages, i need provide all languages translation files to translator. So I want to use some plugins auto generate all the translation files which will scan all .vue and .js files in /pages and /components directories .

**Comment by rchl** [comment]
Sorry, I don't know of any way to do that.

I'm assuming that you have per-page translations stored in vue files (in i18n blocks). That what would make this tricky. It's possible for sure but you would need to write a lot of custom code to achieve that.
