### ISSUE TITLE
Enabling "fallbackLocale" in "detectBrowserLanguage" intereferes with static page generation by breaking prerendering

### ISSUE THREAD

**Issue by Louvki** [nuxt-community/nuxt-i18n#689]
### Version
nuxt-i18n: 6.10.1
nuxt: 2.12.2

### Reproduction Link
https://codesandbox.io/s/romantic-neumann-y1bd1?file=/nuxt.config.js

### Steps to reproduce
I want to prerender 6 pages for the route of "pages\gen\_id\index.vue".
In the page I console.log the payload once it's received in the async data method.

1. Run "npm generate" 
2. Check the console. You will see it only logged out the payload for pages with the default locale. ("en/gen/1", "en/gen/2"). Meaning only 2 pages of the initial 6 will be pre-rendered.

1. Now comment out the "fallbackLocale" option in the i18n object in nuxt.config.js
2. Run "npm generate" 
3. Check the console. Now it will have logged out the payload for every page

### What is Expected?
"fallbackLocale" option should not interefere with static page generation.

### What is actually happening?
When "fallbackLocale" option is enabled, pages which are not of default locale do not get pre-rendered.

**Comment by rchl** [comment]
I can see this happening as the module will redirect to default locale if there is no cookie set yet and I'm assuming that during generation cookies are not sent or saved. This will probably also happen with `alwaysRedirect: true`.

It probably makes sense to special-case generation of pages. It would just need to be reliably detectable from a plugin. I will have a look at some point.

**Comment by rchl** [comment]
Resolved by #718 (spinned of from #715)
