### ISSUE TITLE
Route path doesn't persist when using localePath

### ISSUE THREAD

**Issue by EderOBarreto** [nuxt-community/nuxt-i18n#691]
So, I noticed an unexpected behavior regarding the localePath. When pushing a new route just changing its params, but not the path of it, a problem it happens, the path isn't persisted, so I am not able to just redefine the params, without having to set the path again. This doesn't happen when using the router on Vue.
So, I don't know if this is really a bug, so I would like to ask if this is the expected behavior when dealing with localePath, or it's really a bug.

This is the code that I used.
```
localePath({params: { ...this.$route.params, step: `${Number(this.$route.params.step) + n}` }})
```

And this was the result.

![image](https://user-images.githubusercontent.com/30441620/80712963-198dbb80-8ac9-11ea-80c9-ae49404d125f.png)

Here is an example using Vue that I found on Stackoverflow.

https://stackoverflow.com/questions/56383717/how-to-replace-one-parameter-in-vuejs-router/56388903#56388903

This is my first "contribution", so please, be gentle.

**Comment by rchl** [comment]
You need to pass a route name also but I'll look into it to see if I can make it optional.

**Comment by rchl** [comment]
Btw. It's `localePath`, not `locationPath`.

**Comment by EderOBarreto** [comment]
> Btw. It's `localePath`, not `locationPath`.

Yeah, I didn't notice. Sorry about that. And thanks for the answer.
