### ISSUE TITLE
How to use $t on a page in the 'export default' object?

### ISSUE THREAD

**Issue by Extarys** [nuxt-community/nuxt-i18n#693]
Last time I used nuxt it was during version 1 and I remember I had to add an import statement to use this.$t().

I have a component displaying a table with a lot of keywords. I'm assuming every time the component render it'll need to grab the translation again if I use it in the template part, so I'd like to grab the translation in the script part of the component.

I checked in the documentation but couldn't find what I was looking for.
```
data: () => {
  let word = this.$t('keyword');
  return { word }
}
```

I feel like this is dumb but I can't find the answer, thank you!

**Comment by rchl** [comment]
I'm not sure it's possible. You would need to have access to the vue-i18n instance that has all the translations loaded. You can import 'vue' and look into its prototype and find the I18n object there but not sure it will have translations loaded.

But in any case that's not a proper solution as you won't get reactivity this way. If user would change the language on your page (dynamically) then translations wouldn't update.

So you can maybe hack your way in but I would not recommend it.

**Comment by rchl** [comment]
Oh wait... You want to do that from script part of the component and not external script (I've just noticed your code snippet)?

Well, the problem in your snippet is that you are using an arrow function. The overrides `this` so don't do it. Generally avoid it in Vue components. It should work then.

But doing it that way is probably not any more efficient than using I18n directly in the template. The content will still be reactive and translations will be re-resolved on component render.

**Comment by Daniel-Mendes** [comment]
I use this: `Vue.prototype.$nuxt.$options.i18n.t('keyword')`

**Comment by rchl** [comment]
I think my answer addresses initial problem so closing.
