### ISSUE TITLE
Typescript and vue extend

### ISSUE THREAD

**Issue by gpessa** [nuxt-community/nuxt-i18n#697]
I'm using typescript and now trying to do something like this:

```javascript
export default Vue.extend({
  components: {},
  nuxtI18n: {
    paths: {
      en: '/about-us', // -> accessible at /about-us (no prefix since it's the default locale)
      fr: '/a-propos', // -> accessible at /fr/a-propos
      es: '/sobre' // -> accessible at /es/sobre
    }
  }
})
```

I get an error:

```javascript
Object literal may only specify known properties, and 'nuxtI18n' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.Vetur(2769)
```

Do you know how could i fix it?

**Comment by rchl** [comment]
To make your project aware of `nuxt-i18n` types you need to add them to your `types` array in `tsconfig.json`.
```js
{
    "compilerOptions": {
        // ...
        "types": [
            "nuxt-i18n",
        ],
    },
}
```

**Comment by gpessa** [comment]
> To make your project aware of `nuxt-i18n` types you need to add them to your `types` array in `tsconfig.json`.
> 
> ```js
> {
>     "compilerOptions": {
>         // ...
>         "types": [
>             "nuxt-i18n",
>         ],
>     },
> }
> ```

great! I have done, it. But only after I changed the order inside types it worked. Thanks!
