### ISSUE TITLE
How can I redirect translated url to the same page

### ISSUE THREAD

**Issue by Hayk1907** [nuxt-community/nuxt-i18n#712]
I want to translate url, but have an issue in ssr loading.  
here is my configuration `
```
// nuxt.config.js
module.exports = {
...
modules: [
   [
      'nuxt-i18n',
      {
        seo: true,
        lazy: true,
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: 'i18n_redirected',
          alwaysRedirect: false,
          fallbackLocale: 'hy'
        },
        locales: [
          {
            name: 'English',
            code: 'en',
            iso: 'en-US',
            file: 'en.json'
          },
          {
            name: 'Հայերեն',
            code: 'hy',
            iso: 'hy-AM',
            file: 'hy.json'
          }
        ],
        langDir: 'locales/',
        defaultLocale: 'hy',
        parsePages: false,
         pages: {
           about: {
             en: '/about',
             hy: '/մեր֊մասին'
           },
       }
   ]
}
```
it works in client side when i link to localePath('about') . but when i refresh my page it cant find  http://localhost:4000/մեր֊մասին

**Comment by rchl** [comment]
Can you reproduce the same with pure Nuxt if you just name your route `մեր֊մասին.vue`?

**Comment by Hayk1907** [comment]
my file structure `
```
pages/
├── about.vue
```
if i create մեր֊մասին․vue
```
pages/
├── about.vue
├── մեր֊մասին.vue
```
it will work . but  is there a way to not create մեր֊մասին.vue . because if it works in client side why it cant work in ssr ?

**Comment by rchl** [comment]
I'm trying to determine whether it's a problem with Nuxt or this module.
So you can't reproduce with `nuxt-i18n` disabled and route created manually?

**Comment by Hayk1907** [comment]
> I'm trying to determine whether it's a problem with Nuxt or this module.
> So you can't reproduce with `nuxt-i18n` disabled and route created manually?

no

**Comment by rchl** [comment]
There is actually a `encodePaths` option that you can toggle to fix it.
Check for it here: https://nuxt-community.github.io/nuxt-i18n/options-reference.html
(It's not enabled by default because it's not compatible with some regexp path patterns but if you don't have any custom ones then you should be fine)

**Comment by rchl** [comment]
I'll consider this a bug and fix with #731 by removing the `encodePaths` option and setting the default to `false`. See PR for reasoning.

**Comment by rchl** [comment]
Paths encoding was fixing issue #7 but that one doesn't reproduce in latest Nuxt anymore so I'm even more confident in getting rid of `encodePaths` option.

**Comment by Hayk1907** [comment]
Thanks it works

**Comment by moleCuleFFF** [comment]
This broke all my paths for languages such as Taiwanese, Japanese, Korean.

Please don't introduce MASSIVE breaking changes, to fix the issue of one user.

vue-router now expects all paths to be URIEncoded, can these be reverted and a correct solution for the problem found.

I'd rather not add URIEncode to every path on every class.

**Comment by rchl** [comment]
The removal of encodePaths is almost a year old.

At the time the removal made sense as VueRouter didn't expect encoded paths.

If you have an issue now because VueRouter and Nuxt made changes then feel free to report an issue about it with proper reproduction steps and it will be fixed.

**Comment by moleCuleFFF** [comment]
WIll do.
