### ISSUE TITLE
prefix strategy and index page

### ISSUE THREAD

**Issue by vana-dev** [nuxt-community/nuxt-i18n#741]
nuxt config: 

`i18n: {
    locales: [
      {
        code: 'en',
        file: 'en-US.js'
      },
      {
        code: 'pl',
        file: 'pl-PL.js'
      }
    ],
    defaultLocale: 'en',
    strategy: 'prefix',
    lazy: true,
    langDir: 'lang/',
  },`

expectations:
localhost/en/ - > reditect to index page
localhost/ - > 404 not found

reality: 
localhost/en/ - > 404 not found
localhost/ - > reditect to index page

what I'm missing in configuration to reach my expectations?

**Comment by rchl** [comment]
It should work like that and everything seems correct at first sight.

You might have to create reproduction if you want some help.

**Comment by vana-dev** [comment]
`detectBrowserLanguage: {
      alwaysRedirect: true,
    },`

fix the problem, but now I got another one, how to set redirection if there are no locales

localhost - > reditect to localhost/en/

**Comment by rchl** [comment]
mode: universal or spa?
deployment: static or node server?
which nuxt-i18n version?

**Comment by vana-dev** [comment]
universal
node server
6.6.0

**Comment by rchl** [comment]
First of all, try latest version. There were many changes since then, you might be hitting some old bug.

Redirect from localhost to localhost/en/ should work on node server.
If not I suggest creating a codesandbox repro.

**Comment by vana-dev** [comment]
You're right, updating package resolves all problems, thanks!
