### ISSUE TITLE
Add locale variable to loadLanguageAsync promise

### ISSUE THREAD

**Issue by bandy87** [nuxt-community/nuxt-i18n#742]
### A lazy-loaded promise js doesn't get the "locale" value just the ctx
await Promise.resolve(messages(context))

### Please add the value to the Promise
await Promise.resolve(messages(context, locale))

### Reason 
I made a common i18n loader with fallback handling and my handler doesn't get the desired language without a workaround. 

### Workaround
**en.js**
`
import loader from './i18nLoader'`
`export default (ctx) => {`
`  return loader(ctx, 'en')`
`}`

**i18nLoader**
`export default async (ctx, locale) => {`
`  return new Promise(async (resolve) => {`
`...`
`}}`

**Comment by rchl** [comment]
Implemented and will release in the next version (6.13).
