### ISSUE TITLE
How to translate pages with query params instead of prefixes ?

### ISSUE THREAD

**Issue by suleymangezsat** [nuxt-community/nuxt-i18n#745]
Hi,
Currently i'm working on a project that needs to have query parameter to identify which language to be used. For example : to set language as turkish in about page, route url should contain `/about?lang=tr`. However it seems that nuxt-i18n allows to have routes with prefixes like `/tr/about` so not working for my case.

**Comment by rchl** [comment]
You can try using `no_prefix` strategy, disabling browser language detection and adding a route middleware that will set locale (using `context.app.i18n.setLocale()`) based on query.

**Comment by rchl** [comment]
I hope that answers your question.

**Comment by hydRAnger** [comment]
> You can try using `no_prefix` strategy, disabling browser language detection and adding a route middleware that will set locale (using `context.app.i18n.setLocale()`) based on query.

@rchl thanks for the tips.

for someone reached here.
to solve this, I put this in `plugins/i18n.js`:
```
export default function ({ app, query }) {
  // init locale by query.lang for both client and server.
  if (query.lang && app.i18n.locale !== query.lang) {
   // you can do some check here to make sure query.lang is valid.
   
    app.i18n.setLocale(query.lang);
    app.i18n.locale = query.lang;
  }
}
```

in `nuxt.config.js`:
```
module.exports = {
  plugins: [
    // ...other plugins here

    { src: '~/plugins/i18n.js'}
  ],
  i18n: {
    // ...other i18n configs here
    
    // disable Nuxt's default strategy(based on prefix) and default browser language detection.
    // ref: https://i18n.nuxtjs.org/strategies#no_prefix
    // ref: https://github.com/nuxt-community/i18n-module/issues/745
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
  }
}
```

and instead of original solution which based on [localePath](https://i18n.nuxtjs.org/basic-usage/#nuxt-link)
maybe you need to do more work for things like link:
```
    <nuxt-link :to="{ path: '/', query: { lang: $i18n.locale } }">
      <img src="/img/logo.png" alt="logo image" />
    </nuxt-link>
```
or for router:
```
this.$router.push({
  path: '/',
  query: { lang: this.$i18n.locale },
});
```

**Comment by rttmax** [comment]
Here's what i did in nuxt 3 (plugins/i18n.js).
```
export default defineNuxtPlugin((context) => {
  const i18n = context.$i18n;
  const route = useRoute();

  // Check if the `locale` query parameter is present and different from the current locale
  if (route.query.locale && route.query.locale !== i18n.locale.value) {
    // If the `locale` value is valid, set the locale to the new value
    if (i18n.locales.value.includes(route.query.locale)) {
      i18n.locale.value = route.query.locale;
    } else {
      // If the `locale` value is not valid, set the locale to the default locale
      i18n.locale.value = i18n.defaultLocale;
    }
  }
});

```
and 
```
   strategy: "no_prefix",
   detectBrowserLanguage: false,
```
