### ISSUE TITLE
Router is not generating proper routes

### ISSUE THREAD

**Issue by janswist** [nuxt-community/nuxt-i18n#749]
### Version
nuxt: 2.12.2,
nuxt-i18n: 6.11.1

#### [mode](https://nuxtjs.org/api/configuration-mode):
 - [x] universal

### Reproduction link
https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-8iqxp

### Code
`/pages` structure:
![image](https://user-images.githubusercontent.com/5583954/83515527-cea30180-a4d5-11ea-9903-737727136dfb.png)

`_id.vue`:
```
<template lang="pug">
  div
    p Page
</template>
```

### Configuration:
```
i18n: {
    defaultLocale: 'pl',
    lazy: true,
    langDir: 'lang/',
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en-US.js',
        flag: '🇬🇧'
      },
      {
        code: 'pl',
        name: 'Polski',
        file: 'pl-PL.js',
        flag: '🇵🇱'
      },
    ],
}
```

autogenerated `.nuxt/router.js`:
![image](https://user-images.githubusercontent.com/5583954/83515685-11fd7000-a4d6-11ea-888a-4d81b7dfa35c.png)
![image](https://user-images.githubusercontent.com/5583954/83515701-17f35100-a4d6-11ea-9a22-ba7094caa1d7.png)

### What is Expected?
To have dynamic route working.

### What is actually happening?
`/en/therapists/:id` ~~is working even though in router it's not prefixed~~ now it's not working too. When I switch to default locale (pl) then page is not found unless I type `therapists` instead of `terapeuci`.

`/therapists` (index.vue) works perfectly in both langs.

**Comment by rchl** [comment]
I'm missing `nuxt-i18n` configuration to be able to reproduce and investigate this.
It works in tests.

Also, since you are renaming routes, I might needs the page-local `nuxtI18n` configuration.

Best if you just create a repro.

**Comment by janswist** [comment]
> I'm missing `nuxt-i18n` configuration to be able to reproduce and investigate this.
> It works in tests.
> 
> Also, since you are renaming routes, I might needs the page-local `nuxtI18n` configuration.
> 
> Best if you just create a repro.

I updated question with configuration. Will try to reproduce. Also, [official example that has codesandbox.io example](https://github.com/nuxt/nuxt.js/tree/dev/examples/custom-routes) also seems to be struggling with dynamic routes.

**Comment by rchl** [comment]
Only child routes can have no leading slash. Not sure what is happening with your routes but it doesn't look correct.

And I can't reproduce this issue myself so please create repro on codesanbox or github. There is a codesanbox template linked from bug report template.

**Comment by janswist** [comment]
Reproduction link: https://codesandbox.io/s/nuxt-nuxt-i18n-base-template-8iqxp - dynamic route works only for english (that is not default locale). When you change to polish and click again on dynamic route it will result in page not found.

**Comment by rchl** [comment]
You do need to also set custom paths for the dynamic route. Can't expect those to follow the `therapists/index.vue` magically as those are two separate routes.

So add this for `_id.vue` route:
```js
  nuxtI18n: {
    paths: {
      en: "/therapists/:id",
      pl: "/terapeuci/:id"
    }
  }
```

**Comment by janswist** [comment]
The simplest mistakes are easiest to make. Thanks a lot! That solved my problem - can't believe I didn't thought of it by myself. Pozdrawiam :)
