### ISSUE TITLE
Not created extendroutes

### ISSUE THREAD

**Issue by osnosov** [nuxt-community/nuxt-i18n#750]
### Version
nuxt-i18n: 6.12.1
nuxt: 2.12.2

#### [mode](https://nuxtjs.org/api/configuration-mode):
 - [X] universal

### Nuxt-i18n configuration
```
  i18n: {
    locales: [
      {
        code: "uk",
        iso: "uk-UA",
        name: "UA",
        file: "uk.json"
      },
      {
        code: "en",
        iso: "en-US",
        name: "EN",
        file: "en.json"
      }
    ],
    defaultLocale: "en",
    lazy: true,
    langDir: "lang/",
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: "language",
      alwaysRedirect: true
    },
    seo: false
  }
```

### Reproduction Link
[https://codesandbox.io/s/nuxt-i18n-custom-route-fjeed](https://codesandbox.io/s/nuxt-i18n-custom-route-fjeed)

### What is Expected?
to work extendroutes [https://nuxtjs.org/api/configuration-router#extendroutes](https://nuxtjs.org/api/configuration-router#extendroutes)

### What is actually happening?
Update nuxt-i18n with 6.11.1 to 6.12.1, stopped working extendroutes

**Comment by rchl** [comment]
Since I've changed module to use hooks rather than `extendRoutes`, that apparently changed the order of things and now module extends routes before your `extendRoutes` runs.

I didn't expect that and will have to look if it can be fixed but there is a workaround for now. You can use hooks like so:
```js
  hooks: {
    "build:extendRoutes": (routes, resolve) => {
      routes.push({
        name: "productRouter",
        path: "/:slug/:code(p\\d+)",
        component: resolve(__dirname, "components/Product.vue")
      });
      routes.push({
        name: "categoryRouter",
        path: "/:slug/:code(c\\d+)",
        component: resolve(__dirname, "components/Category.vue")
      });
    }
  },
```

**Comment by rchl** [comment]
Released `v6.12.2` with the fix.

**Comment by osnosov** [comment]
Thank you!

**Comment by MarineLB** [comment]
Hi, still getting a similar issue in `6.28.1` 

```
router: {
    extendRoutes (routes) {
      routes.push({name: 'home-momentum', path: '/m/:slug', component: '@/pages/index.vue'})
    }
  },
 ```
and getting `WARN  [nuxt-i18n] Couldn't read page component file (ENOENT: no such file or directory, open '@/pages/index.vue')`

**Comment by rchl** [comment]
That doesn't look related to the original issue.
I think the component must be an imported component instance and not just a string.
