### ISSUE TITLE
detectBrowserLanguage Redirect Alternate URL Name

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt-community/nuxt-i18n#765]
Hey,

I build my setup in the way that every page also has its path in its language.
So its not simply changing /en/[page-name] to /de/[page-name]/,
but also /en/[page-name-en] to /de/[page-name-de]

Is it somehow possible to let the module know which is the alternate url?
I already added meta and link language tags, but this does not seem to get honored in this decision.

Best,
F

**Comment by brumartins** [comment]
Yes it is, this feature is documented in the documentation [Routing - Custom paths](https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths) 😃

**Comment by fabianwohlfart** [comment]
That actually does not work for me.
_All_ my routes are dynamic, so at the point in the lifecycle where I have to add the alternate page paths I do not know about them yet. I would need the browserRedirect to fire after the asyncData method, because only then I have all the information I need to build the alternate page paths. Best would be to populate the paths from within the asyncData method, is that possible?
Additionally I cannot find the browserRedirect to fire beforeLanguageSwitch and onLanguageSwitched — I tried to log it but it does not show up in the console, is that correct?

**Comment by rchl** [comment]
Custom paths in `nuxt-i18n` are build-time based. So you have to decide the paths at build time already. This affects the routes that are generated.

If you only know your routes dynamically at runtime then you have to create your own, custom solution for that.

Something like having a "catch-all" route (`_.vue`) that will decide on locale to use. `nuxt-i18n` will do the initial redirect to `/en/foo` or `/de/foo` but then you have to have your own logic to redirect to locale-specific page name.

**Comment by fabianwohlfart** [comment]
Yes, I already use a catch-all route.
So what you suggest is that I should disable the nuxt-i18n browser redirection and build my own?

At the moment my solution is to let nuxt-i18n do the redirect, but if no page data can be loaded from my asyncData method I search for language siblings and will redirect the user if found.

So my question was aiming if there is a more easy way, eg tell nuxt-i18n the paths async and delay the redirect until they are set.

**Comment by rchl** [comment]
> So what you suggest is that I should disable the nuxt-i18n browser redirection and build my own?

No, unless it gets in the way.
The way you are doing it now (utilizing nuxt-i18n redirect + adjusting manually) probably makes more sense.

**Comment by fabianwohlfart** [comment]
Okay, thanks for your feedback!
Unless anybody else want to add something here or make a suggestion I will close this thread.

**Comment by rchl** [comment]
BTW. I've just recalled that there exists this functionality: https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html#dynamic-route-parameters

**Comment by janswist** [comment]
> BTW. I've just recalled that there exists this functionality: https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html#dynamic-route-parameters

Link doesn't work

**Comment by rchl** [comment]
Documentation has moved.
https://i18n.nuxtjs.org/lang-switcher.html#dynamic-route-parameters
