### ISSUE TITLE
TypeScript + Vue.extend()

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/nuxt-i18n#766]
Component:

```
export default Vue.extend({
  computed: {
    availableLocales() {
      return this.$i18n.locales.filter((i: any) => i.code !== this.$i18n.locale)
    }
  }
})
```

I'm getting an error:

![image](https://user-images.githubusercontent.com/5739191/84881858-42d1cd80-b0b0-11ea-8d3f-336d60fa05fe.png)

Is there a way to fix this?

**Comment by rchl** [comment]
The procedure is the same for all packages and it's also explained at https://nuxt-community.github.io/nuxt-i18n/setup.html

**Comment by webcoderkz** [comment]
@rchl i already added it to types, but it has no effect.

**Comment by rchl** [comment]
You'd have to provide your tsconfig.js configuration at least and if that looks right, a reproduction repo.

**Comment by webcoderkz** [comment]
tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@types/node", "@nuxt/types", "@nuxt/content", "nuxt-i18n"]
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

**Comment by rchl** [comment]
That looks correct so a repro would be necessary to figure out what's wrong.

**Comment by webcoderkz** [comment]
Does order of `nuxt-i18n` matters here?

**Comment by rchl** [comment]
Not really unless some other types before it are missing or have errors.

**Comment by webcoderkz** [comment]
Ok, i've restarted VSCode and it works now, thanks!
