### ISSUE TITLE
Cannot translation with  v3.0.0

### ISSUE THREAD

**Issue by lucpotage** [nuxt-community/nuxt-i18n#77]
### Version

[v3.0.0](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v3.0.0)

### Reproduction link

[https://github.com/nuxt-community/nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n)

### Steps to reproduce

Upgrade from 2.10.0 to v3.0.0.

### What is expected ?

The keypaths should be translated.

### What is actually happening?

The module does not translate the keypaths.

### Additional comments?

Could you please fix the changelog in GitHub so that I can help you find the solution?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c72">#c72</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hey! Did you update you config following the Migration guide? https://nuxt-community.github.io/nuxt-i18n/migrating.html
Could you share your config here so I can have a better understanding?
I've been using v3 with lazy loading enabled and disabled without any issue this far.
