### ISSUE TITLE
Use Router Module 

### ISSUE THREAD

**Issue by obaidsamadian** [nuxt-community/nuxt-i18n#770]
I'm using @nuxt/router-module. I've tried to use nuxt-i18n too, but unfortunately, It doesn't work. What should I do?

**Comment by rchl** [comment]
Specify exactly what you want to achieve and what is not working.

**Comment by obaidsamadian** [comment]
@rchl I've been using `nuxt-i18n` since I launched my project, now I wanted to use `@nuxt/router-module`, after installing and configuring `@nuxt/router-module`, `nuxt-i18n` stopped working. 

> Specify exactly what you want to achieve and what is not working.

**Comment by rchl** [comment]
Maybe try switching modules order.

**Comment by obaidsamadian** [comment]
> Maybe try switching modules order.
> 
> Otherwise please provide reproduction.

I can't change the order, `i18n` is located on `modules` and `router-moudle` is located on `buildModules`.

**Comment by rchl** [comment]
Put router modules in `modules` temporarily to see if that's the issue.

I assume it's the issue as the router module needs to augment routes first so that `nuxt-i18n` can see the routes that you've added through it.

**Comment by obaidsamadian** [comment]
> Put router module in `modules` temporarily to see if that's the issue.
> 
> I assume it's the issue as the router module needs to augment routes first so that `nuxt-i18n` can see the routes that you've added through it.

I've done ordering and didn't work. 
The default language (en) works now but when I try to switch language by `switchLocalePath()` function I get the following error 
![Screen Shot 2020-06-23 at 3 21 39 PM](https://user-images.githubusercontent.com/9816876/85395774-e8c88080-b565-11ea-8901-ba3722265a6d.png)

And when I try to switch the language manually by adding the language in the URL I get this `404 Not found` error.

**Comment by rchl** [comment]
I don't know then. You'd need to provide reproduction repo. There is a lot of variables here (modules configuration) and you haven't specified them.

**Comment by obaidsamadian** [comment]
> I don't know then. You'd need to provide reproduction repo. There is a lot of variables here (modules configuration) and you haven't specified them.

How can provide reproduction repo?

**Comment by rchl** [comment]
Create a minimal github repo. Or create Nuxt sandbox at http://codesandbox.io/

**Comment by tiretdusix** [comment]
Hello i would like to re-open this issue.

@obaidsamadian  I feel you man i'm in the exact same situation here.
@rchl There is nothing to "reproduce". This are dead simple to understand. He's asking how one can plug the two module to be compatible with each other.

Router-module will disable Nuxt ability to generate routes by itself based on the page directory files. Instead we get back control over the Router file and create route ourselves.
This means the router instance is not the same anymore.
Unfortunately the i18n-module seams to perform it's magic on the Nuxt built-in router only.

I really wish i could find a solution to this myself as these two modules are community reference and it believe they should get along.

Does anyone have any clue on a way to having routes declared from the `router.js` file and then translated by i18n module ?

**Comment by rchl** [comment]
1. Put both modules in `modules` since then you can control the order in which they process things.
2. Make sure `nuxt-i18n` is after `router-module` in the list. If it doesn't work, try the other way around.

If there are still issues, feel free to create a repro case so that I can test it quickly.

(Having `router-module` in `modules` rather than `buildModules` doesn't have any downsides besides requiring to put it in `dependencies` rather than `devDependencies`. It won't have any impact at runtime otherwise.)

**Comment by Dryymoon** [comment]
When we use native nuxt router - routing table builded before calling i18n-module.
In case of router-module usage - routing table created in runtime, rather prebuilded.
