### ISSUE TITLE
Ignore routes in-component option applies only after project is rebuilt

### ISSUE THREAD

**Issue by Menark** [nuxt-community/nuxt-i18n#783]
Version: ```"nuxt-i18n": "^6.5.0"```
Hello. I am using ignore routes in-component option in my page.
```
export default {
  nuxtI18n: {
    locales: ['de', 'ru']
  },
  ...
```
This setting applies only when project is rebuilt.
Is this default behavior?

**Comment by rchl** [comment]
Yes, this setting affects how routes are generated and that only happens at build time.

**Comment by Menark** [comment]
Thank you!
