### ISSUE TITLE
[SEO] Using custom blocks to define translations will break hreflang generation

### ISSUE THREAD

**Issue by tari404** [nuxt-community/nuxt-i18n#785]
### Version
nuxt-i18n: 6.13.0
nuxt: 2.13.2

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [X] universal

### Nuxt-i18n configuration

Not relevant, I thought
```
i18n: {
  vueI18n: {
    fallbackLocale: 'zh'
  },
  vueI18nLoader: true,
  locales: [
    {
      code: 'zh',
      iso: 'zh-CN'
    },
    {
      code: 'en',
      iso: 'en-US'
    }
  ],
  defaultLocale: 'zh',
  baseUrl: '/'
}
```

### Steps to reproduce
1. Define translations using custom blocks in Vue files
2. Use `$nuxtI18nSeo` to generate i18n SEO meta information (or set `seo` option to `true` in nuxt.config.js)

There is a minimal demo
```
// layouts/default.vue

<i18n lang="yaml">
zh:
  hello: "hello world!"
</i18n>

<script>
export default {
  head() {
    return this.$nuxtI18nSeo()
  }
}
</script>
```

### What is Expected?
Automatically generated hrevlang tags like:
```
<link ... rel="alternate" href="/" hreflang="zh-CN">
<link ... rel="alternate" href="/en" hreflang="en-US">
```

### What is actually happening?
I got wrong href in my link tags:
```
<link ... rel="alternate" href="undefined/" hreflang="zh-CN">
<link ... rel="alternate" href="undefined/en" hreflang="en-US">
```

### Reason, I thought
It seems that using `vue-i18n-loader` to generate translations from the `<i18n>` tag will create a new `vue-i18n` instance in the component. As a result, the `__baseUrl` field does not exist on this new instance, so the `nuxtI18nSeo` method does not generate the hrevlang links correctly.

In order to solve the problem I have encountered, here are two ways:
1. Remove `<i18n>` tag (that is not what I expected)
2. Manual set `__baseUrl` before generating header

```
// layouts/default.vue

<script>
export default {
  head() {
    this.$i18n.__baseUrl = '' // it works
    return this.$nuxtI18nSeo()
  }
}
</script>
```

Is this a bug that needs to be fixed? (English is not my first language, I hope to express it clearly)

**Comment by rchl** [comment]
Thanks for the thorough analysis. I've created a fix at https://github.com/nuxt-community/nuxt-i18n/pull/786

I'm already copying-over properties from the root instance when a local one is created but that one variable was forgotten.
