### ISSUE TITLE
Can nuxt-i18n auto detect locale or only language?

### ISSUE THREAD

**Issue by kgrosvenor** [nuxt-community/nuxt-i18n#790]
Thanks for the lib

**Comment by rchl** [comment]
I'm not sure what is your question about exactly. Can you be more specific?

**Comment by kgrosvenor** [comment]
@rchl  for example en-GB, fr-CA, de-DE rather than just en, fr, de for example.

**Comment by rchl** [comment]
It does handle locale codes in those formats, yes. If you define your locale with that `code` then it will be matched exactly.

**Comment by kgrosvenor** [comment]
Awesome @rchl thank you for clarifying! 💯 will close the issue since it isn't one 👍
