### ISSUE TITLE
cannot upgrade from 2.0

### ISSUE THREAD

**Issue by callmewhy** [nuxt-community/nuxt-i18n#83]
### Version

[v3.1.0](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v3.1.0)

### Reproduction link

[https://nuxt-community.github.io/nuxt-i18n/basic-usage.html](https://nuxt-community.github.io/nuxt-i18n/basic-usage.html)

### Steps to reproduce

1. npm install i18n-nuxt
2. edit nuxt.config.js
3. npm run dev

### What is expected ?

it should work

### What is actually happening?

throw an error:

 ERROR 

  TypeError: Cannot read property 'rows' of undefined
  
  
  - components.js:24 Property
    [invested-website]/[.3.1.0@nuxt-i18n]/src/helpers/components.js:24:36
  
  - walk.js:30 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:30:18
  
  - walk.js:341 Object.base.ObjectExpression
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:341:5
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:183 Object.skipThrough
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:183:37
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:376 Object.base.NewExpression.base.CallExpression
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:376:9
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:183 Object.skipThrough
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:183:37
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:237 Object.base.ReturnStatement.base.YieldExpression.base.AwaitExpre    ssion
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:237:24
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:183 Object.skipThrough
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:183:37
  
  - walk.js:29 c
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:29:15
  
  - walk.js:201 Object.base.ExpressionStatement.base.ParenthesizedExpression
    [invested-website]/[.5.5.3@acorn]/dist/walk.js:201:35
  

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c78">#c78</a>)</em></sub></div>

**Comment by paulgv** [comment]
Hi @callmewhy 
Please follow this issue for more info: https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c73
