### ISSUE TITLE
TypeError: Cannot read property 'options' of null

### ISSUE THREAD

**Issue by mahnuh** [nuxt-community/nuxt-i18n#85]
### Version

[v3.2.0](https://github.com/nuxt-community/nuxt-i18n/releases/tag/v3.2.0)

### Reproduction link

[https://github.com/nuxt-community/starter-template](https://github.com/nuxt-community/starter-template)

### Steps to reproduce

- init project using nuxt starter template
- add nuxt-i18n

### What is expected ?

npm run dev will work

### What is actually happening?

When running npm run dev: http://sharedby.manuel-heidrich.com/UFFUYf/5lcBWAFook

and the browser only shows Cannot GET /

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxt-i18n/issues/c80">#c80</a>)</em></sub></div>

**Comment by FransTwisk** [comment]
I was about to open an issue for this as well, but you beat me to it! Experiencing the exact same thing after upgrading from v2 and adjusting all necessary configurations.

**Comment by mahnuh** [comment]
@FransTwisk how did you configure it?

**Comment by FransTwisk** [comment]
Options are stored in `config/i18n.js` and imported into `nuxt.config.js`: 

const { I18N } = require('./config/i18n.js')

['nuxt-i18n', I18N]

**Comment by mahnuh** [comment]
3.0.0 and 3.1.0 do not work as well.

**Comment by paulgv** [comment]
Hi! This should be fixed in v3.2.1, it looks like an issue with latest releases of `esm`, the version is now locked to 3..0.28 which should work properly!

**Comment by mahnuh** [comment]
Awesome, thanks!
